/// A discovered record hint — an automatically-matched historical record
/// that may belong to a person in the tree.
///
/// Hints are generated by [RecordHintsService] by searching external APIs
/// (FamilySearch, WikiTree, Chronicling America, NARA, Open Archives) and
/// storing potential matches for the user to review.
class RecordHint {
  String id;
  String personId;

  /// The external API that found this hint.
  /// One of: `familysearch`, `wikitree`, `chronicling_america`, `nara`,
  /// `open_archives`, `find_a_grave`.
  String apiSource;

  /// External record identifier (API-specific).
  String externalRecordId;

  /// Human-readable title for the hinted record.
  String title;

  /// Brief summary / extracted info from the record.
  String? summary;

  /// URL to the record on the external site.
  String recordUrl;

  /// URL to a thumbnail or record image, if available.
  String? imageUrl;

  /// Match confidence: 0.0 (no match) to 1.0 (perfect match).
  double confidence;

  /// Status of the hint: `pending`, `accepted`, `dismissed`.
  String status;

  /// Tree scope — mirrors Person.treeId.
  String? treeId;

  /// Unix-millisecond timestamp when the hint was discovered.
  int? discoveredAt;

  /// Unix-millisecond timestamp when the user accepted/dismissed the hint.
  int? resolvedAt;

  /// Unix-millisecond timestamp of the last local modification (for sync).
  int? updatedAt;

  RecordHint({
    required this.id,
    required this.personId,
    required this.apiSource,
    required this.externalRecordId,
    required this.title,
    this.summary,
    required this.recordUrl,
    this.imageUrl,
    this.confidence = 0.5,
    this.status = 'pending',
    this.treeId,
    this.discoveredAt,
    this.resolvedAt,
    this.updatedAt,
  });

  bool get isPending => status == 'pending';
  bool get isAccepted => status == 'accepted';
  bool get isDismissed => status == 'dismissed';

  /// Confidence as a human-readable label.
  String get confidenceLabel {
    if (confidence >= 0.9) return 'Very High';
    if (confidence >= 0.7) return 'High';
    if (confidence >= 0.5) return 'Medium';
    if (confidence >= 0.3) return 'Low';
    return 'Very Low';
  }

  Map<String, dynamic> toMap() => {
        'id': id,
        'personId': personId,
        'apiSource': apiSource,
        'externalRecordId': externalRecordId,
        'title': title,
        'summary': summary,
        'recordUrl': recordUrl,
        'imageUrl': imageUrl,
        'confidence': confidence,
        'status': status,
        'treeId': treeId,
        'discoveredAt': discoveredAt,
        'resolvedAt': resolvedAt,
        'updatedAt': updatedAt,
      };

  factory RecordHint.fromMap(Map<String, dynamic> map) => RecordHint(
        id: map['id'] as String,
        personId: map['personId'] as String,
        apiSource: map['apiSource'] as String,
        externalRecordId: map['externalRecordId'] as String,
        title: map['title'] as String,
        summary: map['summary'] as String?,
        recordUrl: map['recordUrl'] as String,
        imageUrl: map['imageUrl'] as String?,
        confidence: (map['confidence'] as num?)?.toDouble() ?? 0.5,
        status: map['status'] as String? ?? 'pending',
        treeId: map['treeId'] as String?,
        discoveredAt: map['discoveredAt'] as int?,
        resolvedAt: map['resolvedAt'] as int?,
        updatedAt: map['updatedAt'] as int?,
      );
}
