import '../models/place.dart';

/// Africa: ISO 3166-2 level-2 administrative subdivisions (districts, counties,
/// parishes, municipalities, etc.) plus all United States counties (FIPS).
// ignore_for_file: lines_longer_than_80_chars
const List<Place> placesL2Africa = [

  // ── Burkina Faso ────────────────────────────────────────
  Place(continent:'Africa', name:'Balé', modernCountry:'Burkina Faso', iso3:'BFA', state:'Boucle du Mouhoun', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Bam', modernCountry:'Burkina Faso', iso3:'BFA', state:'Centre-Nord', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Banwa', modernCountry:'Burkina Faso', iso3:'BFA', state:'Boucle du Mouhoun', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Bazèga', modernCountry:'Burkina Faso', iso3:'BFA', state:'Centre-Sud', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Bougouriba', modernCountry:'Burkina Faso', iso3:'BFA', state:'Sud-Ouest', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Boulgou', modernCountry:'Burkina Faso', iso3:'BFA', state:'Centre-Est', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Boulkiemdé', modernCountry:'Burkina Faso', iso3:'BFA', state:'Centre-Ouest', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Comoé', modernCountry:'Burkina Faso', iso3:'BFA', state:'Cascades', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Ganzourgou', modernCountry:'Burkina Faso', iso3:'BFA', state:'Plateau-Central', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Gnagna', modernCountry:'Burkina Faso', iso3:'BFA', state:'Est', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Gourma', modernCountry:'Burkina Faso', iso3:'BFA', state:'Est', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Houet', modernCountry:'Burkina Faso', iso3:'BFA', state:'Hauts-Bassins', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Ioba', modernCountry:'Burkina Faso', iso3:'BFA', state:'Sud-Ouest', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Kadiogo', modernCountry:'Burkina Faso', iso3:'BFA', state:'Centre', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Komondjari', modernCountry:'Burkina Faso', iso3:'BFA', state:'Est', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Kompienga', modernCountry:'Burkina Faso', iso3:'BFA', state:'Est', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Kossi', modernCountry:'Burkina Faso', iso3:'BFA', state:'Boucle du Mouhoun', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Koulpélogo', modernCountry:'Burkina Faso', iso3:'BFA', state:'Centre-Est', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Kouritenga', modernCountry:'Burkina Faso', iso3:'BFA', state:'Centre-Est', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Kourwéogo', modernCountry:'Burkina Faso', iso3:'BFA', state:'Plateau-Central', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Kénédougou', modernCountry:'Burkina Faso', iso3:'BFA', state:'Hauts-Bassins', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Loroum', modernCountry:'Burkina Faso', iso3:'BFA', state:'Nord', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Léraba', modernCountry:'Burkina Faso', iso3:'BFA', state:'Cascades', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Mouhoun', modernCountry:'Burkina Faso', iso3:'BFA', state:'Boucle du Mouhoun', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Nahouri', modernCountry:'Burkina Faso', iso3:'BFA', state:'Centre-Sud', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Namentenga', modernCountry:'Burkina Faso', iso3:'BFA', state:'Centre-Nord', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Nayala', modernCountry:'Burkina Faso', iso3:'BFA', state:'Boucle du Mouhoun', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Noumbiel', modernCountry:'Burkina Faso', iso3:'BFA', state:'Sud-Ouest', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Oubritenga', modernCountry:'Burkina Faso', iso3:'BFA', state:'Plateau-Central', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Oudalan', modernCountry:'Burkina Faso', iso3:'BFA', state:'Sahel', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Passoré', modernCountry:'Burkina Faso', iso3:'BFA', state:'Nord', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Poni', modernCountry:'Burkina Faso', iso3:'BFA', state:'Sud-Ouest', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Sanguié', modernCountry:'Burkina Faso', iso3:'BFA', state:'Centre-Ouest', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Sanmatenga', modernCountry:'Burkina Faso', iso3:'BFA', state:'Centre-Nord', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Sissili', modernCountry:'Burkina Faso', iso3:'BFA', state:'Centre-Ouest', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Soum', modernCountry:'Burkina Faso', iso3:'BFA', state:'Sahel', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Sourou', modernCountry:'Burkina Faso', iso3:'BFA', state:'Boucle du Mouhoun', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Séno', modernCountry:'Burkina Faso', iso3:'BFA', state:'Sahel', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Tapoa', modernCountry:'Burkina Faso', iso3:'BFA', state:'Est', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Tuy', modernCountry:'Burkina Faso', iso3:'BFA', state:'Hauts-Bassins', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Yagha', modernCountry:'Burkina Faso', iso3:'BFA', state:'Sahel', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Yatenga', modernCountry:'Burkina Faso', iso3:'BFA', state:'Nord', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Ziro', modernCountry:'Burkina Faso', iso3:'BFA', state:'Centre-Ouest', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Zondoma', modernCountry:'Burkina Faso', iso3:'BFA', state:'Nord', historicalContext:'Province of Burkina Faso.'),
  Place(continent:'Africa', name:'Zoundwéogo', modernCountry:'Burkina Faso', iso3:'BFA', state:'Centre-Sud', historicalContext:'Province of Burkina Faso.'),

  // ── Cabo Verde ──────────────────────────────────────────
  Place(continent:'Africa', name:'Boa Vista', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Barlavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'Brava', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Sotavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'Maio', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Sotavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'Mosteiros', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Sotavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'Paul', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Barlavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'Porto Novo', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Barlavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'Praia', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Sotavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'Ribeira Brava', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Barlavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'Ribeira Grande', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Barlavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'Ribeira Grande de Santiago', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Sotavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'Sal', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Barlavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'Santa Catarina', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Sotavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'Santa Catarina do Fogo', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Sotavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'Santa Cruz', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Sotavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'São Domingos', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Sotavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'São Filipe', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Sotavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'São Lourenço dos Órgãos', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Sotavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'São Miguel', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Sotavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'São Salvador do Mundo', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Sotavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'São Vicente', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Barlavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'Tarrafal', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Sotavento', historicalContext:'Municipality of Cabo Verde.'),
  Place(continent:'Africa', name:'Tarrafal de São Nicolau', modernCountry:'Cabo Verde', iso3:'CPV', state:'Ilhas de Barlavento', historicalContext:'Municipality of Cabo Verde.'),

  // ── Guinea ──────────────────────────────────────────────
  Place(continent:'Africa', name:'Beyla', modernCountry:'Guinea', iso3:'GIN', state:'Nzérékoré', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Boffa', modernCountry:'Guinea', iso3:'GIN', state:'Boké', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Boké', modernCountry:'Guinea', iso3:'GIN', state:'Boké', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Coyah', modernCountry:'Guinea', iso3:'GIN', state:'Kindia', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Dabola', modernCountry:'Guinea', iso3:'GIN', state:'Faranah', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Dalaba', modernCountry:'Guinea', iso3:'GIN', state:'Mamou', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Dinguiraye', modernCountry:'Guinea', iso3:'GIN', state:'Faranah', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Dubréka', modernCountry:'Guinea', iso3:'GIN', state:'Kindia', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Faranah', modernCountry:'Guinea', iso3:'GIN', state:'Faranah', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Forécariah', modernCountry:'Guinea', iso3:'GIN', state:'Kindia', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Fria', modernCountry:'Guinea', iso3:'GIN', state:'Boké', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Gaoual', modernCountry:'Guinea', iso3:'GIN', state:'Boké', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Guékédou', modernCountry:'Guinea', iso3:'GIN', state:'Nzérékoré', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Kankan', modernCountry:'Guinea', iso3:'GIN', state:'Kankan', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Kindia', modernCountry:'Guinea', iso3:'GIN', state:'Kindia', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Kissidougou', modernCountry:'Guinea', iso3:'GIN', state:'Faranah', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Koubia', modernCountry:'Guinea', iso3:'GIN', state:'Labé', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Koundara', modernCountry:'Guinea', iso3:'GIN', state:'Boké', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Kouroussa', modernCountry:'Guinea', iso3:'GIN', state:'Kankan', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Kérouané', modernCountry:'Guinea', iso3:'GIN', state:'Kankan', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Labé', modernCountry:'Guinea', iso3:'GIN', state:'Labé', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Lola', modernCountry:'Guinea', iso3:'GIN', state:'Nzérékoré', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Lélouma', modernCountry:'Guinea', iso3:'GIN', state:'Labé', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Macenta', modernCountry:'Guinea', iso3:'GIN', state:'Nzérékoré', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Mali', modernCountry:'Guinea', iso3:'GIN', state:'Labé', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Mamou', modernCountry:'Guinea', iso3:'GIN', state:'Mamou', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Mandiana', modernCountry:'Guinea', iso3:'GIN', state:'Kankan', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Nzérékoré', modernCountry:'Guinea', iso3:'GIN', state:'Nzérékoré', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Pita', modernCountry:'Guinea', iso3:'GIN', state:'Mamou', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Siguiri', modernCountry:'Guinea', iso3:'GIN', state:'Kankan', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Tougué', modernCountry:'Guinea', iso3:'GIN', state:'Labé', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Télimélé', modernCountry:'Guinea', iso3:'GIN', state:'Kindia', historicalContext:'Prefecture of Guinea.'),
  Place(continent:'Africa', name:'Yomou', modernCountry:'Guinea', iso3:'GIN', state:'Nzérékoré', historicalContext:'Prefecture of Guinea.'),

  // ── Equatorial Guinea ───────────────────────────────────
  Place(continent:'Africa', name:'Annobon', modernCountry:'Equatorial Guinea', iso3:'GNQ', state:'Région Insulaire', historicalContext:'Province of Equatorial Guinea.'),
  Place(continent:'Africa', name:'Bioko Nord', modernCountry:'Equatorial Guinea', iso3:'GNQ', state:'Région Insulaire', historicalContext:'Province of Equatorial Guinea.'),
  Place(continent:'Africa', name:'Bioko Sud', modernCountry:'Equatorial Guinea', iso3:'GNQ', state:'Région Insulaire', historicalContext:'Province of Equatorial Guinea.'),
  Place(continent:'Africa', name:'Centro Sud', modernCountry:'Equatorial Guinea', iso3:'GNQ', state:'Région Continentale', historicalContext:'Province of Equatorial Guinea.'),
  Place(continent:'Africa', name:'Djibloho', modernCountry:'Equatorial Guinea', iso3:'GNQ', state:'Région Continentale', historicalContext:'Province of Equatorial Guinea.'),
  Place(continent:'Africa', name:'Kié-Ntem', modernCountry:'Equatorial Guinea', iso3:'GNQ', state:'Région Continentale', historicalContext:'Province of Equatorial Guinea.'),
  Place(continent:'Africa', name:'Littoral', modernCountry:'Equatorial Guinea', iso3:'GNQ', state:'Région Continentale', historicalContext:'Province of Equatorial Guinea.'),
  Place(continent:'Africa', name:'Wele-Nzas', modernCountry:'Equatorial Guinea', iso3:'GNQ', state:'Région Continentale', historicalContext:'Province of Equatorial Guinea.'),

  // ── Guinea-Bissau ───────────────────────────────────────
  Place(continent:'Africa', name:'Bafatá', modernCountry:'Guinea-Bissau', iso3:'GNB', state:'Leste', historicalContext:'Region of Guinea-Bissau.'),
  Place(continent:'Africa', name:'Biombo', modernCountry:'Guinea-Bissau', iso3:'GNB', state:'Norte', historicalContext:'Region of Guinea-Bissau.'),
  Place(continent:'Africa', name:'Bolama / Bijagós', modernCountry:'Guinea-Bissau', iso3:'GNB', state:'Sul', historicalContext:'Region of Guinea-Bissau.'),
  Place(continent:'Africa', name:'Cacheu', modernCountry:'Guinea-Bissau', iso3:'GNB', state:'Norte', historicalContext:'Region of Guinea-Bissau.'),
  Place(continent:'Africa', name:'Gabú', modernCountry:'Guinea-Bissau', iso3:'GNB', state:'Leste', historicalContext:'Region of Guinea-Bissau.'),
  Place(continent:'Africa', name:'Oio', modernCountry:'Guinea-Bissau', iso3:'GNB', state:'Norte', historicalContext:'Region of Guinea-Bissau.'),
  Place(continent:'Africa', name:'Quinara', modernCountry:'Guinea-Bissau', iso3:'GNB', state:'Sul', historicalContext:'Region of Guinea-Bissau.'),
  Place(continent:'Africa', name:'Tombali', modernCountry:'Guinea-Bissau', iso3:'GNB', state:'Sul', historicalContext:'Region of Guinea-Bissau.'),

  // ── Morocco ─────────────────────────────────────────────
  Place(continent:'Africa', name:'Agadir-Ida-Ou-Tanane', modernCountry:'Morocco', iso3:'MAR', state:'Souss-Massa', historicalContext:'Prefecture of Morocco.'),
  Place(continent:'Africa', name:'Al Haouz', modernCountry:'Morocco', iso3:'MAR', state:'Marrakech-Safi', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Al Hoceïma', modernCountry:'Morocco', iso3:'MAR', state:'Tanger-Tétouan-Al Hoceïma', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Aousserd (EH)', modernCountry:'Morocco', iso3:'MAR', state:'Dakhla-Oued Ed-Dahab (EH)', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Assa-Zag (EH-partial)', modernCountry:'Morocco', iso3:'MAR', state:'Guelmim-Oued Noun (EH-partial)', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Azilal', modernCountry:'Morocco', iso3:'MAR', state:'Béni Mellal-Khénifra', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Benslimane', modernCountry:'Morocco', iso3:'MAR', state:'Casablanca-Settat', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Berkane', modernCountry:'Morocco', iso3:'MAR', state:'L\'Oriental', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Berrechid', modernCountry:'Morocco', iso3:'MAR', state:'Casablanca-Settat', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Boujdour (EH)', modernCountry:'Morocco', iso3:'MAR', state:'Laâyoune-Sakia El Hamra (EH-partial)', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Boulemane', modernCountry:'Morocco', iso3:'MAR', state:'Fès-Meknès', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Béni Mellal', modernCountry:'Morocco', iso3:'MAR', state:'Béni Mellal-Khénifra', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Casablanca', modernCountry:'Morocco', iso3:'MAR', state:'Casablanca-Settat', historicalContext:'Prefecture of Morocco.'),
  Place(continent:'Africa', name:'Chefchaouen', modernCountry:'Morocco', iso3:'MAR', state:'Tanger-Tétouan-Al Hoceïma', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Chichaoua', modernCountry:'Morocco', iso3:'MAR', state:'Marrakech-Safi', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Chtouka-Ait Baha', modernCountry:'Morocco', iso3:'MAR', state:'Casablanca-Settat', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Driouch', modernCountry:'Morocco', iso3:'MAR', state:'L\'Oriental', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'El Hajeb', modernCountry:'Morocco', iso3:'MAR', state:'Fès-Meknès', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'El Jadida', modernCountry:'Morocco', iso3:'MAR', state:'Casablanca-Settat', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'El Kelâa des Sraghna', modernCountry:'Morocco', iso3:'MAR', state:'Marrakech-Safi', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Errachidia', modernCountry:'Morocco', iso3:'MAR', state:'Drâa-Tafilalet', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Es-Semara (EH-partial)', modernCountry:'Morocco', iso3:'MAR', state:'Laâyoune-Sakia El Hamra (EH-partial)', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Essaouira', modernCountry:'Morocco', iso3:'MAR', state:'Marrakech-Safi', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Fahs-Anjra', modernCountry:'Morocco', iso3:'MAR', state:'Tanger-Tétouan-Al Hoceïma', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Figuig', modernCountry:'Morocco', iso3:'MAR', state:'L\'Oriental', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Fquih Ben Salah', modernCountry:'Morocco', iso3:'MAR', state:'Béni Mellal-Khénifra', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Fès', modernCountry:'Morocco', iso3:'MAR', state:'Fès-Meknès', historicalContext:'Prefecture of Morocco.'),
  Place(continent:'Africa', name:'Guelmim', modernCountry:'Morocco', iso3:'MAR', state:'Guelmim-Oued Noun (EH-partial)', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Guercif', modernCountry:'Morocco', iso3:'MAR', state:'L\'Oriental', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Ifrane', modernCountry:'Morocco', iso3:'MAR', state:'Fès-Meknès', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Inezgane-Ait Melloul', modernCountry:'Morocco', iso3:'MAR', state:'Souss-Massa', historicalContext:'Prefecture of Morocco.'),
  Place(continent:'Africa', name:'Jerada', modernCountry:'Morocco', iso3:'MAR', state:'L\'Oriental', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Khouribga', modernCountry:'Morocco', iso3:'MAR', state:'Béni Mellal-Khénifra', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Khémisset', modernCountry:'Morocco', iso3:'MAR', state:'Rabat-Salé-Kénitra', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Khénifra', modernCountry:'Morocco', iso3:'MAR', state:'Béni Mellal-Khénifra', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Kénitra', modernCountry:'Morocco', iso3:'MAR', state:'Rabat-Salé-Kénitra', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Larache', modernCountry:'Morocco', iso3:'MAR', state:'Tanger-Tétouan-Al Hoceïma', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Laâyoune (EH)', modernCountry:'Morocco', iso3:'MAR', state:'Laâyoune-Sakia El Hamra (EH-partial)', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Marrakech', modernCountry:'Morocco', iso3:'MAR', state:'Marrakech-Safi', historicalContext:'Prefecture of Morocco.'),
  Place(continent:'Africa', name:'Meknès', modernCountry:'Morocco', iso3:'MAR', state:'Fès-Meknès', historicalContext:'Prefecture of Morocco.'),
  Place(continent:'Africa', name:'Midelt', modernCountry:'Morocco', iso3:'MAR', state:'Drâa-Tafilalet', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Mohammadia', modernCountry:'Morocco', iso3:'MAR', state:'Casablanca-Settat', historicalContext:'Prefecture of Morocco.'),
  Place(continent:'Africa', name:'Moulay Yacoub', modernCountry:'Morocco', iso3:'MAR', state:'Fès-Meknès', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Médiouna', modernCountry:'Morocco', iso3:'MAR', state:'Casablanca-Settat', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'M’diq-Fnideq', modernCountry:'Morocco', iso3:'MAR', state:'Tanger-Tétouan-Al Hoceïma', historicalContext:'Prefecture of Morocco.'),
  Place(continent:'Africa', name:'Nador', modernCountry:'Morocco', iso3:'MAR', state:'L\'Oriental', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Nouaceur', modernCountry:'Morocco', iso3:'MAR', state:'Rabat-Salé-Kénitra', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Ouarzazate', modernCountry:'Morocco', iso3:'MAR', state:'Drâa-Tafilalet', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Oued Ed-Dahab (EH)', modernCountry:'Morocco', iso3:'MAR', state:'Dakhla-Oued Ed-Dahab (EH)', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Ouezzane', modernCountry:'Morocco', iso3:'MAR', state:'Tanger-Tétouan-Al Hoceïma', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Oujda-Angad', modernCountry:'Morocco', iso3:'MAR', state:'L\'Oriental', historicalContext:'Prefecture of Morocco.'),
  Place(continent:'Africa', name:'Rabat', modernCountry:'Morocco', iso3:'MAR', state:'Rabat-Salé-Kénitra', historicalContext:'Prefecture of Morocco.'),
  Place(continent:'Africa', name:'Rehamna', modernCountry:'Morocco', iso3:'MAR', state:'Marrakech-Safi', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Safi', modernCountry:'Morocco', iso3:'MAR', state:'Marrakech-Safi', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Salé', modernCountry:'Morocco', iso3:'MAR', state:'Rabat-Salé-Kénitra', historicalContext:'Prefecture of Morocco.'),
  Place(continent:'Africa', name:'Sefrou', modernCountry:'Morocco', iso3:'MAR', state:'Fès-Meknès', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Settat', modernCountry:'Morocco', iso3:'MAR', state:'Casablanca-Settat', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Sidi Bennour', modernCountry:'Morocco', iso3:'MAR', state:'Casablanca-Settat', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Sidi Ifni', modernCountry:'Morocco', iso3:'MAR', state:'Guelmim-Oued Noun (EH-partial)', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Sidi Kacem', modernCountry:'Morocco', iso3:'MAR', state:'Rabat-Salé-Kénitra', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Sidi Slimane', modernCountry:'Morocco', iso3:'MAR', state:'Rabat-Salé-Kénitra', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Skhirate-Témara', modernCountry:'Morocco', iso3:'MAR', state:'Rabat-Salé-Kénitra', historicalContext:'Prefecture of Morocco.'),
  Place(continent:'Africa', name:'Tan-Tan (EH-partial)', modernCountry:'Morocco', iso3:'MAR', state:'Guelmim-Oued Noun (EH-partial)', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Tanger-Assilah', modernCountry:'Morocco', iso3:'MAR', state:'Tanger-Tétouan-Al Hoceïma', historicalContext:'Prefecture of Morocco.'),
  Place(continent:'Africa', name:'Taounate', modernCountry:'Morocco', iso3:'MAR', state:'Fès-Meknès', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Taourirt', modernCountry:'Morocco', iso3:'MAR', state:'L\'Oriental', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Tarfaya (EH-partial)', modernCountry:'Morocco', iso3:'MAR', state:'Laâyoune-Sakia El Hamra (EH-partial)', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Taroudannt', modernCountry:'Morocco', iso3:'MAR', state:'Souss-Massa', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Tata', modernCountry:'Morocco', iso3:'MAR', state:'Souss-Massa', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Taza', modernCountry:'Morocco', iso3:'MAR', state:'Fès-Meknès', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Tinghir', modernCountry:'Morocco', iso3:'MAR', state:'Drâa-Tafilalet', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Tiznit', modernCountry:'Morocco', iso3:'MAR', state:'Souss-Massa', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Tétouan', modernCountry:'Morocco', iso3:'MAR', state:'Tanger-Tétouan-Al Hoceïma', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Youssoufia', modernCountry:'Morocco', iso3:'MAR', state:'Marrakech-Safi', historicalContext:'Province of Morocco.'),
  Place(continent:'Africa', name:'Zagora', modernCountry:'Morocco', iso3:'MAR', state:'Drâa-Tafilalet', historicalContext:'Province of Morocco.'),

  // ── Malawi ──────────────────────────────────────────────
  Place(continent:'Africa', name:'Balaka', modernCountry:'Malawi', iso3:'MWI', state:'Southern Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Blantyre', modernCountry:'Malawi', iso3:'MWI', state:'Southern Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Chikwawa', modernCountry:'Malawi', iso3:'MWI', state:'Southern Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Chiradzulu', modernCountry:'Malawi', iso3:'MWI', state:'Southern Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Chitipa', modernCountry:'Malawi', iso3:'MWI', state:'Northern Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Dedza', modernCountry:'Malawi', iso3:'MWI', state:'Central Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Dowa', modernCountry:'Malawi', iso3:'MWI', state:'Central Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Karonga', modernCountry:'Malawi', iso3:'MWI', state:'Northern Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Kasungu', modernCountry:'Malawi', iso3:'MWI', state:'Central Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Likoma', modernCountry:'Malawi', iso3:'MWI', state:'Northern Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Lilongwe', modernCountry:'Malawi', iso3:'MWI', state:'Central Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Machinga', modernCountry:'Malawi', iso3:'MWI', state:'Southern Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Mangochi', modernCountry:'Malawi', iso3:'MWI', state:'Southern Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Mchinji', modernCountry:'Malawi', iso3:'MWI', state:'Central Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Mulanje', modernCountry:'Malawi', iso3:'MWI', state:'Southern Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Mwanza', modernCountry:'Malawi', iso3:'MWI', state:'Southern Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Mzimba', modernCountry:'Malawi', iso3:'MWI', state:'Northern Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Neno', modernCountry:'Malawi', iso3:'MWI', state:'Southern Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Nkhata Bay', modernCountry:'Malawi', iso3:'MWI', state:'Northern Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Nkhotakota', modernCountry:'Malawi', iso3:'MWI', state:'Central Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Nsanje', modernCountry:'Malawi', iso3:'MWI', state:'Southern Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Ntcheu', modernCountry:'Malawi', iso3:'MWI', state:'Central Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Ntchisi', modernCountry:'Malawi', iso3:'MWI', state:'Central Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Phalombe', modernCountry:'Malawi', iso3:'MWI', state:'Southern Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Rumphi', modernCountry:'Malawi', iso3:'MWI', state:'Northern Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Salima', modernCountry:'Malawi', iso3:'MWI', state:'Central Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Thyolo', modernCountry:'Malawi', iso3:'MWI', state:'Southern Region', historicalContext:'District of Malawi.'),
  Place(continent:'Africa', name:'Zomba', modernCountry:'Malawi', iso3:'MWI', state:'Southern Region', historicalContext:'District of Malawi.'),

  // ── Uganda ──────────────────────────────────────────────
  Place(continent:'Africa', name:'Abim', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Adjumani', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Agago', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Alebtong', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Amolatar', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Amudat', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Amuria', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Amuru', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Apac', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Arua', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Budaka', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Bududa', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Bugiri', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Bugweri', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Buhweju', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Buikwe', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Bukedea', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Bukomansibi', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Bukwo', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Bulambuli', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Buliisa', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Bundibugyo', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Bunyangabu', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Bushenyi', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Busia', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Butaleja', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Butambala', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Butebo', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Buvuma', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Buyende', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Dokolo', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Gomba', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Gulu', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Hoima', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Ibanda', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Iganga', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Isingiro', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Jinja', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kaabong', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kabale', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kabarole', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kaberamaido', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kagadi', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kakumiro', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kalaki', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kalangala', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kaliro', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kalungu', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kampala', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'City of Uganda.'),
  Place(continent:'Africa', name:'Kamuli', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kamwenge', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kanungu', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kapchorwa', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kapelebyong', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Karenga', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kasanda', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kasese', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Katakwi', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kayunga', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kazo', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kibaale', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kiboga', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kibuku', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kikuube', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kiruhura', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kiryandongo', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kisoro', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kitagwenda', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kitgum', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Koboko', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kole', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kotido', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kumi', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kwania', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kween', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kyankwanzi', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kyegegwa', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kyenjojo', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Kyotera', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Lamwo', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Lira', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Luuka', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Luwero', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Lwengo', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Lyantonde', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Madi-Okollo', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Manafwa', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Maracha', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Masaka', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Masindi', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Mayuge', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Mbale', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Mbarara', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Mitooma', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Mityana', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Moroto', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Moyo', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Mpigi', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Mubende', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Mukono', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Nabilatuk', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Nakapiripirit', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Nakaseke', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Nakasongola', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Namayingo', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Namisindwa', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Namutumba', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Napak', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Nebbi', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Ngora', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Ntoroko', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Ntungamo', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Nwoya', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Obongi', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Omoro', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Otuke', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Oyam', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Pader', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Pakwach', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Pallisa', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Rakai', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Rubanda', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Rubirizi', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Rukiga', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Rukungiri', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Rwampara', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Sembabule', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Serere', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Sheema', modernCountry:'Uganda', iso3:'UGA', state:'Western', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Sironko', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Soroti', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Tororo', modernCountry:'Uganda', iso3:'UGA', state:'Eastern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Wakiso', modernCountry:'Uganda', iso3:'UGA', state:'Central', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Yumbe', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
  Place(continent:'Africa', name:'Zombo', modernCountry:'Uganda', iso3:'UGA', state:'Northern', historicalContext:'District of Uganda.'),
];
