import '../models/place.dart';

/// Americas: all level-1 administrative subdivisions (states, provinces, regions, etc.).
const List<Place> placesSubdivisionsAmericas = [
  // ── Bonaire, Sint Eustatius and Saba ────────────────────────────
  Place(continent:'Americas', name:'Bonaire', modernCountry:'Bonaire, Sint Eustatius and Saba', iso3:'BES', state:'Bonaire', historicalContext:'Special municipality of Bonaire, Sint Eustatius and Saba (Netherlands).'),
  Place(continent:'Americas', name:'Saba', modernCountry:'Bonaire, Sint Eustatius and Saba', iso3:'BES', state:'Saba', historicalContext:'Special municipality of Bonaire, Sint Eustatius and Saba (Netherlands).'),
  Place(continent:'Americas', name:'Sint Eustatius', modernCountry:'Bonaire, Sint Eustatius and Saba', iso3:'BES', state:'Sint Eustatius', historicalContext:'Special municipality of Bonaire, Sint Eustatius and Saba (Netherlands).'),

  // ── Antigua and Barbuda ─────────────────────────────────────────
  Place(continent:'Americas', name:'Barbuda', modernCountry:'Antigua and Barbuda', iso3:'ATG', state:'Barbuda', historicalContext:'Dependency of Antigua and Barbuda.'),
  Place(continent:'Americas', name:'Redonda', modernCountry:'Antigua and Barbuda', iso3:'ATG', state:'Redonda', historicalContext:'Dependency of Antigua and Barbuda.'),
  Place(continent:'Americas', name:'Saint George', modernCountry:'Antigua and Barbuda', iso3:'ATG', state:'Saint George', historicalContext:'Parish of Antigua and Barbuda.'),
  Place(continent:'Americas', name:'Saint John', modernCountry:'Antigua and Barbuda', iso3:'ATG', state:'Saint John', historicalContext:'Parish of Antigua and Barbuda.'),
  Place(continent:'Americas', name:'Saint Mary', modernCountry:'Antigua and Barbuda', iso3:'ATG', state:'Saint Mary', historicalContext:'Parish of Antigua and Barbuda.'),
  Place(continent:'Americas', name:'Saint Paul', modernCountry:'Antigua and Barbuda', iso3:'ATG', state:'Saint Paul', historicalContext:'Parish of Antigua and Barbuda.'),
  Place(continent:'Americas', name:'Saint Peter', modernCountry:'Antigua and Barbuda', iso3:'ATG', state:'Saint Peter', historicalContext:'Parish of Antigua and Barbuda.'),
  Place(continent:'Americas', name:'Saint Philip', modernCountry:'Antigua and Barbuda', iso3:'ATG', state:'Saint Philip', historicalContext:'Parish of Antigua and Barbuda.'),

  // ── Argentina ───────────────────────────────────────────────────
  Place(continent:'Americas', name:'Buenos Aires', modernCountry:'Argentina', iso3:'ARG', state:'Buenos Aires', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'Catamarca', modernCountry:'Argentina', iso3:'ARG', state:'Catamarca', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'Chaco', modernCountry:'Argentina', iso3:'ARG', state:'Chaco', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'Chubut', modernCountry:'Argentina', iso3:'ARG', state:'Chubut', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'Ciudad Autónoma de Buenos Aires', modernCountry:'Argentina', iso3:'ARG', state:'Ciudad Autónoma de Buenos Aires', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'Corrientes', modernCountry:'Argentina', iso3:'ARG', state:'Corrientes', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'Córdoba', modernCountry:'Argentina', iso3:'ARG', state:'Córdoba', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'Entre Ríos', modernCountry:'Argentina', iso3:'ARG', state:'Entre Ríos', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'Formosa', modernCountry:'Argentina', iso3:'ARG', state:'Formosa', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'Jujuy', modernCountry:'Argentina', iso3:'ARG', state:'Jujuy', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'La Pampa', modernCountry:'Argentina', iso3:'ARG', state:'La Pampa', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'La Rioja', modernCountry:'Argentina', iso3:'ARG', state:'La Rioja', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'Mendoza', modernCountry:'Argentina', iso3:'ARG', state:'Mendoza', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'Misiones', modernCountry:'Argentina', iso3:'ARG', state:'Misiones', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'Neuquén', modernCountry:'Argentina', iso3:'ARG', state:'Neuquén', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'Río Negro', modernCountry:'Argentina', iso3:'ARG', state:'Río Negro', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'Salta', modernCountry:'Argentina', iso3:'ARG', state:'Salta', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'San Juan', modernCountry:'Argentina', iso3:'ARG', state:'San Juan', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'San Luis', modernCountry:'Argentina', iso3:'ARG', state:'San Luis', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'Santa Cruz', modernCountry:'Argentina', iso3:'ARG', state:'Santa Cruz', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'Santa Fe', modernCountry:'Argentina', iso3:'ARG', state:'Santa Fe', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'Santiago del Estero', modernCountry:'Argentina', iso3:'ARG', state:'Santiago del Estero', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'Tierra del Fuego', modernCountry:'Argentina', iso3:'ARG', state:'Tierra del Fuego', historicalContext:'Province or autonomous city of Argentina.'),
  Place(continent:'Americas', name:'Tucumán', modernCountry:'Argentina', iso3:'ARG', state:'Tucumán', historicalContext:'Province or autonomous city of Argentina.'),

  // ── Bahamas ─────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Acklins', modernCountry:'Bahamas', iso3:'BHS', state:'Acklins', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Berry Islands', modernCountry:'Bahamas', iso3:'BHS', state:'Berry Islands', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Bimini', modernCountry:'Bahamas', iso3:'BHS', state:'Bimini', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Black Point', modernCountry:'Bahamas', iso3:'BHS', state:'Black Point', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Cat Island', modernCountry:'Bahamas', iso3:'BHS', state:'Cat Island', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Central Abaco', modernCountry:'Bahamas', iso3:'BHS', state:'Central Abaco', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Central Andros', modernCountry:'Bahamas', iso3:'BHS', state:'Central Andros', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Central Eleuthera', modernCountry:'Bahamas', iso3:'BHS', state:'Central Eleuthera', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'City of Freeport', modernCountry:'Bahamas', iso3:'BHS', state:'City of Freeport', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Crooked Island and Long Cay', modernCountry:'Bahamas', iso3:'BHS', state:'Crooked Island and Long Cay', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'East Grand Bahama', modernCountry:'Bahamas', iso3:'BHS', state:'East Grand Bahama', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Exuma', modernCountry:'Bahamas', iso3:'BHS', state:'Exuma', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Grand Cay', modernCountry:'Bahamas', iso3:'BHS', state:'Grand Cay', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Harbour Island', modernCountry:'Bahamas', iso3:'BHS', state:'Harbour Island', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Hope Town', modernCountry:'Bahamas', iso3:'BHS', state:'Hope Town', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Inagua', modernCountry:'Bahamas', iso3:'BHS', state:'Inagua', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Long Island', modernCountry:'Bahamas', iso3:'BHS', state:'Long Island', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Mangrove Cay', modernCountry:'Bahamas', iso3:'BHS', state:'Mangrove Cay', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Mayaguana', modernCountry:'Bahamas', iso3:'BHS', state:'Mayaguana', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Moore\'s Island', modernCountry:'Bahamas', iso3:'BHS', state:'Moore\'s Island', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'New Providence', modernCountry:'Bahamas', iso3:'BHS', state:'New Providence', historicalContext:'Island of Bahamas.'),
  Place(continent:'Americas', name:'North Abaco', modernCountry:'Bahamas', iso3:'BHS', state:'North Abaco', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'North Andros', modernCountry:'Bahamas', iso3:'BHS', state:'North Andros', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'North Eleuthera', modernCountry:'Bahamas', iso3:'BHS', state:'North Eleuthera', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Ragged Island', modernCountry:'Bahamas', iso3:'BHS', state:'Ragged Island', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Rum Cay', modernCountry:'Bahamas', iso3:'BHS', state:'Rum Cay', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'San Salvador', modernCountry:'Bahamas', iso3:'BHS', state:'San Salvador', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'South Abaco', modernCountry:'Bahamas', iso3:'BHS', state:'South Abaco', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'South Andros', modernCountry:'Bahamas', iso3:'BHS', state:'South Andros', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'South Eleuthera', modernCountry:'Bahamas', iso3:'BHS', state:'South Eleuthera', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'Spanish Wells', modernCountry:'Bahamas', iso3:'BHS', state:'Spanish Wells', historicalContext:'District of Bahamas.'),
  Place(continent:'Americas', name:'West Grand Bahama', modernCountry:'Bahamas', iso3:'BHS', state:'West Grand Bahama', historicalContext:'District of Bahamas.'),

  // ── Barbados ────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Christ Church', modernCountry:'Barbados', iso3:'BRB', state:'Christ Church', historicalContext:'Parish of Barbados.'),
  Place(continent:'Americas', name:'Saint Andrew', modernCountry:'Barbados', iso3:'BRB', state:'Saint Andrew', historicalContext:'Parish of Barbados.'),
  Place(continent:'Americas', name:'Saint George', modernCountry:'Barbados', iso3:'BRB', state:'Saint George', historicalContext:'Parish of Barbados.'),
  Place(continent:'Americas', name:'Saint James', modernCountry:'Barbados', iso3:'BRB', state:'Saint James', historicalContext:'Parish of Barbados.'),
  Place(continent:'Americas', name:'Saint John', modernCountry:'Barbados', iso3:'BRB', state:'Saint John', historicalContext:'Parish of Barbados.'),
  Place(continent:'Americas', name:'Saint Joseph', modernCountry:'Barbados', iso3:'BRB', state:'Saint Joseph', historicalContext:'Parish of Barbados.'),
  Place(continent:'Americas', name:'Saint Lucy', modernCountry:'Barbados', iso3:'BRB', state:'Saint Lucy', historicalContext:'Parish of Barbados.'),
  Place(continent:'Americas', name:'Saint Michael', modernCountry:'Barbados', iso3:'BRB', state:'Saint Michael', historicalContext:'Parish of Barbados.'),
  Place(continent:'Americas', name:'Saint Peter', modernCountry:'Barbados', iso3:'BRB', state:'Saint Peter', historicalContext:'Parish of Barbados.'),
  Place(continent:'Americas', name:'Saint Philip', modernCountry:'Barbados', iso3:'BRB', state:'Saint Philip', historicalContext:'Parish of Barbados.'),
  Place(continent:'Americas', name:'Saint Thomas', modernCountry:'Barbados', iso3:'BRB', state:'Saint Thomas', historicalContext:'Parish of Barbados.'),

  // ── Belize ──────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Belize', modernCountry:'Belize', iso3:'BLZ', state:'Belize', historicalContext:'District of Belize.'),
  Place(continent:'Americas', name:'Cayo', modernCountry:'Belize', iso3:'BLZ', state:'Cayo', historicalContext:'District of Belize.'),
  Place(continent:'Americas', name:'Corozal', modernCountry:'Belize', iso3:'BLZ', state:'Corozal', historicalContext:'District of Belize.'),
  Place(continent:'Americas', name:'Orange Walk', modernCountry:'Belize', iso3:'BLZ', state:'Orange Walk', historicalContext:'District of Belize.'),
  Place(continent:'Americas', name:'Stann Creek', modernCountry:'Belize', iso3:'BLZ', state:'Stann Creek', historicalContext:'District of Belize.'),
  Place(continent:'Americas', name:'Toledo', modernCountry:'Belize', iso3:'BLZ', state:'Toledo', historicalContext:'District of Belize.'),

  // ── Bolivia, Plurinational State of ─────────────────────────────
  Place(continent:'Americas', name:'Chuquisaca', modernCountry:'Bolivia, Plurinational State of', iso3:'BOL', state:'Chuquisaca', historicalContext:'Department of Bolivia, Plurinational State of.'),
  Place(continent:'Americas', name:'Cochabamba', modernCountry:'Bolivia, Plurinational State of', iso3:'BOL', state:'Cochabamba', historicalContext:'Department of Bolivia, Plurinational State of.'),
  Place(continent:'Americas', name:'El Beni', modernCountry:'Bolivia, Plurinational State of', iso3:'BOL', state:'El Beni', historicalContext:'Department of Bolivia, Plurinational State of.'),
  Place(continent:'Americas', name:'La Paz', modernCountry:'Bolivia, Plurinational State of', iso3:'BOL', state:'La Paz', historicalContext:'Department of Bolivia, Plurinational State of.'),
  Place(continent:'Americas', name:'Oruro', modernCountry:'Bolivia, Plurinational State of', iso3:'BOL', state:'Oruro', historicalContext:'Department of Bolivia, Plurinational State of.'),
  Place(continent:'Americas', name:'Pando', modernCountry:'Bolivia, Plurinational State of', iso3:'BOL', state:'Pando', historicalContext:'Department of Bolivia, Plurinational State of.'),
  Place(continent:'Americas', name:'Potosí', modernCountry:'Bolivia, Plurinational State of', iso3:'BOL', state:'Potosí', historicalContext:'Department of Bolivia, Plurinational State of.'),
  Place(continent:'Americas', name:'Santa Cruz', modernCountry:'Bolivia, Plurinational State of', iso3:'BOL', state:'Santa Cruz', historicalContext:'Department of Bolivia, Plurinational State of.'),
  Place(continent:'Americas', name:'Tarija', modernCountry:'Bolivia, Plurinational State of', iso3:'BOL', state:'Tarija', historicalContext:'Department of Bolivia, Plurinational State of.'),

  // ── Brazil ──────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Acre', modernCountry:'Brazil', iso3:'BRA', state:'Acre', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Alagoas', modernCountry:'Brazil', iso3:'BRA', state:'Alagoas', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Amapá', modernCountry:'Brazil', iso3:'BRA', state:'Amapá', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Amazonas', modernCountry:'Brazil', iso3:'BRA', state:'Amazonas', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Bahia', modernCountry:'Brazil', iso3:'BRA', state:'Bahia', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Ceará', modernCountry:'Brazil', iso3:'BRA', state:'Ceará', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Distrito Federal', modernCountry:'Brazil', iso3:'BRA', state:'Distrito Federal', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Espírito Santo', modernCountry:'Brazil', iso3:'BRA', state:'Espírito Santo', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Goiás', modernCountry:'Brazil', iso3:'BRA', state:'Goiás', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Maranhão', modernCountry:'Brazil', iso3:'BRA', state:'Maranhão', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Mato Grosso', modernCountry:'Brazil', iso3:'BRA', state:'Mato Grosso', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Mato Grosso do Sul', modernCountry:'Brazil', iso3:'BRA', state:'Mato Grosso do Sul', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Minas Gerais', modernCountry:'Brazil', iso3:'BRA', state:'Minas Gerais', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Paraná', modernCountry:'Brazil', iso3:'BRA', state:'Paraná', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Paraíba', modernCountry:'Brazil', iso3:'BRA', state:'Paraíba', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Pará', modernCountry:'Brazil', iso3:'BRA', state:'Pará', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Pernambuco', modernCountry:'Brazil', iso3:'BRA', state:'Pernambuco', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Piauí', modernCountry:'Brazil', iso3:'BRA', state:'Piauí', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Rio Grande do Norte', modernCountry:'Brazil', iso3:'BRA', state:'Rio Grande do Norte', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Rio Grande do Sul', modernCountry:'Brazil', iso3:'BRA', state:'Rio Grande do Sul', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Rio de Janeiro', modernCountry:'Brazil', iso3:'BRA', state:'Rio de Janeiro', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Rondônia', modernCountry:'Brazil', iso3:'BRA', state:'Rondônia', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Roraima', modernCountry:'Brazil', iso3:'BRA', state:'Roraima', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Santa Catarina', modernCountry:'Brazil', iso3:'BRA', state:'Santa Catarina', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Sergipe', modernCountry:'Brazil', iso3:'BRA', state:'Sergipe', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'São Paulo', modernCountry:'Brazil', iso3:'BRA', state:'São Paulo', historicalContext:'State or federal district of Brazil.'),
  Place(continent:'Americas', name:'Tocantins', modernCountry:'Brazil', iso3:'BRA', state:'Tocantins', historicalContext:'State or federal district of Brazil.'),

  // ── Canada ──────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Alberta', modernCountry:'Canada', iso3:'CAN', state:'Alberta', historicalContext:'Province or territory of Canada.'),
  Place(continent:'Americas', name:'British Columbia', modernCountry:'Canada', iso3:'CAN', state:'British Columbia', historicalContext:'Province or territory of Canada.'),
  Place(continent:'Americas', name:'Manitoba', modernCountry:'Canada', iso3:'CAN', state:'Manitoba', historicalContext:'Province or territory of Canada.'),
  Place(continent:'Americas', name:'New Brunswick', modernCountry:'Canada', iso3:'CAN', state:'New Brunswick', historicalContext:'Province or territory of Canada.'),
  Place(continent:'Americas', name:'Newfoundland and Labrador', modernCountry:'Canada', iso3:'CAN', state:'Newfoundland and Labrador', historicalContext:'Province or territory of Canada.'),
  Place(continent:'Americas', name:'Northwest Territories', modernCountry:'Canada', iso3:'CAN', state:'Northwest Territories', historicalContext:'Province or territory of Canada.'),
  Place(continent:'Americas', name:'Nova Scotia', modernCountry:'Canada', iso3:'CAN', state:'Nova Scotia', historicalContext:'Province or territory of Canada.'),
  Place(continent:'Americas', name:'Nunavut', modernCountry:'Canada', iso3:'CAN', state:'Nunavut', historicalContext:'Province or territory of Canada.'),
  Place(continent:'Americas', name:'Ontario', modernCountry:'Canada', iso3:'CAN', state:'Ontario', historicalContext:'Province or territory of Canada.'),
  Place(continent:'Americas', name:'Prince Edward Island', modernCountry:'Canada', iso3:'CAN', state:'Prince Edward Island', historicalContext:'Province or territory of Canada.'),
  Place(continent:'Americas', name:'Quebec', modernCountry:'Canada', iso3:'CAN', state:'Quebec', historicalContext:'Province or territory of Canada.'),
  Place(continent:'Americas', name:'Saskatchewan', modernCountry:'Canada', iso3:'CAN', state:'Saskatchewan', historicalContext:'Province or territory of Canada.'),
  Place(continent:'Americas', name:'Yukon', modernCountry:'Canada', iso3:'CAN', state:'Yukon', historicalContext:'Province or territory of Canada.'),

  // ── Chile ───────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Aisén del General Carlos Ibañez del Campo', modernCountry:'Chile', iso3:'CHL', state:'Aisén del General Carlos Ibañez del Campo', historicalContext:'Region of Chile.'),
  Place(continent:'Americas', name:'Antofagasta', modernCountry:'Chile', iso3:'CHL', state:'Antofagasta', historicalContext:'Region of Chile.'),
  Place(continent:'Americas', name:'Arica y Parinacota', modernCountry:'Chile', iso3:'CHL', state:'Arica y Parinacota', historicalContext:'Region of Chile.'),
  Place(continent:'Americas', name:'Atacama', modernCountry:'Chile', iso3:'CHL', state:'Atacama', historicalContext:'Region of Chile.'),
  Place(continent:'Americas', name:'Biobío', modernCountry:'Chile', iso3:'CHL', state:'Biobío', historicalContext:'Region of Chile.'),
  Place(continent:'Americas', name:'Coquimbo', modernCountry:'Chile', iso3:'CHL', state:'Coquimbo', historicalContext:'Region of Chile.'),
  Place(continent:'Americas', name:'La Araucanía', modernCountry:'Chile', iso3:'CHL', state:'La Araucanía', historicalContext:'Region of Chile.'),
  Place(continent:'Americas', name:'Libertador General Bernardo O\'Higgins', modernCountry:'Chile', iso3:'CHL', state:'Libertador General Bernardo O\'Higgins', historicalContext:'Region of Chile.'),
  Place(continent:'Americas', name:'Los Lagos', modernCountry:'Chile', iso3:'CHL', state:'Los Lagos', historicalContext:'Region of Chile.'),
  Place(continent:'Americas', name:'Los Ríos', modernCountry:'Chile', iso3:'CHL', state:'Los Ríos', historicalContext:'Region of Chile.'),
  Place(continent:'Americas', name:'Magallanes', modernCountry:'Chile', iso3:'CHL', state:'Magallanes', historicalContext:'Region of Chile.'),
  Place(continent:'Americas', name:'Maule', modernCountry:'Chile', iso3:'CHL', state:'Maule', historicalContext:'Region of Chile.'),
  Place(continent:'Americas', name:'Región Metropolitana de Santiago', modernCountry:'Chile', iso3:'CHL', state:'Región Metropolitana de Santiago', historicalContext:'Region of Chile.'),
  Place(continent:'Americas', name:'Tarapacá', modernCountry:'Chile', iso3:'CHL', state:'Tarapacá', historicalContext:'Region of Chile.'),
  Place(continent:'Americas', name:'Valparaíso', modernCountry:'Chile', iso3:'CHL', state:'Valparaíso', historicalContext:'Region of Chile.'),
  Place(continent:'Americas', name:'Ñuble', modernCountry:'Chile', iso3:'CHL', state:'Ñuble', historicalContext:'Region of Chile.'),

  // ── Colombia ────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Amazonas', modernCountry:'Colombia', iso3:'COL', state:'Amazonas', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Antioquia', modernCountry:'Colombia', iso3:'COL', state:'Antioquia', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Arauca', modernCountry:'Colombia', iso3:'COL', state:'Arauca', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Atlántico', modernCountry:'Colombia', iso3:'COL', state:'Atlántico', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Bolívar', modernCountry:'Colombia', iso3:'COL', state:'Bolívar', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Boyacá', modernCountry:'Colombia', iso3:'COL', state:'Boyacá', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Caldas', modernCountry:'Colombia', iso3:'COL', state:'Caldas', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Caquetá', modernCountry:'Colombia', iso3:'COL', state:'Caquetá', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Casanare', modernCountry:'Colombia', iso3:'COL', state:'Casanare', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Cauca', modernCountry:'Colombia', iso3:'COL', state:'Cauca', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Cesar', modernCountry:'Colombia', iso3:'COL', state:'Cesar', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Chocó', modernCountry:'Colombia', iso3:'COL', state:'Chocó', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Cundinamarca', modernCountry:'Colombia', iso3:'COL', state:'Cundinamarca', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Córdoba', modernCountry:'Colombia', iso3:'COL', state:'Córdoba', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Distrito Capital de Bogotá', modernCountry:'Colombia', iso3:'COL', state:'Distrito Capital de Bogotá', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Guainía', modernCountry:'Colombia', iso3:'COL', state:'Guainía', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Guaviare', modernCountry:'Colombia', iso3:'COL', state:'Guaviare', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Huila', modernCountry:'Colombia', iso3:'COL', state:'Huila', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'La Guajira', modernCountry:'Colombia', iso3:'COL', state:'La Guajira', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Magdalena', modernCountry:'Colombia', iso3:'COL', state:'Magdalena', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Meta', modernCountry:'Colombia', iso3:'COL', state:'Meta', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Nariño', modernCountry:'Colombia', iso3:'COL', state:'Nariño', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Norte de Santander', modernCountry:'Colombia', iso3:'COL', state:'Norte de Santander', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Putumayo', modernCountry:'Colombia', iso3:'COL', state:'Putumayo', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Quindío', modernCountry:'Colombia', iso3:'COL', state:'Quindío', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Risaralda', modernCountry:'Colombia', iso3:'COL', state:'Risaralda', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'San Andrés, Providencia y Santa Catalina', modernCountry:'Colombia', iso3:'COL', state:'San Andrés, Providencia y Santa Catalina', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Santander', modernCountry:'Colombia', iso3:'COL', state:'Santander', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Sucre', modernCountry:'Colombia', iso3:'COL', state:'Sucre', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Tolima', modernCountry:'Colombia', iso3:'COL', state:'Tolima', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Valle del Cauca', modernCountry:'Colombia', iso3:'COL', state:'Valle del Cauca', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Vaupés', modernCountry:'Colombia', iso3:'COL', state:'Vaupés', historicalContext:'Department of Colombia.'),
  Place(continent:'Americas', name:'Vichada', modernCountry:'Colombia', iso3:'COL', state:'Vichada', historicalContext:'Department of Colombia.'),

  // ── Costa Rica ──────────────────────────────────────────────────
  Place(continent:'Americas', name:'Alajuela', modernCountry:'Costa Rica', iso3:'CRI', state:'Alajuela', historicalContext:'Province of Costa Rica.'),
  Place(continent:'Americas', name:'Cartago', modernCountry:'Costa Rica', iso3:'CRI', state:'Cartago', historicalContext:'Province of Costa Rica.'),
  Place(continent:'Americas', name:'Guanacaste', modernCountry:'Costa Rica', iso3:'CRI', state:'Guanacaste', historicalContext:'Province of Costa Rica.'),
  Place(continent:'Americas', name:'Heredia', modernCountry:'Costa Rica', iso3:'CRI', state:'Heredia', historicalContext:'Province of Costa Rica.'),
  Place(continent:'Americas', name:'Limón', modernCountry:'Costa Rica', iso3:'CRI', state:'Limón', historicalContext:'Province of Costa Rica.'),
  Place(continent:'Americas', name:'Puntarenas', modernCountry:'Costa Rica', iso3:'CRI', state:'Puntarenas', historicalContext:'Province of Costa Rica.'),
  Place(continent:'Americas', name:'San José', modernCountry:'Costa Rica', iso3:'CRI', state:'San José', historicalContext:'Province of Costa Rica.'),

  // ── Cuba ────────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Artemisa', modernCountry:'Cuba', iso3:'CUB', state:'Artemisa', historicalContext:'Province of Cuba.'),
  Place(continent:'Americas', name:'Camagüey', modernCountry:'Cuba', iso3:'CUB', state:'Camagüey', historicalContext:'Province of Cuba.'),
  Place(continent:'Americas', name:'Ciego de Ávila', modernCountry:'Cuba', iso3:'CUB', state:'Ciego de Ávila', historicalContext:'Province of Cuba.'),
  Place(continent:'Americas', name:'Cienfuegos', modernCountry:'Cuba', iso3:'CUB', state:'Cienfuegos', historicalContext:'Province of Cuba.'),
  Place(continent:'Americas', name:'Granma', modernCountry:'Cuba', iso3:'CUB', state:'Granma', historicalContext:'Province of Cuba.'),
  Place(continent:'Americas', name:'Guantánamo', modernCountry:'Cuba', iso3:'CUB', state:'Guantánamo', historicalContext:'Province of Cuba.'),
  Place(continent:'Americas', name:'Holguín', modernCountry:'Cuba', iso3:'CUB', state:'Holguín', historicalContext:'Province of Cuba.'),
  Place(continent:'Americas', name:'Isla de la Juventud', modernCountry:'Cuba', iso3:'CUB', state:'Isla de la Juventud', historicalContext:'Special municipality of Cuba.'),
  Place(continent:'Americas', name:'La Habana', modernCountry:'Cuba', iso3:'CUB', state:'La Habana', historicalContext:'Province of Cuba.'),
  Place(continent:'Americas', name:'Las Tunas', modernCountry:'Cuba', iso3:'CUB', state:'Las Tunas', historicalContext:'Province of Cuba.'),
  Place(continent:'Americas', name:'Matanzas', modernCountry:'Cuba', iso3:'CUB', state:'Matanzas', historicalContext:'Province of Cuba.'),
  Place(continent:'Americas', name:'Mayabeque', modernCountry:'Cuba', iso3:'CUB', state:'Mayabeque', historicalContext:'Province of Cuba.'),
  Place(continent:'Americas', name:'Pinar del Río', modernCountry:'Cuba', iso3:'CUB', state:'Pinar del Río', historicalContext:'Province of Cuba.'),
  Place(continent:'Americas', name:'Sancti Spíritus', modernCountry:'Cuba', iso3:'CUB', state:'Sancti Spíritus', historicalContext:'Province of Cuba.'),
  Place(continent:'Americas', name:'Santiago de Cuba', modernCountry:'Cuba', iso3:'CUB', state:'Santiago de Cuba', historicalContext:'Province of Cuba.'),
  Place(continent:'Americas', name:'Villa Clara', modernCountry:'Cuba', iso3:'CUB', state:'Villa Clara', historicalContext:'Province of Cuba.'),

  // ── Dominica ────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Saint Andrew', modernCountry:'Dominica', iso3:'DMA', state:'Saint Andrew', historicalContext:'Parish of Dominica.'),
  Place(continent:'Americas', name:'Saint David', modernCountry:'Dominica', iso3:'DMA', state:'Saint David', historicalContext:'Parish of Dominica.'),
  Place(continent:'Americas', name:'Saint George', modernCountry:'Dominica', iso3:'DMA', state:'Saint George', historicalContext:'Parish of Dominica.'),
  Place(continent:'Americas', name:'Saint John', modernCountry:'Dominica', iso3:'DMA', state:'Saint John', historicalContext:'Parish of Dominica.'),
  Place(continent:'Americas', name:'Saint Joseph', modernCountry:'Dominica', iso3:'DMA', state:'Saint Joseph', historicalContext:'Parish of Dominica.'),
  Place(continent:'Americas', name:'Saint Luke', modernCountry:'Dominica', iso3:'DMA', state:'Saint Luke', historicalContext:'Parish of Dominica.'),
  Place(continent:'Americas', name:'Saint Mark', modernCountry:'Dominica', iso3:'DMA', state:'Saint Mark', historicalContext:'Parish of Dominica.'),
  Place(continent:'Americas', name:'Saint Patrick', modernCountry:'Dominica', iso3:'DMA', state:'Saint Patrick', historicalContext:'Parish of Dominica.'),
  Place(continent:'Americas', name:'Saint Paul', modernCountry:'Dominica', iso3:'DMA', state:'Saint Paul', historicalContext:'Parish of Dominica.'),
  Place(continent:'Americas', name:'Saint Peter', modernCountry:'Dominica', iso3:'DMA', state:'Saint Peter', historicalContext:'Parish of Dominica.'),

  // ── Dominican Republic ──────────────────────────────────────────
  Place(continent:'Americas', name:'Cibao Nordeste', modernCountry:'Dominican Republic', iso3:'DOM', state:'Cibao Nordeste', historicalContext:'Region of Dominican Republic.'),
  Place(continent:'Americas', name:'Cibao Noroeste', modernCountry:'Dominican Republic', iso3:'DOM', state:'Cibao Noroeste', historicalContext:'Region of Dominican Republic.'),
  Place(continent:'Americas', name:'Cibao Norte', modernCountry:'Dominican Republic', iso3:'DOM', state:'Cibao Norte', historicalContext:'Region of Dominican Republic.'),
  Place(continent:'Americas', name:'Cibao Sur', modernCountry:'Dominican Republic', iso3:'DOM', state:'Cibao Sur', historicalContext:'Region of Dominican Republic.'),
  Place(continent:'Americas', name:'El Valle', modernCountry:'Dominican Republic', iso3:'DOM', state:'El Valle', historicalContext:'Region of Dominican Republic.'),
  Place(continent:'Americas', name:'Enriquillo', modernCountry:'Dominican Republic', iso3:'DOM', state:'Enriquillo', historicalContext:'Region of Dominican Republic.'),
  Place(continent:'Americas', name:'Higuamo', modernCountry:'Dominican Republic', iso3:'DOM', state:'Higuamo', historicalContext:'Region of Dominican Republic.'),
  Place(continent:'Americas', name:'Ozama', modernCountry:'Dominican Republic', iso3:'DOM', state:'Ozama', historicalContext:'Region of Dominican Republic.'),
  Place(continent:'Americas', name:'Valdesia', modernCountry:'Dominican Republic', iso3:'DOM', state:'Valdesia', historicalContext:'Region of Dominican Republic.'),
  Place(continent:'Americas', name:'Yuma', modernCountry:'Dominican Republic', iso3:'DOM', state:'Yuma', historicalContext:'Region of Dominican Republic.'),

  // ── Ecuador ─────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Azuay', modernCountry:'Ecuador', iso3:'ECU', state:'Azuay', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Bolívar', modernCountry:'Ecuador', iso3:'ECU', state:'Bolívar', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Carchi', modernCountry:'Ecuador', iso3:'ECU', state:'Carchi', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Cañar', modernCountry:'Ecuador', iso3:'ECU', state:'Cañar', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Chimborazo', modernCountry:'Ecuador', iso3:'ECU', state:'Chimborazo', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Cotopaxi', modernCountry:'Ecuador', iso3:'ECU', state:'Cotopaxi', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'El Oro', modernCountry:'Ecuador', iso3:'ECU', state:'El Oro', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Esmeraldas', modernCountry:'Ecuador', iso3:'ECU', state:'Esmeraldas', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Galápagos', modernCountry:'Ecuador', iso3:'ECU', state:'Galápagos', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Guayas', modernCountry:'Ecuador', iso3:'ECU', state:'Guayas', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Imbabura', modernCountry:'Ecuador', iso3:'ECU', state:'Imbabura', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Loja', modernCountry:'Ecuador', iso3:'ECU', state:'Loja', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Los Ríos', modernCountry:'Ecuador', iso3:'ECU', state:'Los Ríos', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Manabí', modernCountry:'Ecuador', iso3:'ECU', state:'Manabí', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Morona Santiago', modernCountry:'Ecuador', iso3:'ECU', state:'Morona Santiago', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Napo', modernCountry:'Ecuador', iso3:'ECU', state:'Napo', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Orellana', modernCountry:'Ecuador', iso3:'ECU', state:'Orellana', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Pastaza', modernCountry:'Ecuador', iso3:'ECU', state:'Pastaza', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Pichincha', modernCountry:'Ecuador', iso3:'ECU', state:'Pichincha', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Santa Elena', modernCountry:'Ecuador', iso3:'ECU', state:'Santa Elena', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Santo Domingo de los Tsáchilas', modernCountry:'Ecuador', iso3:'ECU', state:'Santo Domingo de los Tsáchilas', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Sucumbíos', modernCountry:'Ecuador', iso3:'ECU', state:'Sucumbíos', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Tungurahua', modernCountry:'Ecuador', iso3:'ECU', state:'Tungurahua', historicalContext:'Province of Ecuador.'),
  Place(continent:'Americas', name:'Zamora Chinchipe', modernCountry:'Ecuador', iso3:'ECU', state:'Zamora Chinchipe', historicalContext:'Province of Ecuador.'),

  // ── El Salvador ─────────────────────────────────────────────────
  Place(continent:'Americas', name:'Ahuachapán', modernCountry:'El Salvador', iso3:'SLV', state:'Ahuachapán', historicalContext:'Department of El Salvador.'),
  Place(continent:'Americas', name:'Cabañas', modernCountry:'El Salvador', iso3:'SLV', state:'Cabañas', historicalContext:'Department of El Salvador.'),
  Place(continent:'Americas', name:'Chalatenango', modernCountry:'El Salvador', iso3:'SLV', state:'Chalatenango', historicalContext:'Department of El Salvador.'),
  Place(continent:'Americas', name:'Cuscatlán', modernCountry:'El Salvador', iso3:'SLV', state:'Cuscatlán', historicalContext:'Department of El Salvador.'),
  Place(continent:'Americas', name:'La Libertad', modernCountry:'El Salvador', iso3:'SLV', state:'La Libertad', historicalContext:'Department of El Salvador.'),
  Place(continent:'Americas', name:'La Paz', modernCountry:'El Salvador', iso3:'SLV', state:'La Paz', historicalContext:'Department of El Salvador.'),
  Place(continent:'Americas', name:'La Unión', modernCountry:'El Salvador', iso3:'SLV', state:'La Unión', historicalContext:'Department of El Salvador.'),
  Place(continent:'Americas', name:'Morazán', modernCountry:'El Salvador', iso3:'SLV', state:'Morazán', historicalContext:'Department of El Salvador.'),
  Place(continent:'Americas', name:'San Miguel', modernCountry:'El Salvador', iso3:'SLV', state:'San Miguel', historicalContext:'Department of El Salvador.'),
  Place(continent:'Americas', name:'San Salvador', modernCountry:'El Salvador', iso3:'SLV', state:'San Salvador', historicalContext:'Department of El Salvador.'),
  Place(continent:'Americas', name:'San Vicente', modernCountry:'El Salvador', iso3:'SLV', state:'San Vicente', historicalContext:'Department of El Salvador.'),
  Place(continent:'Americas', name:'Santa Ana', modernCountry:'El Salvador', iso3:'SLV', state:'Santa Ana', historicalContext:'Department of El Salvador.'),
  Place(continent:'Americas', name:'Sonsonate', modernCountry:'El Salvador', iso3:'SLV', state:'Sonsonate', historicalContext:'Department of El Salvador.'),
  Place(continent:'Americas', name:'Usulután', modernCountry:'El Salvador', iso3:'SLV', state:'Usulután', historicalContext:'Department of El Salvador.'),

  // ── Greenland ───────────────────────────────────────────────────
  Place(continent:'Americas', name:'Avannaata Kommunia', modernCountry:'Greenland', iso3:'GRL', state:'Avannaata Kommunia', historicalContext:'Municipality of Greenland.'),
  Place(continent:'Americas', name:'Kommune Kujalleq', modernCountry:'Greenland', iso3:'GRL', state:'Kommune Kujalleq', historicalContext:'Municipality of Greenland.'),
  Place(continent:'Americas', name:'Kommune Qeqertalik', modernCountry:'Greenland', iso3:'GRL', state:'Kommune Qeqertalik', historicalContext:'Municipality of Greenland.'),
  Place(continent:'Americas', name:'Kommuneqarfik Sermersooq', modernCountry:'Greenland', iso3:'GRL', state:'Kommuneqarfik Sermersooq', historicalContext:'Municipality of Greenland.'),
  Place(continent:'Americas', name:'Qeqqata Kommunia', modernCountry:'Greenland', iso3:'GRL', state:'Qeqqata Kommunia', historicalContext:'Municipality of Greenland.'),

  // ── Grenada ─────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Saint Andrew', modernCountry:'Grenada', iso3:'GRD', state:'Saint Andrew', historicalContext:'Parish of Grenada.'),
  Place(continent:'Americas', name:'Saint David', modernCountry:'Grenada', iso3:'GRD', state:'Saint David', historicalContext:'Parish of Grenada.'),
  Place(continent:'Americas', name:'Saint George', modernCountry:'Grenada', iso3:'GRD', state:'Saint George', historicalContext:'Parish of Grenada.'),
  Place(continent:'Americas', name:'Saint John', modernCountry:'Grenada', iso3:'GRD', state:'Saint John', historicalContext:'Parish of Grenada.'),
  Place(continent:'Americas', name:'Saint Mark', modernCountry:'Grenada', iso3:'GRD', state:'Saint Mark', historicalContext:'Parish of Grenada.'),
  Place(continent:'Americas', name:'Saint Patrick', modernCountry:'Grenada', iso3:'GRD', state:'Saint Patrick', historicalContext:'Parish of Grenada.'),
  Place(continent:'Americas', name:'Southern Grenadine Islands', modernCountry:'Grenada', iso3:'GRD', state:'Southern Grenadine Islands', historicalContext:'Dependency of Grenada.'),

  // ── Guatemala ───────────────────────────────────────────────────
  Place(continent:'Americas', name:'Alta Verapaz', modernCountry:'Guatemala', iso3:'GTM', state:'Alta Verapaz', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'Baja Verapaz', modernCountry:'Guatemala', iso3:'GTM', state:'Baja Verapaz', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'Chimaltenango', modernCountry:'Guatemala', iso3:'GTM', state:'Chimaltenango', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'Chiquimula', modernCountry:'Guatemala', iso3:'GTM', state:'Chiquimula', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'El Progreso', modernCountry:'Guatemala', iso3:'GTM', state:'El Progreso', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'Escuintla', modernCountry:'Guatemala', iso3:'GTM', state:'Escuintla', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'Guatemala', modernCountry:'Guatemala', iso3:'GTM', state:'Guatemala', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'Huehuetenango', modernCountry:'Guatemala', iso3:'GTM', state:'Huehuetenango', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'Izabal', modernCountry:'Guatemala', iso3:'GTM', state:'Izabal', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'Jalapa', modernCountry:'Guatemala', iso3:'GTM', state:'Jalapa', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'Jutiapa', modernCountry:'Guatemala', iso3:'GTM', state:'Jutiapa', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'Petén', modernCountry:'Guatemala', iso3:'GTM', state:'Petén', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'Quetzaltenango', modernCountry:'Guatemala', iso3:'GTM', state:'Quetzaltenango', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'Quiché', modernCountry:'Guatemala', iso3:'GTM', state:'Quiché', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'Retalhuleu', modernCountry:'Guatemala', iso3:'GTM', state:'Retalhuleu', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'Sacatepéquez', modernCountry:'Guatemala', iso3:'GTM', state:'Sacatepéquez', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'San Marcos', modernCountry:'Guatemala', iso3:'GTM', state:'San Marcos', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'Santa Rosa', modernCountry:'Guatemala', iso3:'GTM', state:'Santa Rosa', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'Sololá', modernCountry:'Guatemala', iso3:'GTM', state:'Sololá', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'Suchitepéquez', modernCountry:'Guatemala', iso3:'GTM', state:'Suchitepéquez', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'Totonicapán', modernCountry:'Guatemala', iso3:'GTM', state:'Totonicapán', historicalContext:'Department of Guatemala.'),
  Place(continent:'Americas', name:'Zacapa', modernCountry:'Guatemala', iso3:'GTM', state:'Zacapa', historicalContext:'Department of Guatemala.'),

  // ── Guyana ──────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Barima-Waini', modernCountry:'Guyana', iso3:'GUY', state:'Barima-Waini', historicalContext:'Region of Guyana.'),
  Place(continent:'Americas', name:'Cuyuni-Mazaruni', modernCountry:'Guyana', iso3:'GUY', state:'Cuyuni-Mazaruni', historicalContext:'Region of Guyana.'),
  Place(continent:'Americas', name:'Demerara-Mahaica', modernCountry:'Guyana', iso3:'GUY', state:'Demerara-Mahaica', historicalContext:'Region of Guyana.'),
  Place(continent:'Americas', name:'East Berbice-Corentyne', modernCountry:'Guyana', iso3:'GUY', state:'East Berbice-Corentyne', historicalContext:'Region of Guyana.'),
  Place(continent:'Americas', name:'Essequibo Islands-West Demerara', modernCountry:'Guyana', iso3:'GUY', state:'Essequibo Islands-West Demerara', historicalContext:'Region of Guyana.'),
  Place(continent:'Americas', name:'Mahaica-Berbice', modernCountry:'Guyana', iso3:'GUY', state:'Mahaica-Berbice', historicalContext:'Region of Guyana.'),
  Place(continent:'Americas', name:'Pomeroon-Supenaam', modernCountry:'Guyana', iso3:'GUY', state:'Pomeroon-Supenaam', historicalContext:'Region of Guyana.'),
  Place(continent:'Americas', name:'Potaro-Siparuni', modernCountry:'Guyana', iso3:'GUY', state:'Potaro-Siparuni', historicalContext:'Region of Guyana.'),
  Place(continent:'Americas', name:'Upper Demerara-Berbice', modernCountry:'Guyana', iso3:'GUY', state:'Upper Demerara-Berbice', historicalContext:'Region of Guyana.'),
  Place(continent:'Americas', name:'Upper Takutu-Upper Essequibo', modernCountry:'Guyana', iso3:'GUY', state:'Upper Takutu-Upper Essequibo', historicalContext:'Region of Guyana.'),

  // ── Haiti ───────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Artibonite', modernCountry:'Haiti', iso3:'HTI', state:'Artibonite', historicalContext:'Department of Haiti.'),
  Place(continent:'Americas', name:'Centre', modernCountry:'Haiti', iso3:'HTI', state:'Centre', historicalContext:'Department of Haiti.'),
  Place(continent:'Americas', name:'Grande’Anse', modernCountry:'Haiti', iso3:'HTI', state:'Grande’Anse', historicalContext:'Department of Haiti.'),
  Place(continent:'Americas', name:'Nippes', modernCountry:'Haiti', iso3:'HTI', state:'Nippes', historicalContext:'Department of Haiti.'),
  Place(continent:'Americas', name:'Nord', modernCountry:'Haiti', iso3:'HTI', state:'Nord', historicalContext:'Department of Haiti.'),
  Place(continent:'Americas', name:'Nord-Est', modernCountry:'Haiti', iso3:'HTI', state:'Nord-Est', historicalContext:'Department of Haiti.'),
  Place(continent:'Americas', name:'Nord-Ouest', modernCountry:'Haiti', iso3:'HTI', state:'Nord-Ouest', historicalContext:'Department of Haiti.'),
  Place(continent:'Americas', name:'Ouest', modernCountry:'Haiti', iso3:'HTI', state:'Ouest', historicalContext:'Department of Haiti.'),
  Place(continent:'Americas', name:'Sud', modernCountry:'Haiti', iso3:'HTI', state:'Sud', historicalContext:'Department of Haiti.'),
  Place(continent:'Americas', name:'Sud-Est', modernCountry:'Haiti', iso3:'HTI', state:'Sud-Est', historicalContext:'Department of Haiti.'),

  // ── Honduras ────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Atlántida', modernCountry:'Honduras', iso3:'HND', state:'Atlántida', historicalContext:'Department of Honduras.'),
  Place(continent:'Americas', name:'Choluteca', modernCountry:'Honduras', iso3:'HND', state:'Choluteca', historicalContext:'Department of Honduras.'),
  Place(continent:'Americas', name:'Colón', modernCountry:'Honduras', iso3:'HND', state:'Colón', historicalContext:'Department of Honduras.'),
  Place(continent:'Americas', name:'Comayagua', modernCountry:'Honduras', iso3:'HND', state:'Comayagua', historicalContext:'Department of Honduras.'),
  Place(continent:'Americas', name:'Copán', modernCountry:'Honduras', iso3:'HND', state:'Copán', historicalContext:'Department of Honduras.'),
  Place(continent:'Americas', name:'Cortés', modernCountry:'Honduras', iso3:'HND', state:'Cortés', historicalContext:'Department of Honduras.'),
  Place(continent:'Americas', name:'El Paraíso', modernCountry:'Honduras', iso3:'HND', state:'El Paraíso', historicalContext:'Department of Honduras.'),
  Place(continent:'Americas', name:'Francisco Morazán', modernCountry:'Honduras', iso3:'HND', state:'Francisco Morazán', historicalContext:'Department of Honduras.'),
  Place(continent:'Americas', name:'Gracias a Dios', modernCountry:'Honduras', iso3:'HND', state:'Gracias a Dios', historicalContext:'Department of Honduras.'),
  Place(continent:'Americas', name:'Intibucá', modernCountry:'Honduras', iso3:'HND', state:'Intibucá', historicalContext:'Department of Honduras.'),
  Place(continent:'Americas', name:'Islas de la Bahía', modernCountry:'Honduras', iso3:'HND', state:'Islas de la Bahía', historicalContext:'Department of Honduras.'),
  Place(continent:'Americas', name:'La Paz', modernCountry:'Honduras', iso3:'HND', state:'La Paz', historicalContext:'Department of Honduras.'),
  Place(continent:'Americas', name:'Lempira', modernCountry:'Honduras', iso3:'HND', state:'Lempira', historicalContext:'Department of Honduras.'),
  Place(continent:'Americas', name:'Ocotepeque', modernCountry:'Honduras', iso3:'HND', state:'Ocotepeque', historicalContext:'Department of Honduras.'),
  Place(continent:'Americas', name:'Olancho', modernCountry:'Honduras', iso3:'HND', state:'Olancho', historicalContext:'Department of Honduras.'),
  Place(continent:'Americas', name:'Santa Bárbara', modernCountry:'Honduras', iso3:'HND', state:'Santa Bárbara', historicalContext:'Department of Honduras.'),
  Place(continent:'Americas', name:'Valle', modernCountry:'Honduras', iso3:'HND', state:'Valle', historicalContext:'Department of Honduras.'),
  Place(continent:'Americas', name:'Yoro', modernCountry:'Honduras', iso3:'HND', state:'Yoro', historicalContext:'Department of Honduras.'),

  // ── Jamaica ─────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Clarendon', modernCountry:'Jamaica', iso3:'JAM', state:'Clarendon', historicalContext:'Parish of Jamaica.'),
  Place(continent:'Americas', name:'Hanover', modernCountry:'Jamaica', iso3:'JAM', state:'Hanover', historicalContext:'Parish of Jamaica.'),
  Place(continent:'Americas', name:'Kingston', modernCountry:'Jamaica', iso3:'JAM', state:'Kingston', historicalContext:'Parish of Jamaica.'),
  Place(continent:'Americas', name:'Manchester', modernCountry:'Jamaica', iso3:'JAM', state:'Manchester', historicalContext:'Parish of Jamaica.'),
  Place(continent:'Americas', name:'Portland', modernCountry:'Jamaica', iso3:'JAM', state:'Portland', historicalContext:'Parish of Jamaica.'),
  Place(continent:'Americas', name:'Saint Andrew', modernCountry:'Jamaica', iso3:'JAM', state:'Saint Andrew', historicalContext:'Parish of Jamaica.'),
  Place(continent:'Americas', name:'Saint Ann', modernCountry:'Jamaica', iso3:'JAM', state:'Saint Ann', historicalContext:'Parish of Jamaica.'),
  Place(continent:'Americas', name:'Saint Catherine', modernCountry:'Jamaica', iso3:'JAM', state:'Saint Catherine', historicalContext:'Parish of Jamaica.'),
  Place(continent:'Americas', name:'Saint Elizabeth', modernCountry:'Jamaica', iso3:'JAM', state:'Saint Elizabeth', historicalContext:'Parish of Jamaica.'),
  Place(continent:'Americas', name:'Saint James', modernCountry:'Jamaica', iso3:'JAM', state:'Saint James', historicalContext:'Parish of Jamaica.'),
  Place(continent:'Americas', name:'Saint Mary', modernCountry:'Jamaica', iso3:'JAM', state:'Saint Mary', historicalContext:'Parish of Jamaica.'),
  Place(continent:'Americas', name:'Saint Thomas', modernCountry:'Jamaica', iso3:'JAM', state:'Saint Thomas', historicalContext:'Parish of Jamaica.'),
  Place(continent:'Americas', name:'Trelawny', modernCountry:'Jamaica', iso3:'JAM', state:'Trelawny', historicalContext:'Parish of Jamaica.'),
  Place(continent:'Americas', name:'Westmoreland', modernCountry:'Jamaica', iso3:'JAM', state:'Westmoreland', historicalContext:'Parish of Jamaica.'),

  // ── Mexico ──────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Aguascalientes', modernCountry:'Mexico', iso3:'MEX', state:'Aguascalientes', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Baja California', modernCountry:'Mexico', iso3:'MEX', state:'Baja California', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Baja California Sur', modernCountry:'Mexico', iso3:'MEX', state:'Baja California Sur', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Campeche', modernCountry:'Mexico', iso3:'MEX', state:'Campeche', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Chiapas', modernCountry:'Mexico', iso3:'MEX', state:'Chiapas', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Chihuahua', modernCountry:'Mexico', iso3:'MEX', state:'Chihuahua', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Ciudad de México', modernCountry:'Mexico', iso3:'MEX', state:'Ciudad de México', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Coahuila de Zaragoza', modernCountry:'Mexico', iso3:'MEX', state:'Coahuila de Zaragoza', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Colima', modernCountry:'Mexico', iso3:'MEX', state:'Colima', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Durango', modernCountry:'Mexico', iso3:'MEX', state:'Durango', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Guanajuato', modernCountry:'Mexico', iso3:'MEX', state:'Guanajuato', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Guerrero', modernCountry:'Mexico', iso3:'MEX', state:'Guerrero', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Hidalgo', modernCountry:'Mexico', iso3:'MEX', state:'Hidalgo', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Jalisco', modernCountry:'Mexico', iso3:'MEX', state:'Jalisco', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Michoacán de Ocampo', modernCountry:'Mexico', iso3:'MEX', state:'Michoacán de Ocampo', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Morelos', modernCountry:'Mexico', iso3:'MEX', state:'Morelos', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'México', modernCountry:'Mexico', iso3:'MEX', state:'México', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Nayarit', modernCountry:'Mexico', iso3:'MEX', state:'Nayarit', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Nuevo León', modernCountry:'Mexico', iso3:'MEX', state:'Nuevo León', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Oaxaca', modernCountry:'Mexico', iso3:'MEX', state:'Oaxaca', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Puebla', modernCountry:'Mexico', iso3:'MEX', state:'Puebla', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Querétaro', modernCountry:'Mexico', iso3:'MEX', state:'Querétaro', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Quintana Roo', modernCountry:'Mexico', iso3:'MEX', state:'Quintana Roo', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'San Luis Potosí', modernCountry:'Mexico', iso3:'MEX', state:'San Luis Potosí', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Sinaloa', modernCountry:'Mexico', iso3:'MEX', state:'Sinaloa', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Sonora', modernCountry:'Mexico', iso3:'MEX', state:'Sonora', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Tabasco', modernCountry:'Mexico', iso3:'MEX', state:'Tabasco', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Tamaulipas', modernCountry:'Mexico', iso3:'MEX', state:'Tamaulipas', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Tlaxcala', modernCountry:'Mexico', iso3:'MEX', state:'Tlaxcala', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Veracruz de Ignacio de la Llave', modernCountry:'Mexico', iso3:'MEX', state:'Veracruz de Ignacio de la Llave', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Yucatán', modernCountry:'Mexico', iso3:'MEX', state:'Yucatán', historicalContext:'State or federal entity of Mexico.'),
  Place(continent:'Americas', name:'Zacatecas', modernCountry:'Mexico', iso3:'MEX', state:'Zacatecas', historicalContext:'State or federal entity of Mexico.'),

  // ── Nicaragua ───────────────────────────────────────────────────
  Place(continent:'Americas', name:'Boaco', modernCountry:'Nicaragua', iso3:'NIC', state:'Boaco', historicalContext:'Department of Nicaragua.'),
  Place(continent:'Americas', name:'Carazo', modernCountry:'Nicaragua', iso3:'NIC', state:'Carazo', historicalContext:'Department of Nicaragua.'),
  Place(continent:'Americas', name:'Chinandega', modernCountry:'Nicaragua', iso3:'NIC', state:'Chinandega', historicalContext:'Department of Nicaragua.'),
  Place(continent:'Americas', name:'Chontales', modernCountry:'Nicaragua', iso3:'NIC', state:'Chontales', historicalContext:'Department of Nicaragua.'),
  Place(continent:'Americas', name:'Costa Caribe Norte', modernCountry:'Nicaragua', iso3:'NIC', state:'Costa Caribe Norte', historicalContext:'Autonomous region of Nicaragua.'),
  Place(continent:'Americas', name:'Costa Caribe Sur', modernCountry:'Nicaragua', iso3:'NIC', state:'Costa Caribe Sur', historicalContext:'Autonomous region of Nicaragua.'),
  Place(continent:'Americas', name:'Estelí', modernCountry:'Nicaragua', iso3:'NIC', state:'Estelí', historicalContext:'Department of Nicaragua.'),
  Place(continent:'Americas', name:'Granada', modernCountry:'Nicaragua', iso3:'NIC', state:'Granada', historicalContext:'Department of Nicaragua.'),
  Place(continent:'Americas', name:'Jinotega', modernCountry:'Nicaragua', iso3:'NIC', state:'Jinotega', historicalContext:'Department of Nicaragua.'),
  Place(continent:'Americas', name:'León', modernCountry:'Nicaragua', iso3:'NIC', state:'León', historicalContext:'Department of Nicaragua.'),
  Place(continent:'Americas', name:'Madriz', modernCountry:'Nicaragua', iso3:'NIC', state:'Madriz', historicalContext:'Department of Nicaragua.'),
  Place(continent:'Americas', name:'Managua', modernCountry:'Nicaragua', iso3:'NIC', state:'Managua', historicalContext:'Department of Nicaragua.'),
  Place(continent:'Americas', name:'Masaya', modernCountry:'Nicaragua', iso3:'NIC', state:'Masaya', historicalContext:'Department of Nicaragua.'),
  Place(continent:'Americas', name:'Matagalpa', modernCountry:'Nicaragua', iso3:'NIC', state:'Matagalpa', historicalContext:'Department of Nicaragua.'),
  Place(continent:'Americas', name:'Nueva Segovia', modernCountry:'Nicaragua', iso3:'NIC', state:'Nueva Segovia', historicalContext:'Department of Nicaragua.'),
  Place(continent:'Americas', name:'Rivas', modernCountry:'Nicaragua', iso3:'NIC', state:'Rivas', historicalContext:'Department of Nicaragua.'),
  Place(continent:'Americas', name:'Río San Juan', modernCountry:'Nicaragua', iso3:'NIC', state:'Río San Juan', historicalContext:'Department of Nicaragua.'),

  // ── Panama ──────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Bocas del Toro', modernCountry:'Panama', iso3:'PAN', state:'Bocas del Toro', historicalContext:'Province of Panama.'),
  Place(continent:'Americas', name:'Chiriquí', modernCountry:'Panama', iso3:'PAN', state:'Chiriquí', historicalContext:'Province of Panama.'),
  Place(continent:'Americas', name:'Coclé', modernCountry:'Panama', iso3:'PAN', state:'Coclé', historicalContext:'Province of Panama.'),
  Place(continent:'Americas', name:'Colón', modernCountry:'Panama', iso3:'PAN', state:'Colón', historicalContext:'Province of Panama.'),
  Place(continent:'Americas', name:'Darién', modernCountry:'Panama', iso3:'PAN', state:'Darién', historicalContext:'Province of Panama.'),
  Place(continent:'Americas', name:'Emberá', modernCountry:'Panama', iso3:'PAN', state:'Emberá', historicalContext:'Indigenous region of Panama.'),
  Place(continent:'Americas', name:'Guna Yala', modernCountry:'Panama', iso3:'PAN', state:'Guna Yala', historicalContext:'Indigenous region of Panama.'),
  Place(continent:'Americas', name:'Herrera', modernCountry:'Panama', iso3:'PAN', state:'Herrera', historicalContext:'Province of Panama.'),
  Place(continent:'Americas', name:'Los Santos', modernCountry:'Panama', iso3:'PAN', state:'Los Santos', historicalContext:'Province of Panama.'),
  Place(continent:'Americas', name:'Naso Tjër Di', modernCountry:'Panama', iso3:'PAN', state:'Naso Tjër Di', historicalContext:'Indigenous region of Panama.'),
  Place(continent:'Americas', name:'Ngäbe-Buglé', modernCountry:'Panama', iso3:'PAN', state:'Ngäbe-Buglé', historicalContext:'Indigenous region of Panama.'),
  Place(continent:'Americas', name:'Panamá', modernCountry:'Panama', iso3:'PAN', state:'Panamá', historicalContext:'Province of Panama.'),
  Place(continent:'Americas', name:'Panamá Oeste', modernCountry:'Panama', iso3:'PAN', state:'Panamá Oeste', historicalContext:'Province of Panama.'),
  Place(continent:'Americas', name:'Veraguas', modernCountry:'Panama', iso3:'PAN', state:'Veraguas', historicalContext:'Province of Panama.'),

  // ── Paraguay ────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Alto Paraguay', modernCountry:'Paraguay', iso3:'PRY', state:'Alto Paraguay', historicalContext:'Department of Paraguay.'),
  Place(continent:'Americas', name:'Alto Paraná', modernCountry:'Paraguay', iso3:'PRY', state:'Alto Paraná', historicalContext:'Department of Paraguay.'),
  Place(continent:'Americas', name:'Amambay', modernCountry:'Paraguay', iso3:'PRY', state:'Amambay', historicalContext:'Department of Paraguay.'),
  Place(continent:'Americas', name:'Asunción', modernCountry:'Paraguay', iso3:'PRY', state:'Asunción', historicalContext:'Capital of Paraguay.'),
  Place(continent:'Americas', name:'Boquerón', modernCountry:'Paraguay', iso3:'PRY', state:'Boquerón', historicalContext:'Department of Paraguay.'),
  Place(continent:'Americas', name:'Caaguazú', modernCountry:'Paraguay', iso3:'PRY', state:'Caaguazú', historicalContext:'Department of Paraguay.'),
  Place(continent:'Americas', name:'Caazapá', modernCountry:'Paraguay', iso3:'PRY', state:'Caazapá', historicalContext:'Department of Paraguay.'),
  Place(continent:'Americas', name:'Canindeyú', modernCountry:'Paraguay', iso3:'PRY', state:'Canindeyú', historicalContext:'Department of Paraguay.'),
  Place(continent:'Americas', name:'Central', modernCountry:'Paraguay', iso3:'PRY', state:'Central', historicalContext:'Department of Paraguay.'),
  Place(continent:'Americas', name:'Concepción', modernCountry:'Paraguay', iso3:'PRY', state:'Concepción', historicalContext:'Department of Paraguay.'),
  Place(continent:'Americas', name:'Cordillera', modernCountry:'Paraguay', iso3:'PRY', state:'Cordillera', historicalContext:'Department of Paraguay.'),
  Place(continent:'Americas', name:'Guairá', modernCountry:'Paraguay', iso3:'PRY', state:'Guairá', historicalContext:'Department of Paraguay.'),
  Place(continent:'Americas', name:'Itapúa', modernCountry:'Paraguay', iso3:'PRY', state:'Itapúa', historicalContext:'Department of Paraguay.'),
  Place(continent:'Americas', name:'Misiones', modernCountry:'Paraguay', iso3:'PRY', state:'Misiones', historicalContext:'Department of Paraguay.'),
  Place(continent:'Americas', name:'Paraguarí', modernCountry:'Paraguay', iso3:'PRY', state:'Paraguarí', historicalContext:'Department of Paraguay.'),
  Place(continent:'Americas', name:'Presidente Hayes', modernCountry:'Paraguay', iso3:'PRY', state:'Presidente Hayes', historicalContext:'Department of Paraguay.'),
  Place(continent:'Americas', name:'San Pedro', modernCountry:'Paraguay', iso3:'PRY', state:'San Pedro', historicalContext:'Department of Paraguay.'),
  Place(continent:'Americas', name:'Ñeembucú', modernCountry:'Paraguay', iso3:'PRY', state:'Ñeembucú', historicalContext:'Department of Paraguay.'),

  // ── Peru ────────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Amazonas', modernCountry:'Peru', iso3:'PER', state:'Amazonas', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Ancash', modernCountry:'Peru', iso3:'PER', state:'Ancash', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Apurímac', modernCountry:'Peru', iso3:'PER', state:'Apurímac', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Arequipa', modernCountry:'Peru', iso3:'PER', state:'Arequipa', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Ayacucho', modernCountry:'Peru', iso3:'PER', state:'Ayacucho', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Cajamarca', modernCountry:'Peru', iso3:'PER', state:'Cajamarca', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Cusco', modernCountry:'Peru', iso3:'PER', state:'Cusco', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'El Callao', modernCountry:'Peru', iso3:'PER', state:'El Callao', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Huancavelica', modernCountry:'Peru', iso3:'PER', state:'Huancavelica', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Huánuco', modernCountry:'Peru', iso3:'PER', state:'Huánuco', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Ica', modernCountry:'Peru', iso3:'PER', state:'Ica', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Junín', modernCountry:'Peru', iso3:'PER', state:'Junín', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'La Libertad', modernCountry:'Peru', iso3:'PER', state:'La Libertad', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Lambayeque', modernCountry:'Peru', iso3:'PER', state:'Lambayeque', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Lima', modernCountry:'Peru', iso3:'PER', state:'Lima', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Loreto', modernCountry:'Peru', iso3:'PER', state:'Loreto', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Madre de Dios', modernCountry:'Peru', iso3:'PER', state:'Madre de Dios', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Moquegua', modernCountry:'Peru', iso3:'PER', state:'Moquegua', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Municipalidad Metropolitana de Lima', modernCountry:'Peru', iso3:'PER', state:'Municipalidad Metropolitana de Lima', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Pasco', modernCountry:'Peru', iso3:'PER', state:'Pasco', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Piura', modernCountry:'Peru', iso3:'PER', state:'Piura', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Puno', modernCountry:'Peru', iso3:'PER', state:'Puno', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'San Martín', modernCountry:'Peru', iso3:'PER', state:'San Martín', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Tacna', modernCountry:'Peru', iso3:'PER', state:'Tacna', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Tumbes', modernCountry:'Peru', iso3:'PER', state:'Tumbes', historicalContext:'Region of Peru.'),
  Place(continent:'Americas', name:'Ucayali', modernCountry:'Peru', iso3:'PER', state:'Ucayali', historicalContext:'Region of Peru.'),

  // ── Saint Kitts and Nevis ───────────────────────────────────────
  Place(continent:'Americas', name:'Nevis', modernCountry:'Saint Kitts and Nevis', iso3:'KNA', state:'Nevis', historicalContext:'State of Saint Kitts and Nevis.'),
  Place(continent:'Americas', name:'Saint Kitts', modernCountry:'Saint Kitts and Nevis', iso3:'KNA', state:'Saint Kitts', historicalContext:'State of Saint Kitts and Nevis.'),

  // ── Saint Lucia ─────────────────────────────────────────────────
  Place(continent:'Americas', name:'Anse la Raye', modernCountry:'Saint Lucia', iso3:'LCA', state:'Anse la Raye', historicalContext:'District of Saint Lucia.'),
  Place(continent:'Americas', name:'Canaries', modernCountry:'Saint Lucia', iso3:'LCA', state:'Canaries', historicalContext:'District of Saint Lucia.'),
  Place(continent:'Americas', name:'Castries', modernCountry:'Saint Lucia', iso3:'LCA', state:'Castries', historicalContext:'District of Saint Lucia.'),
  Place(continent:'Americas', name:'Choiseul', modernCountry:'Saint Lucia', iso3:'LCA', state:'Choiseul', historicalContext:'District of Saint Lucia.'),
  Place(continent:'Americas', name:'Dennery', modernCountry:'Saint Lucia', iso3:'LCA', state:'Dennery', historicalContext:'District of Saint Lucia.'),
  Place(continent:'Americas', name:'Gros Islet', modernCountry:'Saint Lucia', iso3:'LCA', state:'Gros Islet', historicalContext:'District of Saint Lucia.'),
  Place(continent:'Americas', name:'Laborie', modernCountry:'Saint Lucia', iso3:'LCA', state:'Laborie', historicalContext:'District of Saint Lucia.'),
  Place(continent:'Americas', name:'Micoud', modernCountry:'Saint Lucia', iso3:'LCA', state:'Micoud', historicalContext:'District of Saint Lucia.'),
  Place(continent:'Americas', name:'Soufrière', modernCountry:'Saint Lucia', iso3:'LCA', state:'Soufrière', historicalContext:'District of Saint Lucia.'),
  Place(continent:'Americas', name:'Vieux Fort', modernCountry:'Saint Lucia', iso3:'LCA', state:'Vieux Fort', historicalContext:'District of Saint Lucia.'),

  // ── Saint Vincent and the Grenadines ────────────────────────────
  Place(continent:'Americas', name:'Charlotte', modernCountry:'Saint Vincent and the Grenadines', iso3:'VCT', state:'Charlotte', historicalContext:'Parish of Saint Vincent and the Grenadines.'),
  Place(continent:'Americas', name:'Grenadines', modernCountry:'Saint Vincent and the Grenadines', iso3:'VCT', state:'Grenadines', historicalContext:'Parish of Saint Vincent and the Grenadines.'),
  Place(continent:'Americas', name:'Saint Andrew', modernCountry:'Saint Vincent and the Grenadines', iso3:'VCT', state:'Saint Andrew', historicalContext:'Parish of Saint Vincent and the Grenadines.'),
  Place(continent:'Americas', name:'Saint David', modernCountry:'Saint Vincent and the Grenadines', iso3:'VCT', state:'Saint David', historicalContext:'Parish of Saint Vincent and the Grenadines.'),
  Place(continent:'Americas', name:'Saint George', modernCountry:'Saint Vincent and the Grenadines', iso3:'VCT', state:'Saint George', historicalContext:'Parish of Saint Vincent and the Grenadines.'),
  Place(continent:'Americas', name:'Saint Patrick', modernCountry:'Saint Vincent and the Grenadines', iso3:'VCT', state:'Saint Patrick', historicalContext:'Parish of Saint Vincent and the Grenadines.'),

  // ── Suriname ────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Brokopondo', modernCountry:'Suriname', iso3:'SUR', state:'Brokopondo', historicalContext:'District of Suriname.'),
  Place(continent:'Americas', name:'Commewijne', modernCountry:'Suriname', iso3:'SUR', state:'Commewijne', historicalContext:'District of Suriname.'),
  Place(continent:'Americas', name:'Coronie', modernCountry:'Suriname', iso3:'SUR', state:'Coronie', historicalContext:'District of Suriname.'),
  Place(continent:'Americas', name:'Marowijne', modernCountry:'Suriname', iso3:'SUR', state:'Marowijne', historicalContext:'District of Suriname.'),
  Place(continent:'Americas', name:'Nickerie', modernCountry:'Suriname', iso3:'SUR', state:'Nickerie', historicalContext:'District of Suriname.'),
  Place(continent:'Americas', name:'Para', modernCountry:'Suriname', iso3:'SUR', state:'Para', historicalContext:'District of Suriname.'),
  Place(continent:'Americas', name:'Paramaribo', modernCountry:'Suriname', iso3:'SUR', state:'Paramaribo', historicalContext:'District of Suriname.'),
  Place(continent:'Americas', name:'Saramacca', modernCountry:'Suriname', iso3:'SUR', state:'Saramacca', historicalContext:'District of Suriname.'),
  Place(continent:'Americas', name:'Sipaliwini', modernCountry:'Suriname', iso3:'SUR', state:'Sipaliwini', historicalContext:'District of Suriname.'),
  Place(continent:'Americas', name:'Wanica', modernCountry:'Suriname', iso3:'SUR', state:'Wanica', historicalContext:'District of Suriname.'),

  // ── Trinidad and Tobago ─────────────────────────────────────────
  Place(continent:'Americas', name:'Arima', modernCountry:'Trinidad and Tobago', iso3:'TTO', state:'Arima', historicalContext:'Borough of Trinidad and Tobago.'),
  Place(continent:'Americas', name:'Chaguanas', modernCountry:'Trinidad and Tobago', iso3:'TTO', state:'Chaguanas', historicalContext:'Borough of Trinidad and Tobago.'),
  Place(continent:'Americas', name:'Couva-Tabaquite-Talparo', modernCountry:'Trinidad and Tobago', iso3:'TTO', state:'Couva-Tabaquite-Talparo', historicalContext:'Region of Trinidad and Tobago.'),
  Place(continent:'Americas', name:'Diego Martin', modernCountry:'Trinidad and Tobago', iso3:'TTO', state:'Diego Martin', historicalContext:'Region of Trinidad and Tobago.'),
  Place(continent:'Americas', name:'Mayaro-Rio Claro', modernCountry:'Trinidad and Tobago', iso3:'TTO', state:'Mayaro-Rio Claro', historicalContext:'Region of Trinidad and Tobago.'),
  Place(continent:'Americas', name:'Penal-Debe', modernCountry:'Trinidad and Tobago', iso3:'TTO', state:'Penal-Debe', historicalContext:'Region of Trinidad and Tobago.'),
  Place(continent:'Americas', name:'Point Fortin', modernCountry:'Trinidad and Tobago', iso3:'TTO', state:'Point Fortin', historicalContext:'Borough of Trinidad and Tobago.'),
  Place(continent:'Americas', name:'Port of Spain', modernCountry:'Trinidad and Tobago', iso3:'TTO', state:'Port of Spain', historicalContext:'City of Trinidad and Tobago.'),
  Place(continent:'Americas', name:'Princes Town', modernCountry:'Trinidad and Tobago', iso3:'TTO', state:'Princes Town', historicalContext:'Region of Trinidad and Tobago.'),
  Place(continent:'Americas', name:'San Fernando', modernCountry:'Trinidad and Tobago', iso3:'TTO', state:'San Fernando', historicalContext:'City of Trinidad and Tobago.'),
  Place(continent:'Americas', name:'San Juan-Laventille', modernCountry:'Trinidad and Tobago', iso3:'TTO', state:'San Juan-Laventille', historicalContext:'Region of Trinidad and Tobago.'),
  Place(continent:'Americas', name:'Sangre Grande', modernCountry:'Trinidad and Tobago', iso3:'TTO', state:'Sangre Grande', historicalContext:'Region of Trinidad and Tobago.'),
  Place(continent:'Americas', name:'Siparia', modernCountry:'Trinidad and Tobago', iso3:'TTO', state:'Siparia', historicalContext:'Region of Trinidad and Tobago.'),
  Place(continent:'Americas', name:'Tobago', modernCountry:'Trinidad and Tobago', iso3:'TTO', state:'Tobago', historicalContext:'Ward of Trinidad and Tobago.'),
  Place(continent:'Americas', name:'Tunapuna-Piarco', modernCountry:'Trinidad and Tobago', iso3:'TTO', state:'Tunapuna-Piarco', historicalContext:'Region of Trinidad and Tobago.'),

  // ── United States ───────────────────────────────────────────────
  Place(continent:'Americas', name:'Alabama', modernCountry:'United States', iso3:'USA', state:'Alabama', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Alaska', modernCountry:'United States', iso3:'USA', state:'Alaska', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'American Samoa', modernCountry:'United States', iso3:'USA', state:'American Samoa', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Arizona', modernCountry:'United States', iso3:'USA', state:'Arizona', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Arkansas', modernCountry:'United States', iso3:'USA', state:'Arkansas', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'California', modernCountry:'United States', iso3:'USA', state:'California', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Colorado', modernCountry:'United States', iso3:'USA', state:'Colorado', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Connecticut', modernCountry:'United States', iso3:'USA', state:'Connecticut', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Delaware', modernCountry:'United States', iso3:'USA', state:'Delaware', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'District of Columbia', modernCountry:'United States', iso3:'USA', state:'District of Columbia', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Florida', modernCountry:'United States', iso3:'USA', state:'Florida', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Georgia', modernCountry:'United States', iso3:'USA', state:'Georgia', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Guam', modernCountry:'United States', iso3:'USA', state:'Guam', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Hawaii', modernCountry:'United States', iso3:'USA', state:'Hawaii', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Idaho', modernCountry:'United States', iso3:'USA', state:'Idaho', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Illinois', modernCountry:'United States', iso3:'USA', state:'Illinois', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Indiana', modernCountry:'United States', iso3:'USA', state:'Indiana', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Iowa', modernCountry:'United States', iso3:'USA', state:'Iowa', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Kansas', modernCountry:'United States', iso3:'USA', state:'Kansas', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Kentucky', modernCountry:'United States', iso3:'USA', state:'Kentucky', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Louisiana', modernCountry:'United States', iso3:'USA', state:'Louisiana', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Maine', modernCountry:'United States', iso3:'USA', state:'Maine', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Maryland', modernCountry:'United States', iso3:'USA', state:'Maryland', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Massachusetts', modernCountry:'United States', iso3:'USA', state:'Massachusetts', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Michigan', modernCountry:'United States', iso3:'USA', state:'Michigan', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Minnesota', modernCountry:'United States', iso3:'USA', state:'Minnesota', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Mississippi', modernCountry:'United States', iso3:'USA', state:'Mississippi', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Missouri', modernCountry:'United States', iso3:'USA', state:'Missouri', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Montana', modernCountry:'United States', iso3:'USA', state:'Montana', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Nebraska', modernCountry:'United States', iso3:'USA', state:'Nebraska', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Nevada', modernCountry:'United States', iso3:'USA', state:'Nevada', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'New Hampshire', modernCountry:'United States', iso3:'USA', state:'New Hampshire', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'New Jersey', modernCountry:'United States', iso3:'USA', state:'New Jersey', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'New Mexico', modernCountry:'United States', iso3:'USA', state:'New Mexico', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'New York', modernCountry:'United States', iso3:'USA', state:'New York', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'North Carolina', modernCountry:'United States', iso3:'USA', state:'North Carolina', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'North Dakota', modernCountry:'United States', iso3:'USA', state:'North Dakota', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Northern Mariana Islands', modernCountry:'United States', iso3:'USA', state:'Northern Mariana Islands', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Ohio', modernCountry:'United States', iso3:'USA', state:'Ohio', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Oklahoma', modernCountry:'United States', iso3:'USA', state:'Oklahoma', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Oregon', modernCountry:'United States', iso3:'USA', state:'Oregon', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Pennsylvania', modernCountry:'United States', iso3:'USA', state:'Pennsylvania', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Puerto Rico', modernCountry:'United States', iso3:'USA', state:'Puerto Rico', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Rhode Island', modernCountry:'United States', iso3:'USA', state:'Rhode Island', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'South Carolina', modernCountry:'United States', iso3:'USA', state:'South Carolina', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'South Dakota', modernCountry:'United States', iso3:'USA', state:'South Dakota', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Tennessee', modernCountry:'United States', iso3:'USA', state:'Tennessee', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Texas', modernCountry:'United States', iso3:'USA', state:'Texas', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'United States Minor Outlying Islands', modernCountry:'United States', iso3:'USA', state:'United States Minor Outlying Islands', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Utah', modernCountry:'United States', iso3:'USA', state:'Utah', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Vermont', modernCountry:'United States', iso3:'USA', state:'Vermont', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Virgin Islands, U.S.', modernCountry:'United States', iso3:'USA', state:'Virgin Islands, U.S.', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Virginia', modernCountry:'United States', iso3:'USA', state:'Virginia', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Washington', modernCountry:'United States', iso3:'USA', state:'Washington', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'West Virginia', modernCountry:'United States', iso3:'USA', state:'West Virginia', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Wisconsin', modernCountry:'United States', iso3:'USA', state:'Wisconsin', historicalContext:'State of the United States.'),
  Place(continent:'Americas', name:'Wyoming', modernCountry:'United States', iso3:'USA', state:'Wyoming', historicalContext:'State of the United States.'),

  // ── Uruguay ─────────────────────────────────────────────────────
  Place(continent:'Americas', name:'Artigas', modernCountry:'Uruguay', iso3:'URY', state:'Artigas', historicalContext:'Department of Uruguay.'),
  Place(continent:'Americas', name:'Canelones', modernCountry:'Uruguay', iso3:'URY', state:'Canelones', historicalContext:'Department of Uruguay.'),
  Place(continent:'Americas', name:'Cerro Largo', modernCountry:'Uruguay', iso3:'URY', state:'Cerro Largo', historicalContext:'Department of Uruguay.'),
  Place(continent:'Americas', name:'Colonia', modernCountry:'Uruguay', iso3:'URY', state:'Colonia', historicalContext:'Department of Uruguay.'),
  Place(continent:'Americas', name:'Durazno', modernCountry:'Uruguay', iso3:'URY', state:'Durazno', historicalContext:'Department of Uruguay.'),
  Place(continent:'Americas', name:'Flores', modernCountry:'Uruguay', iso3:'URY', state:'Flores', historicalContext:'Department of Uruguay.'),
  Place(continent:'Americas', name:'Florida', modernCountry:'Uruguay', iso3:'URY', state:'Florida', historicalContext:'Department of Uruguay.'),
  Place(continent:'Americas', name:'Lavalleja', modernCountry:'Uruguay', iso3:'URY', state:'Lavalleja', historicalContext:'Department of Uruguay.'),
  Place(continent:'Americas', name:'Maldonado', modernCountry:'Uruguay', iso3:'URY', state:'Maldonado', historicalContext:'Department of Uruguay.'),
  Place(continent:'Americas', name:'Montevideo', modernCountry:'Uruguay', iso3:'URY', state:'Montevideo', historicalContext:'Department of Uruguay.'),
  Place(continent:'Americas', name:'Paysandú', modernCountry:'Uruguay', iso3:'URY', state:'Paysandú', historicalContext:'Department of Uruguay.'),
  Place(continent:'Americas', name:'Rivera', modernCountry:'Uruguay', iso3:'URY', state:'Rivera', historicalContext:'Department of Uruguay.'),
  Place(continent:'Americas', name:'Rocha', modernCountry:'Uruguay', iso3:'URY', state:'Rocha', historicalContext:'Department of Uruguay.'),
  Place(continent:'Americas', name:'Río Negro', modernCountry:'Uruguay', iso3:'URY', state:'Río Negro', historicalContext:'Department of Uruguay.'),
  Place(continent:'Americas', name:'Salto', modernCountry:'Uruguay', iso3:'URY', state:'Salto', historicalContext:'Department of Uruguay.'),
  Place(continent:'Americas', name:'San José', modernCountry:'Uruguay', iso3:'URY', state:'San José', historicalContext:'Department of Uruguay.'),
  Place(continent:'Americas', name:'Soriano', modernCountry:'Uruguay', iso3:'URY', state:'Soriano', historicalContext:'Department of Uruguay.'),
  Place(continent:'Americas', name:'Tacuarembó', modernCountry:'Uruguay', iso3:'URY', state:'Tacuarembó', historicalContext:'Department of Uruguay.'),
  Place(continent:'Americas', name:'Treinta y Tres', modernCountry:'Uruguay', iso3:'URY', state:'Treinta y Tres', historicalContext:'Department of Uruguay.'),

  // ── Venezuela, Bolivarian Republic of ───────────────────────────
  Place(continent:'Americas', name:'Amazonas', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Amazonas', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Anzoátegui', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Anzoátegui', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Apure', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Apure', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Aragua', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Aragua', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Barinas', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Barinas', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Bolívar', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Bolívar', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Carabobo', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Carabobo', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Cojedes', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Cojedes', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Delta Amacuro', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Delta Amacuro', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Dependencias Federales', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Dependencias Federales', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Distrito Capital', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Distrito Capital', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Falcón', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Falcón', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Guárico', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Guárico', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'La Guaira', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'La Guaira', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Lara', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Lara', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Miranda', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Miranda', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Monagas', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Monagas', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Mérida', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Mérida', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Nueva Esparta', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Nueva Esparta', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Portuguesa', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Portuguesa', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Sucre', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Sucre', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Trujillo', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Trujillo', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Táchira', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Táchira', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Yaracuy', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Yaracuy', historicalContext:'State of Venezuela.'),
  Place(continent:'Americas', name:'Zulia', modernCountry:'Venezuela, Bolivarian Republic of', iso3:'VEN', state:'Zulia', historicalContext:'State of Venezuela.'),
];
