import '../models/place.dart';

/// Europe: organised continent → country → state/region → county → city
const List<Place> placesEurope = [

  // ── Albania ──────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Tirana', modernCountry:'Albania', iso3:'ALB', state:'Tirana County',
    historicalContext:'Capital of Albania; grew under Ottoman rule, became capital in 1920.',
    colonizer:'Ottoman Empire', nativeTribes:'Illyrians', romanizedNative:'Tiranë'),

  // ── Andorra ──────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Andorra la Vella', modernCountry:'Andorra', iso3:'AND', state:'Andorra la Vella Parish',
    historicalContext:'Capital of the Andorran co-principality, established in 1278.',
    nativeTribes:'Andorrans (Catalan-speaking)'),

  // ── Austria ──────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Vienna', modernCountry:'Austria', iso3:'AUT', state:'Vienna',
    historicalContext:'Capital of the Habsburg and Austro-Hungarian Empire; major genealogy records hub.',
    colonizer:'Roman Empire, Habsburg Dynasty', nativeTribes:'Celtic Boii', romanizedNative:'Vindobona'),
  Place(continent:'Europe', name:'Graz', modernCountry:'Austria', iso3:'AUT', state:'Styria',
    historicalContext:'Second largest Austrian city; Styria region records date to medieval period.',
    colonizer:'Habsburg Dynasty', nativeTribes:'Celtic Celts', romanizedNative:'Gratz'),
  Place(continent:'Europe', name:'Salzburg', modernCountry:'Austria', iso3:'AUT', state:'Salzburg',
    historicalContext:'Birthplace of Mozart; formerly an independent prince-archbishopric.',
    colonizer:'Holy Roman Empire', romanizedNative:'Juvavum'),
  Place(continent:'Europe', name:'Innsbruck', modernCountry:'Austria', iso3:'AUT', state:'Tyrol',
    historicalContext:'Habsburg seat; Tyrol was passed between Austria and Bavaria through centuries.',
    colonizer:'Habsburg Dynasty'),

  // ── Belarus ──────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Minsk', modernCountry:'Belarus', iso3:'BLR', state:'Minsk Region',
    historicalContext:'Capital of Belarus; occupied by Poland-Lithuania, Russia, and Soviet Union.',
    colonizer:'Polish-Lithuanian Commonwealth, Russian Empire', nativeTribes:'Eastern Slavs', romanizedNative:'Mensk'),
  Place(continent:'Europe', name:'Brest', modernCountry:'Belarus', iso3:'BLR', state:'Brest Region',
    historicalContext:'Border city; Treaty of Brest-Litovsk signed here 1918.',
    colonizer:'Polish-Lithuanian Commonwealth, Russian Empire', romanizedNative:'Brest-Litovsk'),
  Place(continent:'Europe', name:'Grodno', modernCountry:'Belarus', iso3:'BLR', state:'Grodno Region',
    historicalContext:'Historic Jewish community; passed between Poland and Russia many times.',
    colonizer:'Polish-Lithuanian Commonwealth, Russian Empire', romanizedNative:'Hrodna'),

  // ── Belgium ──────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Brussels', modernCountry:'Belgium', iso3:'BEL', state:'Brussels Capital Region',
    historicalContext:'Capital of Belgium and the EU; formerly part of Spanish and Austrian Netherlands.',
    colonizer:'Spanish Netherlands, Austrian Netherlands', nativeTribes:'Celtic Belgae', romanizedNative:'Bruxellae'),
  Place(continent:'Europe', name:'Antwerp', modernCountry:'Belgium', iso3:'BEL', state:'Antwerp Province',
    historicalContext:'Major port; commercial hub of the Habsburg Netherlands in the 16th century.',
    colonizer:'Spanish Netherlands', nativeTribes:'Celtic Belgae', romanizedNative:'Antverpiae'),
  Place(continent:'Europe', name:'Ghent', modernCountry:'Belgium', iso3:'BEL', state:'East Flanders',
    historicalContext:'Medieval cloth-trade city; birthplace of Holy Roman Emperor Charles V.',
    colonizer:'Spanish Netherlands', romanizedNative:'Gent'),
  Place(continent:'Europe', name:'Liège', modernCountry:'Belgium', iso3:'BEL', state:'Liège Province',
    historicalContext:'Industrial Walloon city; former prince-bishopric with independent medieval status.'),

  // ── Bosnia and Herzegovina ────────────────────────────────────────────────
  Place(continent:'Europe', name:'Sarajevo', modernCountry:'Bosnia and Herzegovina', iso3:'BIH', state:'Sarajevo Canton',
    historicalContext:'Site of 1914 assassination; Ottoman administrative centre for the Balkans.',
    colonizer:'Ottoman Empire, Austro-Hungarian Empire', nativeTribes:'South Slavs', romanizedNative:'Sarajevo'),

  // ── Bulgaria ─────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Sofia', modernCountry:'Bulgaria', iso3:'BGR', state:'Sofia City Province',
    historicalContext:'Capital of Bulgaria; under Ottoman rule 1382–1878.',
    colonizer:'Byzantine Empire, Ottoman Empire', nativeTribes:'Thracians', romanizedNative:'Serdica'),
  Place(continent:'Europe', name:'Plovdiv', modernCountry:'Bulgaria', iso3:'BGR', state:'Plovdiv Province',
    historicalContext:'One of Europe\'s oldest continuously inhabited cities; Thracian then Roman.',
    colonizer:'Roman Empire, Ottoman Empire', nativeTribes:'Thracians', romanizedNative:'Philippopolis'),

  // ── Croatia ──────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Zagreb', modernCountry:'Croatia', iso3:'HRV', state:'Zagreb County',
    historicalContext:'Capital of Croatia; part of Habsburg Empire; important Catholic records hub.',
    colonizer:'Habsburg Empire, Austro-Hungarian Empire', nativeTribes:'South Slavs', romanizedNative:'Agram'),
  Place(continent:'Europe', name:'Split', modernCountry:'Croatia', iso3:'HRV', state:'Split-Dalmatia County',
    historicalContext:'Built inside Diocletian\'s Palace; Dalmatia long under Venetian control.',
    colonizer:'Roman Empire, Venetian Republic', nativeTribes:'Illyrians', romanizedNative:'Spalato'),
  Place(continent:'Europe', name:'Dubrovnik', modernCountry:'Croatia', iso3:'HRV', state:'Dubrovnik-Neretva County',
    historicalContext:'The independent Republic of Ragusa 1358–1808; major maritime trading power.',
    colonizer:'Venetian Republic (briefly)', romanizedNative:'Ragusa'),

  // ── Czech Republic ───────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Prague', modernCountry:'Czech Republic', iso3:'CZE', state:'Prague',
    historicalContext:'Capital of Bohemia and the Holy Roman Empire; Jewish quarter among Europe\'s oldest.',
    colonizer:'Habsburg Empire', nativeTribes:'Celtic Boii, Slavs', romanizedNative:'Praha'),
  Place(continent:'Europe', name:'Brno', modernCountry:'Czech Republic', iso3:'CZE', state:'South Moravian Region',
    historicalContext:'Moravia\'s capital; heavy German-speaking population before 1945 expulsion.',
    colonizer:'Habsburg Empire', romanizedNative:'Brünn'),
  Place(continent:'Europe', name:'Ostrava', modernCountry:'Czech Republic', iso3:'CZE', state:'Moravian-Silesian Region',
    historicalContext:'Silesian mining city; disputed between Austria and Prussia historically.'),

  // ── Denmark ──────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Copenhagen', modernCountry:'Denmark', iso3:'DNK', state:'Capital Region',
    historicalContext:'Capital of Denmark and formerly of a Scandinavian empire including Norway and Iceland.',
    nativeTribes:'Norse/Danish Vikings', romanizedNative:'Køpmannahavn'),
  Place(continent:'Europe', name:'Aarhus', modernCountry:'Denmark', iso3:'DNK', state:'Central Denmark Region',
    historicalContext:'Denmark\'s second city; Viking settlement and medieval bishopric.',
    nativeTribes:'Norse Vikings'),

  // ── Estonia ──────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Tallinn', modernCountry:'Estonia', iso3:'EST', state:'Harju County',
    historicalContext:'Hanseatic League member; occupied by Denmark, Sweden, and Russia for centuries.',
    colonizer:'Denmark, Teutonic Knights, Sweden, Russian Empire', nativeTribes:'Estonians (Finno-Ugric)', romanizedNative:'Reval'),
  Place(continent:'Europe', name:'Tartu', modernCountry:'Estonia', iso3:'EST', state:'Tartu County',
    historicalContext:'University city; major centre of Estonian national awakening.',
    colonizer:'Teutonic Knights, Sweden, Russian Empire', romanizedNative:'Dorpat'),

  // ── Finland ──────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Helsinki', modernCountry:'Finland', iso3:'FIN', state:'Uusimaa',
    historicalContext:'Capital; founded by Sweden in 1550, ceded to Russia in 1809, independent 1917.',
    colonizer:'Swedish Empire, Russian Empire', nativeTribes:'Finns (Finno-Ugric)', romanizedNative:'Helsingfors'),
  Place(continent:'Europe', name:'Turku', modernCountry:'Finland', iso3:'FIN', state:'Southwest Finland',
    historicalContext:'Oldest city in Finland; former capital under Swedish rule.',
    colonizer:'Swedish Empire', romanizedNative:'Åbo'),
  Place(continent:'Europe', name:'Tampere', modernCountry:'Finland', iso3:'FIN', state:'Pirkanmaa',
    historicalContext:'Major industrial centre; key city in 1918 Finnish Civil War.',
    colonizer:'Swedish Empire, Russian Empire'),
  Place(continent:'Europe', name:'Oulu', modernCountry:'Finland', iso3:'FIN', state:'North Ostrobothnia',
    historicalContext:'Northern Finnish city; important for Sámi and Finnish genealogical records.'),

  // ── France ───────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Paris', modernCountry:'France', iso3:'FRA', state:'Île-de-France', subState:'Seine',
    historicalContext:'Capital of France; royal seat since Capetian dynasty; major civil records archive.',
    colonizer:'Roman Empire, Franks', nativeTribes:'Parisii (Gauls)', romanizedNative:'Lutetia'),
  Place(continent:'Europe', name:'Lyon', modernCountry:'France', iso3:'FRA', state:'Auvergne-Rhône-Alpes', subState:'Métropole de Lyon',
    historicalContext:'Roman capital of Gaul (Lugdunum); major silk trade and banking city.',
    colonizer:'Roman Empire', nativeTribes:'Gallic Celts', romanizedNative:'Lugdunum'),
  Place(continent:'Europe', name:'Marseille', modernCountry:'France', iso3:'FRA', state:'Provence-Alpes-Côte d\'Azur', subState:'Bouches-du-Rhône',
    historicalContext:'Greece\'s oldest colony in France (Massalia); major Mediterranean port.',
    colonizer:'Greek colonists, Roman Empire', nativeTribes:'Ligurian Celts', romanizedNative:'Massalia'),
  Place(continent:'Europe', name:'Bordeaux', modernCountry:'France', iso3:'FRA', state:'Nouvelle-Aquitaine', subState:'Gironde',
    historicalContext:'English Aquitaine for 300 years (1154–1453); wine trade hub.',
    colonizer:'Roman Empire, English Crown', nativeTribes:'Bituriges Vivisci', romanizedNative:'Burdigala'),
  Place(continent:'Europe', name:'Strasbourg', modernCountry:'France', iso3:'FRA', state:'Grand Est', subState:'Bas-Rhin',
    historicalContext:'Contested between France and Germany; Alsace-Lorraine records are bicultural.',
    colonizer:'Holy Roman Empire, German Empire', nativeTribes:'Germanic Alemanni', romanizedNative:'Argentoratum'),
  Place(continent:'Europe', name:'Nice', modernCountry:'France', iso3:'FRA', state:'Provence-Alpes-Côte d\'Azur', subState:'Alpes-Maritimes',
    historicalContext:'Part of the Duchy of Savoy until 1860; Italian-speaking genealogical records exist.',
    colonizer:'Roman Empire, Duchy of Savoy', nativeTribes:'Ligurian Celts', romanizedNative:'Nizza'),
  Place(continent:'Europe', name:'Nantes', modernCountry:'France', iso3:'FRA', state:'Pays de la Loire', subState:'Loire-Atlantique',
    historicalContext:'Edict of Nantes 1598 signed here; major slave-trade port in 18th century.'),
  Place(continent:'Europe', name:'Toulouse', modernCountry:'France', iso3:'FRA', state:'Occitanie', subState:'Haute-Garonne',
    historicalContext:'Capital of Visigoth kingdom; Cathar stronghold; Occitan language homeland.'),

  // ── Germany ──────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Berlin', modernCountry:'Germany', iso3:'DEU', state:'Berlin',
    historicalContext:'Prussian capital then German Empire capital; reunified 1990; major archive hub.',
    colonizer:'Holy Roman Empire, Prussia', nativeTribes:'Slavic Hevelli', romanizedNative:'Cölln'),
  Place(continent:'Europe', name:'Munich', modernCountry:'Germany', iso3:'DEU', state:'Bavaria', subState:'Upper Bavaria', county:'Munich',
    historicalContext:'Capital of the Kingdom of Bavaria; major Catholic records repository.',
    colonizer:'Roman Empire, Wittelsbach Duchy', nativeTribes:'Baiuvarii (Germanic)', romanizedNative:'München'),
  Place(continent:'Europe', name:'Hamburg', modernCountry:'Germany', iso3:'DEU', state:'Hamburg',
    historicalContext:'Free Imperial City and Hanseatic League member; major emigration port to Americas.',
    colonizer:'Holy Roman Empire', nativeTribes:'Saxons', romanizedNative:'Hammaburg'),
  Place(continent:'Europe', name:'Frankfurt', modernCountry:'Germany', iso3:'DEU', state:'Hesse', county:'Frankfurt am Main',
    historicalContext:'Holy Roman Empire coronation city; major banking and commercial centre.',
    colonizer:'Roman Empire, Holy Roman Empire', nativeTribes:'Franks', romanizedNative:'Franconoford'),
  Place(continent:'Europe', name:'Cologne', modernCountry:'Germany', iso3:'DEU', state:'North Rhine-Westphalia', county:'Cologne',
    historicalContext:'Roman colonia; major medieval archbishopric; Rhine trade hub.',
    colonizer:'Roman Empire', nativeTribes:'Ubii (Germanic)', romanizedNative:'Colonia Agrippina'),
  Place(continent:'Europe', name:'Dresden', modernCountry:'Germany', iso3:'DEU', state:'Saxony', county:'Dresden',
    historicalContext:'Capital of Electoral Saxony; heavily bombed 1945; baroque architecture.',
    colonizer:'Holy Roman Empire, Kingdom of Saxony', nativeTribes:'Slavic Sorbians'),
  Place(continent:'Europe', name:'Leipzig', modernCountry:'Germany', iso3:'DEU', state:'Saxony', county:'Leipzig',
    historicalContext:'Major trade fair city; Battle of Nations 1813; Bach was Cantor here.'),
  Place(continent:'Europe', name:'Nuremberg', modernCountry:'Germany', iso3:'DEU', state:'Bavaria', subState:'Middle Franconia', county:'Nuremberg',
    historicalContext:'Imperial free city; site of Nazi war crimes trials.',
    colonizer:'Holy Roman Empire', romanizedNative:'Nürnberg'),
  Place(continent:'Europe', name:'Königsberg', modernCountry:'Germany', iso3:'DEU', state:'East Prussia',
    historicalContext:'Former Prussian capital; now Kaliningrad, Russia. Many German genealogical records.',
    colonizer:'Teutonic Knights, Prussia', nativeTribes:'Baltic Prussians', romanizedNative:'Kaliningrad',
    validTo:'1946-04-04T00:00:00.000Z'),

  // ── Greece ───────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Athens', modernCountry:'Greece', iso3:'GRC', state:'Attica',
    historicalContext:'Birthplace of democracy; under Ottoman rule 1458–1833.',
    colonizer:'Roman Empire, Byzantine Empire, Ottoman Empire', nativeTribes:'Ancient Athenians', romanizedNative:'Athinai'),
  Place(continent:'Europe', name:'Thessaloniki', modernCountry:'Greece', iso3:'GRC', state:'Central Macedonia',
    historicalContext:'Major Byzantine city; large Sephardic Jewish community until WWII.',
    colonizer:'Roman Empire, Byzantine Empire, Ottoman Empire', nativeTribes:'Macedonians', romanizedNative:'Selanik'),

  // ── Hungary ──────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Budapest', modernCountry:'Hungary', iso3:'HUN', state:'Budapest',
    historicalContext:'Union of Buda and Pest in 1873; capital of Kingdom of Hungary in Austro-Hungarian Empire.',
    colonizer:'Ottoman Empire, Habsburg Empire', nativeTribes:'Magyars, Avars, Celts', romanizedNative:'Aquincum'),
  Place(continent:'Europe', name:'Debrecen', modernCountry:'Hungary', iso3:'HUN', state:'Hajdú-Bihar County',
    historicalContext:'Protestant "Calvinist Rome" of Hungary; briefly capital in 1849 revolution.'),

  // ── Iceland ──────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Reykjavik', modernCountry:'Iceland', iso3:'ISL', state:'Capital Region',
    historicalContext:'World\'s northernmost capital; settled by Norse Vikings ~870 AD.',
    nativeTribes:'Norse settlers (no indigenous population)', romanizedNative:'Reykjavík'),

  // ── Ireland ──────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Dublin', modernCountry:'Ireland', iso3:'IRL', state:'Leinster', county:'Dublin',
    historicalContext:'Founded by Vikings; capital of British Ireland until 1922; major genealogy hub.',
    colonizer:'Norse Vikings, Anglo-Norman, British Empire', nativeTribes:'Gaels', romanizedNative:'Dubh Linn'),
  Place(continent:'Europe', name:'Cork', modernCountry:'Ireland', iso3:'IRL', state:'Munster', county:'Cork',
    historicalContext:'Second city of Ireland; major port for emigration during the Famine.',
    colonizer:'Norse Vikings, Anglo-Norman, British Empire', nativeTribes:'Gaels'),
  Place(continent:'Europe', name:'Galway', modernCountry:'Ireland', iso3:'IRL', state:'Connacht', county:'Galway',
    historicalContext:'Western gateway to Connaught; Gaeltacht Irish-speaking region nearby.',
    colonizer:'Anglo-Norman, British Empire', nativeTribes:'Gaels'),
  Place(continent:'Europe', name:'Limerick', modernCountry:'Ireland', iso3:'IRL', state:'Munster', county:'Limerick',
    historicalContext:'Viking-founded city on the Shannon; Treaty of Limerick 1691.',
    colonizer:'Norse Vikings, Anglo-Norman, British Empire', nativeTribes:'Gaels'),

  // ── Italy ────────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Rome', modernCountry:'Italy', iso3:'ITA', state:'Lazio', county:'Rome',
    historicalContext:'Centre of the Roman Empire and Catholic Church; Vatican records vital for genealogy.',
    colonizer:'Roman Republic (expanded)', nativeTribes:'Latins, Sabines, Etruscans', romanizedNative:'Roma'),
  Place(continent:'Europe', name:'Milan', modernCountry:'Italy', iso3:'ITA', state:'Lombardy', county:'Milan',
    historicalContext:'Capital of the Duchy of Milan; under Spanish and Austrian rule before unification.',
    colonizer:'Roman Empire, Spanish Crown, Habsburg Austria', nativeTribes:'Celtic Insubres', romanizedNative:'Mediolanum'),
  Place(continent:'Europe', name:'Naples', modernCountry:'Italy', iso3:'ITA', state:'Campania', county:'Naples',
    historicalContext:'Capital of Kingdom of the Two Sicilies; major emigration source to Americas.',
    colonizer:'Greek colonists, Roman Empire, Spanish Crown', nativeTribes:'Oscans', romanizedNative:'Neapolis'),
  Place(continent:'Europe', name:'Venice', modernCountry:'Italy', iso3:'ITA', state:'Veneto', county:'Venice',
    historicalContext:'Republic of Venice lasted 1000+ years; major Mediterranean trading power.',
    colonizer:'Roman Empire (predecessor)', nativeTribes:'Veneti', romanizedNative:'Venetia'),
  Place(continent:'Europe', name:'Florence', modernCountry:'Italy', iso3:'ITA', state:'Tuscany', county:'Florence',
    historicalContext:'Medici seat; cradle of the Renaissance; Tuscany records among Italy\'s best preserved.',
    colonizer:'Roman Empire', nativeTribes:'Etruscans', romanizedNative:'Florentia'),
  Place(continent:'Europe', name:'Turin', modernCountry:'Italy', iso3:'ITA', state:'Piedmont', county:'Turin',
    historicalContext:'Capital of Kingdom of Sardinia; drove Italian unification in 1861.',
    colonizer:'Roman Empire, Duchy of Savoy', nativeTribes:'Ligurian Celts', romanizedNative:'Augusta Taurinorum'),
  Place(continent:'Europe', name:'Palermo', modernCountry:'Italy', iso3:'ITA', state:'Sicily', county:'Palermo',
    historicalContext:'Norman Kingdom of Sicily capital; Arab, Norman, and Spanish influences.',
    colonizer:'Phoenicians, Greeks, Romans, Arabs, Normans, Spanish', nativeTribes:'Sicani', romanizedNative:'Panormus'),
  Place(continent:'Europe', name:'Genoa', modernCountry:'Italy', iso3:'ITA', state:'Liguria', county:'Genoa',
    historicalContext:'Republic of Genoa rivalled Venice; founded Columbus and major banking dynasties.',
    colonizer:'Roman Empire', nativeTribes:'Ligurians', romanizedNative:'Genua'),
  Place(continent:'Europe', name:'Bologna', modernCountry:'Italy', iso3:'ITA', state:'Emilia-Romagna', county:'Bologna',
    historicalContext:'Home of world\'s oldest university (1088); Papal States territory.',
    colonizer:'Roman Empire, Papal States', nativeTribes:'Celtic Boii', romanizedNative:'Bononia'),

  // ── Latvia ───────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Riga', modernCountry:'Latvia', iso3:'LVA', state:'Riga Region',
    historicalContext:'Hanseatic city; under German, Swedish, Russian, and Soviet rule.',
    colonizer:'Teutonic Knights, Sweden, Russian Empire', nativeTribes:'Latvians (Baltic)', romanizedNative:'Riga'),

  // ── Liechtenstein ────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Vaduz', modernCountry:'Liechtenstein', iso3:'LIE', state:'Vaduz',
    historicalContext:'Capital of the Principality of Liechtenstein since 1719.',
    colonizer:'Holy Roman Empire, Habsburg Austria'),

  // ── Lithuania ────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Vilnius', modernCountry:'Lithuania', iso3:'LTU', state:'Vilnius County',
    historicalContext:'Capital of the Grand Duchy of Lithuania; significant Jewish (Litvak) community.',
    colonizer:'Polish-Lithuanian Commonwealth, Russian Empire', nativeTribes:'Lithuanians (Baltic)', romanizedNative:'Wilno / Wilna'),
  Place(continent:'Europe', name:'Kaunas', modernCountry:'Lithuania', iso3:'LTU', state:'Kaunas County',
    historicalContext:'Temporary capital during interwar period when Vilnius was under Polish control.',
    colonizer:'Russian Empire', romanizedNative:'Kovno'),

  // ── Luxembourg ───────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Luxembourg City', modernCountry:'Luxembourg', iso3:'LUX', state:'Luxembourg District',
    historicalContext:'Capital of Grand Duchy; fortress city passed between Habsburg, French, and Prussian control.',
    colonizer:'Habsburg Empire, France', nativeTribes:'Celtic Treveri'),

  // ── Malta ─────────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Valletta', modernCountry:'Malta', iso3:'MLT', state:'South Eastern Region',
    historicalContext:'Capital founded by Knights of St. John 1566; British colony 1800–1964.',
    colonizer:'Knights of St. John, British Empire', nativeTribes:'Phoenicians, Romans', romanizedNative:'Valletta'),

  // ── Moldova ──────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Chișinău', modernCountry:'Moldova', iso3:'MDA', state:'Chișinău Municipality',
    historicalContext:'Capital of Moldovan SSR; formerly part of Romania; large Jewish community historically.',
    colonizer:'Ottoman Empire, Russian Empire', romanizedNative:'Kishinev'),

  // ── Monaco ───────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Monaco', modernCountry:'Monaco', iso3:'MCO', state:'Monaco',
    historicalContext:'Principality ruled by Grimaldi family since 1297.',
    colonizer:'Genoese Republic'),

  // ── Montenegro ───────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Podgorica', modernCountry:'Montenegro', iso3:'MNE', state:'Podgorica Municipality',
    historicalContext:'Capital of Montenegro; Ottoman and Yugoslav periods evident in records.',
    colonizer:'Ottoman Empire', romanizedNative:'Titograd'),

  // ── Netherlands ──────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Amsterdam', modernCountry:'Netherlands', iso3:'NLD', state:'North Holland', county:'Amsterdam',
    historicalContext:'Capital of Dutch Republic; major colonial and trade empire base.',
    colonizer:'Spanish Netherlands (resisted)', nativeTribes:'Frisians, Batavians', romanizedNative:'Amstelodamum'),
  Place(continent:'Europe', name:'The Hague', modernCountry:'Netherlands', iso3:'NLD', state:'South Holland',
    historicalContext:'Seat of Dutch government and parliament; home of International Court of Justice.'),
  Place(continent:'Europe', name:'Rotterdam', modernCountry:'Netherlands', iso3:'NLD', state:'South Holland', county:'Rotterdam',
    historicalContext:'World\'s busiest port for much of 20th century; emigration gateway to Americas.'),
  Place(continent:'Europe', name:'Utrecht', modernCountry:'Netherlands', iso3:'NLD', state:'Utrecht',
    historicalContext:'Treaty of Utrecht 1713; historic bishopric and university city.'),

  // ── North Macedonia ──────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Skopje', modernCountry:'North Macedonia', iso3:'MKD', state:'Skopje Region',
    historicalContext:'Capital; under Ottoman rule for 500 years; birthplace of Mother Teresa.',
    colonizer:'Byzantine Empire, Ottoman Empire', nativeTribes:'Macedonians', romanizedNative:'Scupi'),

  // ── Norway ───────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Oslo', modernCountry:'Norway', iso3:'NOR', state:'Oslo',
    historicalContext:'Capital of Norway; in union with Denmark until 1814, then Sweden until 1905.',
    nativeTribes:'Norse Vikings, Sámi (north)', romanizedNative:'Christiania / Kristiania'),
  Place(continent:'Europe', name:'Bergen', modernCountry:'Norway', iso3:'NOR', state:'Vestland',
    historicalContext:'Former capital; Hanseatic League German quarter; gateway to Norwegian fjords.',
    colonizer:'Hanseatic League (merchant quarter)', nativeTribes:'Norse Vikings'),

  // ── Poland ───────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Warsaw', modernCountry:'Poland', iso3:'POL', state:'Masovian Voivodeship', county:'Warsaw',
    historicalContext:'Capital of Poland; partitioned between Prussia, Russia, Austria 1795–1918; WW2 ghetto.',
    colonizer:'Prussia, Russian Empire, Nazi Germany', nativeTribes:'Mazovian Poles', romanizedNative:'Warszawa'),
  Place(continent:'Europe', name:'Kraków', modernCountry:'Poland', iso3:'POL', state:'Lesser Poland Voivodeship', county:'Kraków',
    historicalContext:'Medieval capital of Poland; Wawel Castle; Jewish Kazimierz district.',
    colonizer:'Habsburg Austria (partition era)', nativeTribes:'Vistulans', romanizedNative:'Cracovia'),
  Place(continent:'Europe', name:'Gdańsk', modernCountry:'Poland', iso3:'POL', state:'Pomeranian Voivodeship', county:'Gdańsk',
    historicalContext:'Free City of Danzig 1919–1939; German majority; WW2 began here.',
    colonizer:'Teutonic Knights, Prussia, Nazi Germany', nativeTribes:'Pomeranians', romanizedNative:'Danzig'),
  Place(continent:'Europe', name:'Wrocław', modernCountry:'Poland', iso3:'POL', state:'Lower Silesian Voivodeship', county:'Wrocław',
    historicalContext:'Historically German Breslau; Silesia transferred to Poland in 1945.',
    colonizer:'Habsburg Austria, Kingdom of Prussia', nativeTribes:'Silesian Slavs', romanizedNative:'Breslau'),
  Place(continent:'Europe', name:'Łódź', modernCountry:'Poland', iso3:'POL', state:'Łódź Voivodeship',
    historicalContext:'Major textile city; large Jewish community; Łódź Ghetto in WWII.',
    colonizer:'Russian Empire (partition era)'),
  Place(continent:'Europe', name:'Lwów', modernCountry:'Poland', iso3:'POL', state:'Lwów Oblast',
    historicalContext:'Now Lviv, Ukraine; historically Polish, Austrian, and Ukrainian; shifted post-WWII.',
    colonizer:'Habsburg Austria', nativeTribes:'Ruthenians', romanizedNative:'Lemberg / Lwów',
    validTo:'1945-01-01T00:00:00.000Z'),

  // ── Portugal ─────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Lisbon', modernCountry:'Portugal', iso3:'PRT', state:'Lisbon District',
    historicalContext:'Capital of global Portuguese Empire; 1755 earthquake destroyed most records.',
    colonizer:'Roman Empire, Moorish Caliphate', nativeTribes:'Lusitanians', romanizedNative:'Olisipo'),
  Place(continent:'Europe', name:'Porto', modernCountry:'Portugal', iso3:'PRT', state:'Porto District',
    historicalContext:'Portugal\'s second city; origin of the country\'s name; port wine trade.',
    colonizer:'Roman Empire, Suebi Kingdom', nativeTribes:'Callaeci', romanizedNative:'Portus Cale'),

  // ── Romania ──────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Bucharest', modernCountry:'Romania', iso3:'ROU', state:'Ilfov County',
    historicalContext:'Capital of Romania; former Ottoman vassal state.',
    colonizer:'Ottoman Empire, Russian Empire', nativeTribes:'Dacians', romanizedNative:'București'),
  Place(continent:'Europe', name:'Cluj-Napoca', modernCountry:'Romania', iso3:'ROU', state:'Cluj County',
    historicalContext:'Historic Transylvanian city; under Hungarian and Austrian rule for centuries.',
    colonizer:'Habsburg Empire, Austro-Hungarian Empire', nativeTribes:'Dacians', romanizedNative:'Kolozsvár / Klausenburg'),

  // ── Russia ───────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Moscow', modernCountry:'Russia', iso3:'RUS', state:'Moscow Oblast',
    historicalContext:'Capital of the Tsardom of Russia and Soviet Union; vast genealogical archives.',
    colonizer:'Mongol Empire (subjugated)', nativeTribes:'Eastern Slavs', romanizedNative:'Moskva'),
  Place(continent:'Europe', name:'Saint Petersburg', modernCountry:'Russia', iso3:'RUS', state:'Leningrad Oblast',
    historicalContext:'Founded 1703 by Peter the Great; renamed Petrograd 1914, Leningrad 1924, reverted 1991.',
    nativeTribes:'Ingrian Finns', romanizedNative:'Petrograd / Leningrad'),
  Place(continent:'Europe', name:'Novosibirsk', modernCountry:'Russia', iso3:'RUS', state:'Novosibirsk Oblast',
    historicalContext:'Siberia\'s largest city; founded 1893 on Trans-Siberian Railway route.'),
  Place(continent:'Europe', name:'Yekaterinburg', modernCountry:'Russia', iso3:'RUS', state:'Sverdlovsk Oblast',
    historicalContext:'Site of Romanov family execution 1918; Ural region industrial centre.',
    romanizedNative:'Sverdlovsk (Soviet era)'),
  Place(continent:'Europe', name:'Kazan', modernCountry:'Russia', iso3:'RUS', state:'Tatarstan Republic',
    historicalContext:'Capital of Tatar Khanate; conquered by Ivan the Terrible 1552; Tatar cultural centre.',
    nativeTribes:'Tatars', romanizedNative:'Qazan'),
  Place(continent:'Europe', name:'Kaliningrad', modernCountry:'Russia', iso3:'RUS', state:'Kaliningrad Oblast',
    historicalContext:'Formerly Königsberg, Prussia; transferred to USSR after WWII; German records remain.',
    colonizer:'Teutonic Knights, Kingdom of Prussia', nativeTribes:'Baltic Old Prussians', romanizedNative:'Königsberg'),

  // ── San Marino ───────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'San Marino', modernCountry:'San Marino', iso3:'SMR', state:'San Marino',
    historicalContext:'World\'s oldest republic, traditionally founded 301 AD.',
    colonizer:'Papal States (surrounded by)'),

  // ── Serbia ───────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Belgrade', modernCountry:'Serbia', iso3:'SRB', state:'Belgrade District',
    historicalContext:'Capital of Serbia; Ottoman rule 1521–1867; Yugoslavia capital 1918–1992.',
    colonizer:'Ottoman Empire, Austro-Hungarian Empire', nativeTribes:'Scordisci (Celtic-Illyrian)', romanizedNative:'Singidunum'),
  Place(continent:'Europe', name:'Novi Sad', modernCountry:'Serbia', iso3:'SRB', state:'South Bačka District',
    historicalContext:'Capital of Vojvodina; large Hungarian and German minority historically.',
    colonizer:'Ottoman Empire, Habsburg Empire'),

  // ── Slovakia ─────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Bratislava', modernCountry:'Slovakia', iso3:'SVK', state:'Bratislava Region',
    historicalContext:'Capital of Kingdom of Hungary 1536–1783 when Buda was under Ottoman rule.',
    colonizer:'Habsburg Empire', nativeTribes:'Celtic Boii', romanizedNative:'Pressburg / Pozsony'),

  // ── Slovenia ─────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Ljubljana', modernCountry:'Slovenia', iso3:'SVN', state:'Ljubljana Urban Municipality',
    historicalContext:'Capital of Slovenia; long part of Habsburg Empire as Laibach.',
    colonizer:'Roman Empire, Habsburg Empire', nativeTribes:'Illyrians', romanizedNative:'Laibach'),

  // ── Spain ────────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Madrid', modernCountry:'Spain', iso3:'ESP', state:'Community of Madrid',
    historicalContext:'Capital of the Spanish Empire; centre of colonial administration for the Americas.',
    colonizer:'Moorish Caliphate, Castile', nativeTribes:'Carpetani (Iberian)', romanizedNative:'Matrice'),
  Place(continent:'Europe', name:'Barcelona', modernCountry:'Spain', iso3:'ESP', state:'Catalonia', county:'Barcelonès',
    historicalContext:'Capital of Catalonia; Roman colony; centre of Catalan language and culture.',
    colonizer:'Roman Empire, Moorish Caliphate', nativeTribes:'Laietani (Iberian)', romanizedNative:'Barcino'),
  Place(continent:'Europe', name:'Seville', modernCountry:'Spain', iso3:'ESP', state:'Andalusia', county:'Seville',
    historicalContext:'Gateway for Spanish colonial trade with the Americas; Columbus sailed from here.',
    colonizer:'Roman Empire, Moorish Caliphate', nativeTribes:'Turdetani', romanizedNative:'Hispalis'),
  Place(continent:'Europe', name:'Valencia', modernCountry:'Spain', iso3:'ESP', state:'Valencian Community', county:'Valencia',
    historicalContext:'Kingdom of Valencia 1238–1707; major Mediterranean port.',
    colonizer:'Roman Empire, Moorish Caliphate', nativeTribes:'Edetani (Iberian)', romanizedNative:'Valentia'),
  Place(continent:'Europe', name:'Granada', modernCountry:'Spain', iso3:'ESP', state:'Andalusia', county:'Granada',
    historicalContext:'Last Moorish kingdom in Iberia; fell to Castile 1492; Alhambra palace.',
    colonizer:'Moorish Caliphate', nativeTribes:'Bastetani (Iberian)', romanizedNative:'Garnata'),
  Place(continent:'Europe', name:'Bilbao', modernCountry:'Spain', iso3:'ESP', state:'Basque Country', county:'Biscay',
    historicalContext:'Basque Country industrial centre; Basque language (Euskara) preserved here.',
    nativeTribes:'Basques (pre-Indo-European)', romanizedNative:'Bilbo'),

  // ── Sweden ───────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Stockholm', modernCountry:'Sweden', iso3:'SWE', state:'Stockholm County',
    historicalContext:'Capital of Sweden and formerly of the Swedish Empire; Scandinavia\'s largest city.',
    nativeTribes:'Norse Svear', romanizedNative:'Stockholm'),
  Place(continent:'Europe', name:'Gothenburg', modernCountry:'Sweden', iso3:'SWE', state:'Västra Götaland County',
    historicalContext:'Sweden\'s second city; major emigration port — millions left for America via here.',
    nativeTribes:'Norse Geats', romanizedNative:'Göteborg'),
  Place(continent:'Europe', name:'Malmö', modernCountry:'Sweden', iso3:'SWE', state:'Skåne County',
    historicalContext:'Part of Denmark until 1658 when Scania was ceded to Sweden.',
    nativeTribes:'Norse Danes/Swedes'),

  // ── Switzerland ──────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Bern', modernCountry:'Switzerland', iso3:'CHE', state:'Canton of Bern',
    historicalContext:'Federal capital of Switzerland; founded 1191 by Dukes of Zähringen.',
    colonizer:'Holy Roman Empire', nativeTribes:'Celtic Helvetii'),
  Place(continent:'Europe', name:'Zurich', modernCountry:'Switzerland', iso3:'CHE', state:'Canton of Zurich',
    historicalContext:'Largest Swiss city; Calvin\'s Reformation base; major financial centre.',
    colonizer:'Roman Empire, Habsburg Austria', nativeTribes:'Celtic Helvetii', romanizedNative:'Turicum'),
  Place(continent:'Europe', name:'Geneva', modernCountry:'Switzerland', iso3:'CHE', state:'Canton of Geneva',
    historicalContext:'John Calvin\'s city; seat of international organisations; Huguenot refugee hub.',
    colonizer:'Roman Empire, Duchy of Savoy', nativeTribes:'Celtic Allobroges', romanizedNative:'Genava'),

  // ── Ukraine ──────────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Kyiv', modernCountry:'Ukraine', iso3:'UKR', state:'Kyiv Oblast',
    historicalContext:'Cradle of Eastern Slavic civilization; Kievan Rus capital; under Polish and Russian rule.',
    colonizer:'Mongol Empire, Polish-Lithuanian Commonwealth, Russian Empire', nativeTribes:'Eastern Slavs', romanizedNative:'Kiev'),
  Place(continent:'Europe', name:'Lviv', modernCountry:'Ukraine', iso3:'UKR', state:'Lviv Oblast',
    historicalContext:'Formerly Polish Lwów and Austrian Lemberg; multicultural city with Polish/Ukrainian/Jewish roots.',
    colonizer:'Polish Kingdom, Habsburg Austria', nativeTribes:'Ruthenians', romanizedNative:'Lemberg / Lwów'),
  Place(continent:'Europe', name:'Odessa', modernCountry:'Ukraine', iso3:'UKR', state:'Odessa Oblast',
    historicalContext:'Black Sea port founded 1794 by Russia; major Jewish community (Odessa pogrom).',
    colonizer:'Ottoman Empire, Russian Empire', nativeTribes:'Pontic Greeks, Tatars'),
  Place(continent:'Europe', name:'Kharkiv', modernCountry:'Ukraine', iso3:'UKR', state:'Kharkiv Oblast',
    historicalContext:'First capital of Soviet Ukraine 1917–1934; major industrial centre.',
    colonizer:'Russian Empire'),

  // ── United Kingdom ───────────────────────────────────────────────────────
  Place(continent:'Europe', name:'London', modernCountry:'United Kingdom', iso3:'GBR', state:'England', subState:'Greater London', county:'City of London',
    historicalContext:'Capital of Great Britain and its global Empire; founded by Romans as Londinium.',
    colonizer:'Roman Empire, Anglo-Saxons, Normans', nativeTribes:'Celtic Britons', romanizedNative:'Londinium'),
  Place(continent:'Europe', name:'Edinburgh', modernCountry:'United Kingdom', iso3:'GBR', state:'Scotland', county:'City of Edinburgh',
    historicalContext:'Capital of Scotland; seat of Stuart monarchy; Scottish records held at New Register House.',
    colonizer:'Roman Empire (frontier), Norman', nativeTribes:'Picts, Gaels', romanizedNative:'Dunedin'),
  Place(continent:'Europe', name:'Manchester', modernCountry:'United Kingdom', iso3:'GBR', state:'England', subState:'Greater Manchester', county:'Manchester',
    historicalContext:'Birthplace of the Industrial Revolution; major Irish immigrant destination.',
    colonizer:'Roman Empire', nativeTribes:'Celtic Brigantes', romanizedNative:'Mamucium'),
  Place(continent:'Europe', name:'Birmingham', modernCountry:'United Kingdom', iso3:'GBR', state:'England', subState:'West Midlands', county:'Birmingham',
    historicalContext:'Industrial heartland; "city of a thousand trades"; centre of metal manufacturing.',
    colonizer:'Anglo-Saxons', nativeTribes:'Celtic Mercians'),
  Place(continent:'Europe', name:'Liverpool', modernCountry:'United Kingdom', iso3:'GBR', state:'England', subState:'Merseyside', county:'Liverpool',
    historicalContext:'Major slave-trade port; largest Irish immigrant community outside Ireland.',
    colonizer:'Norman', nativeTribes:'Celtic Brigantes'),
  Place(continent:'Europe', name:'Glasgow', modernCountry:'United Kingdom', iso3:'GBR', state:'Scotland', county:'Glasgow City',
    historicalContext:'Scotland\'s largest city; industrial powerhouse; Highland and Irish migration hub.',
    nativeTribes:'Picts, Britons of Strathclyde'),
  Place(continent:'Europe', name:'Cardiff', modernCountry:'United Kingdom', iso3:'GBR', state:'Wales', county:'Cardiff',
    historicalContext:'Capital of Wales; coal export hub; Welsh-language records from 18th century.',
    colonizer:'Roman Empire, Norman, English Crown', nativeTribes:'Celtic Silures', romanizedNative:'Caerdydd'),
  Place(continent:'Europe', name:'Belfast', modernCountry:'United Kingdom', iso3:'GBR', state:'Northern Ireland', county:'County Antrim / County Down',
    historicalContext:'Capital of Northern Ireland; linen and shipbuilding industries; Titanic built here.',
    colonizer:'Norman, English/Scottish plantation', nativeTribes:'Gaels'),
  Place(continent:'Europe', name:'York', modernCountry:'United Kingdom', iso3:'GBR', state:'England', subState:'North Yorkshire', county:'York',
    historicalContext:'Roman capital of Britannia; Viking Jorvik; medieval walled city.',
    colonizer:'Roman Empire, Norse Vikings, Normans', nativeTribes:'Celtic Brigantes', romanizedNative:'Eboracum'),

  // ── Vatican City ─────────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Vatican City', modernCountry:'Vatican City', iso3:'VAT', state:'Vatican City',
    historicalContext:'Seat of the Catholic Church; Vatican Archives contain centuries of genealogical records.',
    colonizer:'Papal States (historical predecessor)'),

  // ── Additional Austria ────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Linz', modernCountry:'Austria', iso3:'AUT', state:'Upper Austria',
    historicalContext:'Industrial city on the Danube; birthplace of Kepler; major Habsburg administrative centre.',
    colonizer:'Habsburg Dynasty', romanizedNative:'Linz'),
  Place(continent:'Europe', name:'Klagenfurt', modernCountry:'Austria', iso3:'AUT', state:'Carinthia',
    historicalContext:'Capital of Carinthia; historically contested between Austria and Yugoslavia.',
    colonizer:'Habsburg Dynasty'),
  Place(continent:'Europe', name:'St. Pölten', modernCountry:'Austria', iso3:'AUT', state:'Lower Austria',
    historicalContext:'Capital of Lower Austria; among Austria\'s oldest cities, Roman origins.',
    colonizer:'Roman Empire, Habsburg Dynasty', romanizedNative:'Aelium Cetium'),
  Place(continent:'Europe', name:'Bregenz', modernCountry:'Austria', iso3:'AUT', state:'Vorarlberg',
    historicalContext:'Capital of Vorarlberg; on Lake Constance; Celtic then Roman settlement.',
    colonizer:'Roman Empire', nativeTribes:'Celtic Brigantii', romanizedNative:'Brigantium'),

  // ── Additional Belarus ────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Vitebsk', modernCountry:'Belarus', iso3:'BLR', state:'Vitebsk Region',
    historicalContext:'Birthplace of Marc Chagall; historic Jewish community; passed between Muscovy, Poland, Russia.',
    colonizer:'Polish-Lithuanian Commonwealth, Russian Empire', romanizedNative:'Vitsebsk'),
  Place(continent:'Europe', name:'Mogilev', modernCountry:'Belarus', iso3:'BLR', state:'Mogilev Region',
    historicalContext:'Major city in eastern Belarus; tsarist-era administrative centre; significant Jewish population.',
    colonizer:'Polish-Lithuanian Commonwealth, Russian Empire', romanizedNative:'Mahilyow'),
  Place(continent:'Europe', name:'Pinsk', modernCountry:'Belarus', iso3:'BLR', state:'Brest Region',
    historicalContext:'Important historic Jewish city (shtetl); in the Pripyat Marshes region.',
    colonizer:'Polish-Lithuanian Commonwealth, Russian Empire', romanizedNative:'Pinsk'),

  // ── Additional Belgium ────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Bruges', modernCountry:'Belgium', iso3:'BEL', state:'West Flanders',
    historicalContext:'Medieval trade capital; well-preserved canal city; centre of Flemish Primitive art.',
    colonizer:'Spanish Netherlands', romanizedNative:'Brugge'),
  Place(continent:'Europe', name:'Leuven', modernCountry:'Belgium', iso3:'BEL', state:'Flemish Brabant',
    historicalContext:'Home of one of Europe\'s oldest universities (1425); centre of Belgian brewing.',
    colonizer:'Spanish Netherlands', romanizedNative:'Louvain'),
  Place(continent:'Europe', name:'Namur', modernCountry:'Belgium', iso3:'BEL', state:'Namur Province',
    historicalContext:'Walloon capital; strategically important fortress city at Meuse–Sambre confluence.',
    colonizer:'Spanish Netherlands'),

  // ── Additional Bulgaria ───────────────────────────────────────────────────
  Place(continent:'Europe', name:'Varna', modernCountry:'Bulgaria', iso3:'BGR', state:'Varna Province',
    historicalContext:'Black Sea port; ancient Odessos; major Bulgarian city since liberation from Ottomans.',
    colonizer:'Greek colonists, Roman Empire, Ottoman Empire', nativeTribes:'Thracians', romanizedNative:'Odessos'),
  Place(continent:'Europe', name:'Burgas', modernCountry:'Bulgaria', iso3:'BGR', state:'Burgas Province',
    historicalContext:'Black Sea port and industrial city; Ottoman trading post.',
    colonizer:'Ottoman Empire'),
  Place(continent:'Europe', name:'Rousse', modernCountry:'Bulgaria', iso3:'BGR', state:'Ruse Province',
    historicalContext:'Danube port city; Danubian principality capital; called "Little Vienna" for architecture.',
    colonizer:'Ottoman Empire', romanizedNative:'Ruse'),
  Place(continent:'Europe', name:'Stara Zagora', modernCountry:'Bulgaria', iso3:'BGR', state:'Stara Zagora Province',
    historicalContext:'Central Bulgarian city; ancient Beroe Augusta; Rose Valley records; agriculture hub.',
    colonizer:'Roman Empire, Ottoman Empire', nativeTribes:'Thracians', romanizedNative:'Augusta Traiana'),

  // ── Additional Croatia ────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Rijeka', modernCountry:'Croatia', iso3:'HRV', state:'Primorje-Gorski Kotar County',
    historicalContext:'Contested port between Italy and Yugoslavia after WWI; formerly Fiume.',
    colonizer:'Habsburg Empire, Italian Republic', nativeTribes:'Illyrians', romanizedNative:'Tarsatica'),
  Place(continent:'Europe', name:'Osijek', modernCountry:'Croatia', iso3:'HRV', state:'Osijek-Baranja County',
    historicalContext:'Major city in Slavonia; Roman Mursa; Ottoman then Habsburg.',
    colonizer:'Roman Empire, Ottoman Empire, Habsburg Empire', romanizedNative:'Mursa'),

  // ── Additional Czech Republic ─────────────────────────────────────────────
  Place(continent:'Europe', name:'Plzeň', modernCountry:'Czech Republic', iso3:'CZE', state:'Plzeň Region',
    historicalContext:'Pilsner beer city; significant industrial and Catholic records centre.',
    colonizer:'Holy Roman Empire, Habsburg Dynasty', romanizedNative:'Pilsen'),
  Place(continent:'Europe', name:'Liberec', modernCountry:'Czech Republic', iso3:'CZE', state:'Liberec Region',
    historicalContext:'Northern Bohemian textile city; large German-speaking population until 1945.',
    colonizer:'Habsburg Dynasty', romanizedNative:'Reichenberg'),
  Place(continent:'Europe', name:'České Budějovice', modernCountry:'Czech Republic', iso3:'CZE', state:'South Bohemian Region',
    historicalContext:'South Bohemian capital; Budweiser beer origin; royal silver-mining city.',
    colonizer:'Habsburg Dynasty', romanizedNative:'Budweis'),
  Place(continent:'Europe', name:'Olomouc', modernCountry:'Czech Republic', iso3:'CZE', state:'Olomouc Region',
    historicalContext:'Former capital of Moravia; cathedral city with Baroque fountains; major Catholic archive.',
    colonizer:'Holy Roman Empire', romanizedNative:'Olmütz'),

  // ── Additional Denmark ────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Odense', modernCountry:'Denmark', iso3:'DNK', state:'South Denmark',
    historicalContext:'Birthplace of Hans Christian Andersen; major Danish city since Viking era.',
    nativeTribes:'Norse Vikings', romanizedNative:'Odense'),
  Place(continent:'Europe', name:'Aalborg', modernCountry:'Denmark', iso3:'DNK', state:'North Denmark',
    historicalContext:'Major port and industrial city in northern Jutland; Viking burial site nearby.',
    nativeTribes:'Norse Vikings'),
  Place(continent:'Europe', name:'Fredericia', modernCountry:'Denmark', iso3:'DNK', state:'South Denmark',
    historicalContext:'Fortified town; historically offered religious tolerance, attracting Jewish settlers.',
    colonizer:'Danish Crown'),

  // ── Additional Estonia ────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Narva', modernCountry:'Estonia', iso3:'EST', state:'Ida-Viru County',
    historicalContext:'Border city with Russia; heavily Russian-speaking; scene of major 1700 Battle of Narva.',
    colonizer:'Swedish Empire, Russian Empire'),
  Place(continent:'Europe', name:'Pärnu', modernCountry:'Estonia', iso3:'EST', state:'Pärnu County',
    historicalContext:'Summer capital of Estonia; Hanseatic trading town; Baltic German population historically.',
    colonizer:'Livonian Order, Swedish Empire, Russian Empire'),

  // ── Additional Finland ────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Jyväskylä', modernCountry:'Finland', iso3:'FIN', state:'Central Finland',
    historicalContext:'University city; grew rapidly in 19th century under Russian rule as Grand Duchy.',
    colonizer:'Swedish Empire, Russian Empire'),
  Place(continent:'Europe', name:'Lahti', modernCountry:'Finland', iso3:'FIN', state:'Päijät-Häme',
    historicalContext:'Industrial city; skiing centre; grew after railway connection in 19th century.',
    colonizer:'Russian Empire'),
  Place(continent:'Europe', name:'Kuopio', modernCountry:'Finland', iso3:'FIN', state:'North Savo',
    historicalContext:'Eastern Finnish city; Orthodox Christian influence from Karelian tradition.',
    colonizer:'Swedish Empire, Russian Empire'),
  Place(continent:'Europe', name:'Vaasa', modernCountry:'Finland', iso3:'FIN', state:'Ostrobothnia',
    historicalContext:'West coast city; Swedish-speaking minority; major emigration port to America.',
    colonizer:'Swedish Empire, Russian Empire', romanizedNative:'Vasa'),

  // ── Additional France ─────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Montpellier', modernCountry:'France', iso3:'FRA', state:'Occitanie', county:'Hérault',
    historicalContext:'Medieval university city; large medieval Jewish community; on pilgrimage route.',
    colonizer:'Roman Empire'),
  Place(continent:'Europe', name:'Rennes', modernCountry:'France', iso3:'FRA', state:'Brittany', county:'Ille-et-Vilaine',
    historicalContext:'Capital of Brittany; Celtic Armorican stronghold; French-Breton records hub.',
    nativeTribes:'Celtic Redones', romanizedNative:'Condate'),
  Place(continent:'Europe', name:'Reims', modernCountry:'France', iso3:'FRA', state:'Grand Est', county:'Marne',
    historicalContext:'Where French kings were crowned; major Cathedral; Champagne region centre.',
    colonizer:'Roman Empire', nativeTribes:'Remi', romanizedNative:'Durocortorum'),
  Place(continent:'Europe', name:'Rouen', modernCountry:'France', iso3:'FRA', state:'Normandy', county:'Seine-Maritime',
    historicalContext:'Norman capital; Joan of Arc executed here; Viking Rollo\'s stronghold.',
    colonizer:'Roman Empire, Norse Vikings', nativeTribes:'Celtic Veliocasses', romanizedNative:'Rotomagus'),
  Place(continent:'Europe', name:'Dijon', modernCountry:'France', iso3:'FRA', state:'Bourgogne-Franche-Comté', county:'Côte-d\'Or',
    historicalContext:'Capital of the Duchy of Burgundy; wine and mustard capital; major ecclesiastical records.',
    colonizer:'Roman Empire', nativeTribes:'Lingones', romanizedNative:'Divio'),
  Place(continent:'Europe', name:'Grenoble', modernCountry:'France', iso3:'FRA', state:'Auvergne-Rhône-Alpes', county:'Isère',
    historicalContext:'Alpine city; Dauphiné capital; important French records centre.',
    colonizer:'Roman Empire', nativeTribes:'Allobroges', romanizedNative:'Cularo'),
  Place(continent:'Europe', name:'Metz', modernCountry:'France', iso3:'FRA', state:'Grand Est', county:'Moselle',
    historicalContext:'Ancient Gallo-Roman city; annexed by Germany 1871–1918; Moselle region genealogy hub.',
    colonizer:'Roman Empire, German Empire', nativeTribes:'Mediomatrici', romanizedNative:'Divodurum'),
  Place(continent:'Europe', name:'Caen', modernCountry:'France', iso3:'FRA', state:'Normandy', county:'Calvados',
    historicalContext:'William the Conqueror\'s capital; D-Day Memorial site; major Norman genealogy records.',
    colonizer:'Norse Vikings', nativeTribes:'Celtic Viducasses', romanizedNative:'Catumagos'),
  Place(continent:'Europe', name:'Angers', modernCountry:'France', iso3:'FRA', state:'Pays de la Loire', county:'Maine-et-Loire',
    historicalContext:'Capital of Anjou; Plantagenet dynasty cradle; major Loire Valley records centre.',
    colonizer:'Roman Empire', nativeTribes:'Andecavi', romanizedNative:'Juliomagus'),
  Place(continent:'Europe', name:'Le Havre', modernCountry:'France', iso3:'FRA', state:'Normandy', county:'Seine-Maritime',
    historicalContext:'Major Atlantic port; key emigration point for European migrants to the Americas.',
    colonizer:'French Crown'),
  Place(continent:'Europe', name:'Clermont-Ferrand', modernCountry:'France', iso3:'FRA', state:'Auvergne-Rhône-Alpes', county:'Puy-de-Dôme',
    historicalContext:'First Crusade called here 1095; Michelin tire company birthplace; Auvergne capital.',
    colonizer:'Roman Empire', nativeTribes:'Arverni', romanizedNative:'Augustonemetum'),

  // ── Additional Germany ────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Frankfurt am Main', modernCountry:'Germany', iso3:'DEU', state:'Hesse',
    historicalContext:'Free Imperial City; Holy Roman emperors elected/crowned here; major financial centre.',
    colonizer:'Roman Empire, Holy Roman Empire', nativeTribes:'Germanic tribes', romanizedNative:'Franconofurd'),
  Place(continent:'Europe', name:'Stuttgart', modernCountry:'Germany', iso3:'DEU', state:'Baden-Württemberg',
    historicalContext:'Capital of Württemberg; automotive industry; significant Swabian records.',
    colonizer:'Holy Roman Empire, Kingdom of Württemberg'),
  Place(continent:'Europe', name:'Düsseldorf', modernCountry:'Germany', iso3:'DEU', state:'North Rhine-Westphalia',
    historicalContext:'Capital of the Rhine Province; art and fashion city; extensive Rhine-Prussia records.',
    colonizer:'Holy Roman Empire'),
  Place(continent:'Europe', name:'Dortmund', modernCountry:'Germany', iso3:'DEU', state:'North Rhine-Westphalia',
    historicalContext:'Hanseatic city; Ruhr Valley coal and steel centre; major industrial genealogy records.',
    colonizer:'Holy Roman Empire'),
  Place(continent:'Europe', name:'Essen', modernCountry:'Germany', iso3:'DEU', state:'North Rhine-Westphalia',
    historicalContext:'Krupp steel empire headquarters; heart of the Ruhr industrial belt.',
    colonizer:'Holy Roman Empire'),
  Place(continent:'Europe', name:'Bremen', modernCountry:'Germany', iso3:'DEU', state:'Bremen',
    historicalContext:'Hanseatic League city-state; transatlantic emigration port; still a city-state today.',
    colonizer:'Holy Roman Empire'),
  Place(continent:'Europe', name:'Hannover', modernCountry:'Germany', iso3:'DEU', state:'Lower Saxony',
    historicalContext:'Capital of the Kingdom of Hanover; House of Hanover became British royal family.',
    colonizer:'Holy Roman Empire, Kingdom of Hanover'),
  Place(continent:'Europe', name:'Augsburg', modernCountry:'Germany', iso3:'DEU', state:'Bavaria',
    historicalContext:'Roman foundation; Free Imperial City; Peace of Augsburg 1555; Fugger banking family.',
    colonizer:'Roman Empire', nativeTribes:'Vindelici', romanizedNative:'Augusta Vindelicorum'),
  Place(continent:'Europe', name:'Mainz', modernCountry:'Germany', iso3:'DEU', state:'Rhineland-Palatinate',
    historicalContext:'Electoral archbishopric; Gutenberg\'s birthplace and printing press origin.',
    colonizer:'Roman Empire', nativeTribes:'Germanic Vangiones', romanizedNative:'Mogontiacum'),
  Place(continent:'Europe', name:'Freiburg im Breisgau', modernCountry:'Germany', iso3:'DEU', state:'Baden-Württemberg',
    historicalContext:'University city in the Black Forest; Habsburg territory; Baden genealogy records centre.',
    colonizer:'Habsburg Dynasty'),
  Place(continent:'Europe', name:'Rostock', modernCountry:'Germany', iso3:'DEU', state:'Mecklenburg-Vorpommern',
    historicalContext:'Hanseatic Baltic port; oldest German university (1419); emigration port.',
    nativeTribes:'Slavic Obotriti', romanizedNative:'Roztoc'),
  Place(continent:'Europe', name:'Karlsruhe', modernCountry:'Germany', iso3:'DEU', state:'Baden-Württemberg',
    historicalContext:'Founded 1715 as a planned city; seat of German Federal Court; Baden capital.',
    colonizer:'Margraviate of Baden'),
  Place(continent:'Europe', name:'Erfurt', modernCountry:'Germany', iso3:'DEU', state:'Thuringia',
    historicalContext:'Martin Luther studied here; Thuringian capital; important ecclesiastical records.',
    colonizer:'Holy Roman Empire'),
  Place(continent:'Europe', name:'Kassel', modernCountry:'Germany', iso3:'DEU', state:'Hesse',
    historicalContext:'Brothers Grimm collected fairy tales here; Landgraviate of Hesse capital.',
    colonizer:'Holy Roman Empire'),
  Place(continent:'Europe', name:'Wiesbaden', modernCountry:'Germany', iso3:'DEU', state:'Hesse',
    historicalContext:'Nassau ducal capital; Roman spa town; wealthy resort city on the Rhine.',
    colonizer:'Roman Empire, Duchy of Nassau', nativeTribes:'Mattiaci', romanizedNative:'Aquae Mattiacae'),
  Place(continent:'Europe', name:'Potsdam', modernCountry:'Germany', iso3:'DEU', state:'Brandenburg',
    historicalContext:'Prussian royal residence; Sanssouci Palace; Potsdam Conference 1945 reshaping Europe.',
    colonizer:'Kingdom of Prussia'),
  Place(continent:'Europe', name:'Lübeck', modernCountry:'Germany', iso3:'DEU', state:'Schleswig-Holstein',
    historicalContext:'Hanseatic League capital; "Queen of the Hanse"; Thomas Mann\'s birthplace.',
    colonizer:'Holy Roman Empire'),
  Place(continent:'Europe', name:'Regensburg', modernCountry:'Germany', iso3:'DEU', state:'Bavaria',
    historicalContext:'Roman fort on Danube; Holy Roman Empire diet met here; UNESCO old town.',
    colonizer:'Roman Empire', nativeTribes:'Celtic Raetii', romanizedNative:'Castra Regina'),
  Place(continent:'Europe', name:'Würzburg', modernCountry:'Germany', iso3:'DEU', state:'Bavaria',
    historicalContext:'Prince-bishopric; Baroque Residence Palace; Franconian wine and records.',
    colonizer:'Holy Roman Empire'),

  // ── Additional Greece ─────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Patras', modernCountry:'Greece', iso3:'GRC', state:'Western Greece',
    historicalContext:'Gateway to Italy; ancient Achaean city; carnival tradition; major port.',
    colonizer:'Roman Empire, Byzantine Empire, Ottoman Empire', nativeTribes:'Ancient Greeks', romanizedNative:'Πάτρα'),
  Place(continent:'Europe', name:'Heraklion', modernCountry:'Greece', iso3:'GRC', state:'Crete',
    historicalContext:'Capital of Crete; Minoan palace of Knossos nearby; long Venetian and Ottoman rule.',
    colonizer:'Byzantine Empire, Venetian Republic, Ottoman Empire', nativeTribes:'Minoans', romanizedNative:'Candia'),
  Place(continent:'Europe', name:'Larissa', modernCountry:'Greece', iso3:'GRC', state:'Thessaly',
    historicalContext:'Ancient Thessalian city; Hippocrates died here; Ottoman eyalet capital.',
    colonizer:'Roman Empire, Byzantine Empire, Ottoman Empire', nativeTribes:'Pelasgians', romanizedNative:'Λάρισα'),
  Place(continent:'Europe', name:'Ioannina', modernCountry:'Greece', iso3:'GRC', state:'Epirus',
    historicalContext:'Capital of the Pashalik of Yanina under Ali Pasha; important Orthodox and Jewish community.',
    colonizer:'Byzantine Empire, Ottoman Empire', romanizedNative:'Ιωάννινα'),

  // ── Additional Hungary ────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Pécs', modernCountry:'Hungary', iso3:'HUN', state:'Baranya County',
    historicalContext:'UNESCO Early Christian Necropolis; Roman Sopianae; major Ottoman settlement.',
    colonizer:'Roman Empire, Ottoman Empire, Habsburg Dynasty', nativeTribes:'Pannonian Celts', romanizedNative:'Sopianae'),
  Place(continent:'Europe', name:'Győr', modernCountry:'Hungary', iso3:'HUN', state:'Győr-Moson-Sopron County',
    historicalContext:'Roman Arrabona; important Catholic diocese; Habsburg border fortress.',
    colonizer:'Roman Empire, Ottoman Empire, Habsburg Dynasty', nativeTribes:'Celtic Aravisci', romanizedNative:'Arrabona'),
  Place(continent:'Europe', name:'Miskolc', modernCountry:'Hungary', iso3:'HUN', state:'Borsod-Abaúj-Zemplén County',
    historicalContext:'Industrial city; major iron and steel production; Hungarian-Slovak border region.',
    colonizer:'Habsburg Dynasty'),
  Place(continent:'Europe', name:'Eger', modernCountry:'Hungary', iso3:'HUN', state:'Heves County',
    historicalContext:'Baroque city; famous 1552 siege against Ottomans; wine region; Eger Bull\'s Blood wine.',
    colonizer:'Ottoman Empire, Habsburg Dynasty'),

  // ── Additional Ireland ────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Waterford', modernCountry:'Ireland', iso3:'IRL', state:'Munster', county:'County Waterford',
    historicalContext:'Ireland\'s oldest city; Viking Vadrefjord; important ecclesiastical and civil records.',
    colonizer:'Norse Vikings, Norman', nativeTribes:'Celtic Irish', romanizedNative:'Vadrefjord'),
  Place(continent:'Europe', name:'Kilkenny', modernCountry:'Ireland', iso3:'IRL', state:'Leinster', county:'County Kilkenny',
    historicalContext:'Medieval Norman city; seat of the Confederation of Kilkenny; significant castle.',
    colonizer:'Norman, English Crown', nativeTribes:'Celtic Irish'),
  Place(continent:'Europe', name:'Drogheda', modernCountry:'Ireland', iso3:'IRL', state:'Leinster', county:'County Louth',
    historicalContext:'Norse then Norman city; site of Cromwell\'s 1649 massacre; Battle of the Boyne nearby.',
    colonizer:'Norse Vikings, Norman, English Crown', nativeTribes:'Celtic Irish'),

  // ── Additional Italy ──────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Catania', modernCountry:'Italy', iso3:'ITA', state:'Sicily', county:'Metropolitan City of Catania',
    historicalContext:'At the foot of Etna; Greek colony Katane; Norman then Spanish then Bourbon rule.',
    colonizer:'Greek colonists, Roman Empire, Norman, Spanish Empire', nativeTribes:'Sicels', romanizedNative:'Catana'),
  Place(continent:'Europe', name:'Bari', modernCountry:'Italy', iso3:'ITA', state:'Apulia', county:'Metropolitan City of Bari',
    historicalContext:'Apulian capital; Norman then Byzantine; St. Nicholas Basilica; major emigration port.',
    colonizer:'Roman Empire, Byzantine Empire, Norman, Kingdom of Naples', nativeTribes:'Peucetii', romanizedNative:'Barium'),
  Place(continent:'Europe', name:'Verona', modernCountry:'Italy', iso3:'ITA', state:'Veneto', county:'Province of Verona',
    historicalContext:'Romeo and Juliet city; Roman amphitheatre; Lombard and Scaligeri rule; Venetian era.',
    colonizer:'Roman Empire, Lombards, Venetian Republic', nativeTribes:'Euganei', romanizedNative:'Verona'),
  Place(continent:'Europe', name:'Padua', modernCountry:'Italy', iso3:'ITA', state:'Veneto', county:'Province of Padua',
    historicalContext:'Ancient Patavium; Galileo taught here; Giotto Scrovegni Chapel; Venetian Republic era.',
    colonizer:'Roman Empire, Lombards, Venetian Republic', nativeTribes:'Euganei, Veneti', romanizedNative:'Patavium'),
  Place(continent:'Europe', name:'Trieste', modernCountry:'Italy', iso3:'ITA', state:'Friuli-Venezia Giulia',
    historicalContext:'Habsburg free port; cosmopolitan mix of Italian, Slovenian, Jewish, Greek communities.',
    colonizer:'Roman Empire, Habsburg Dynasty', nativeTribes:'Carni, Veneti', romanizedNative:'Tergeste'),
  Place(continent:'Europe', name:'Messina', modernCountry:'Italy', iso3:'ITA', state:'Sicily', county:'Metropolitan City of Messina',
    historicalContext:'Straits of Messina; Greek Zancle; major Arab, Norman, Spanish occupations.',
    colonizer:'Greek colonists, Arab, Norman, Spanish Empire', nativeTribes:'Sicels', romanizedNative:'Zancle'),
  Place(continent:'Europe', name:'Brescia', modernCountry:'Italy', iso3:'ITA', state:'Lombardy', county:'Province of Brescia',
    historicalContext:'Roman Brixia; Venetian then Austrian; arms industry; significant Jewish community.',
    colonizer:'Roman Empire, Lombards, Venetian Republic, Habsburg Dynasty', nativeTribes:'Celtic Cenomani', romanizedNative:'Brixia'),
  Place(continent:'Europe', name:'Reggio Calabria', modernCountry:'Italy', iso3:'ITA', state:'Calabria', county:'Metropolitan City of Reggio Calabria',
    historicalContext:'Oldest Greek colony in Italy (Rhegion); toe of the boot; Arabic and Norman influence.',
    colonizer:'Greek colonists, Roman Empire, Arab, Norman, Kingdom of Naples', nativeTribes:'Italic Bruttii', romanizedNative:'Rhegion'),
  Place(continent:'Europe', name:'Lecce', modernCountry:'Italy', iso3:'ITA', state:'Apulia', county:'Province of Lecce',
    historicalContext:'Florence of the South; Baroque architecture; Roman then Otranto Duchy records.',
    colonizer:'Roman Empire, Byzantine Empire, Norman, Spanish Empire', nativeTribes:'Messapii', romanizedNative:'Lupiae'),
  Place(continent:'Europe', name:'Perugia', modernCountry:'Italy', iso3:'ITA', state:'Umbria', county:'Province of Perugia',
    historicalContext:'Etruscan then Roman; medieval commune; Papal States; important Church records.',
    colonizer:'Roman Empire, Papal States', nativeTribes:'Etruscans', romanizedNative:'Perusia'),
  Place(continent:'Europe', name:'Ravenna', modernCountry:'Italy', iso3:'ITA', state:'Emilia-Romagna', county:'Province of Ravenna',
    historicalContext:'Western Roman Empire capital; Byzantine exarchate; UNESCO mosaics.',
    colonizer:'Roman Empire, Byzantine Empire, Lombards', nativeTribes:'Celtic Senones', romanizedNative:'Ravenna'),

  // ── Additional Latvia ─────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Daugavpils', modernCountry:'Latvia', iso3:'LVA', state:'Latgale',
    historicalContext:'Second city; historically Dvinsk; major Jewish and Russian community; Russian Empire records.',
    colonizer:'Livonian Order, Polish-Lithuanian Commonwealth, Russian Empire', romanizedNative:'Dvinsk'),
  Place(continent:'Europe', name:'Liepāja', modernCountry:'Latvia', iso3:'LVA', state:'Kurzeme',
    historicalContext:'Baltic port; German then Russian Empire; Soviet naval base; Libau in German records.',
    colonizer:'Livonian Order, Duchy of Courland, Russian Empire', romanizedNative:'Libau'),

  // ── Additional Lithuania ──────────────────────────────────────────────────
  Place(continent:'Europe', name:'Klaipėda', modernCountry:'Lithuania', iso3:'LTU', state:'Klaipėda County',
    historicalContext:'Memelland; German until 1939; Lithuanian port city; important Baltic records.',
    colonizer:'Teutonic Knights, Prussia, German Empire, Lithuanian administration', romanizedNative:'Memel'),
  Place(continent:'Europe', name:'Šiauliai', modernCountry:'Lithuania', iso3:'LTU', state:'Šiauliai County',
    historicalContext:'Northern Lithuanian city; Hill of Crosses pilgrimage site; significant Jewish history.',
    colonizer:'Russian Empire', romanizedNative:'Szawle'),

  // ── Additional Netherlands ────────────────────────────────────────────────
  Place(continent:'Europe', name:'Leiden', modernCountry:'Netherlands', iso3:'NLD', state:'South Holland',
    historicalContext:'University city (1575); Pilgrim Fathers lived here before sailing to America.',
    colonizer:'Spanish Netherlands, House of Orange'),
  Place(continent:'Europe', name:'Haarlem', modernCountry:'Netherlands', iso3:'NLD', state:'North Holland',
    historicalContext:'Near Amsterdam; early centre of Dutch Golden Age painting; tulip bulb trade.',
    colonizer:'Spanish Netherlands, House of Orange'),
  Place(continent:'Europe', name:'Groningen', modernCountry:'Netherlands', iso3:'NLD', state:'Groningen',
    historicalContext:'Northern Dutch capital; Hanseatic town; university city; extensive records.',
    colonizer:'Holy Roman Empire, Spanish Netherlands'),
  Place(continent:'Europe', name:'Maastricht', modernCountry:'Netherlands', iso3:'NLD', state:'Limburg',
    historicalContext:'Oldest Dutch city; Maastricht Treaty 1992; Burgundian and Habsburg territory.',
    colonizer:'Roman Empire, Duchy of Burgundy, Habsburg Dynasty', nativeTribes:'Germanic Tungri', romanizedNative:'Traiectum ad Mosam'),

  // ── Additional Norway ─────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Trondheim', modernCountry:'Norway', iso3:'NOR', state:'Trøndelag',
    historicalContext:'Former Norwegian capital Nidaros; burial place of St. Olaf; coronation city.',
    nativeTribes:'Norse Vikings', romanizedNative:'Nidaros'),
  Place(continent:'Europe', name:'Stavanger', modernCountry:'Norway', iso3:'NOR', state:'Rogaland',
    historicalContext:'Norway\'s oil capital; important emigration city to America; 12th-century cathedral.',
    nativeTribes:'Norse Vikings'),
  Place(continent:'Europe', name:'Tromsø', modernCountry:'Norway', iso3:'NOR', state:'Troms og Finnmark',
    historicalContext:'Arctic city; gateway for polar expeditions; Sami indigenous presence.',
    nativeTribes:'Sami'),

  // ── Additional Poland ─────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Poznań', modernCountry:'Poland', iso3:'POL', state:'Greater Poland Voivodeship',
    historicalContext:'Capital of Greater Poland; cradle of the Polish state; Piast dynasty seat.',
    colonizer:'Holy Roman Empire, Kingdom of Prussia, German Empire (Posen)', romanizedNative:'Posen'),
  Place(continent:'Europe', name:'Szczecin', modernCountry:'Poland', iso3:'POL', state:'West Pomeranian Voivodeship',
    historicalContext:'Pomeranian capital; historically Stettin (German); major Baltic port.',
    colonizer:'Holy Roman Empire, Kingdom of Prussia, German Empire', nativeTribes:'Slavic Pomeranians', romanizedNative:'Stettin'),
  Place(continent:'Europe', name:'Lublin', modernCountry:'Poland', iso3:'POL', state:'Lublin Voivodeship',
    historicalContext:'Major Jewish community; Union of Lublin 1569; Majdanek concentration camp nearby.',
    colonizer:'Polish-Lithuanian Commonwealth, Russian Empire'),
  Place(continent:'Europe', name:'Białystok', modernCountry:'Poland', iso3:'POL', state:'Podlaskie Voivodeship',
    historicalContext:'Major textile city; significant Jewish and Belarusian minority history.',
    colonizer:'Polish-Lithuanian Commonwealth, Russian Empire'),
  Place(continent:'Europe', name:'Katowice', modernCountry:'Poland', iso3:'POL', state:'Silesian Voivodeship',
    historicalContext:'Industrial Silesian city; historically German Kattowitz; coal mining centre.',
    colonizer:'Kingdom of Prussia, German Empire', romanizedNative:'Kattowitz'),
  Place(continent:'Europe', name:'Toruń', modernCountry:'Poland', iso3:'POL', state:'Kuyavian-Pomeranian Voivodeship',
    historicalContext:'Birthplace of Copernicus; Hanseatic city; Treaty of Toruń 1466 signed here.',
    colonizer:'Teutonic Knights, Polish-Lithuanian Commonwealth', romanizedNative:'Thorn'),
  Place(continent:'Europe', name:'Bydgoszcz', modernCountry:'Poland', iso3:'POL', state:'Kuyavian-Pomeranian Voivodeship',
    historicalContext:'Bromberg in German; Pomeranian-Kuyavian records; significant German community.',
    colonizer:'Kingdom of Prussia, German Empire', romanizedNative:'Bromberg'),
  Place(continent:'Europe', name:'Vilnius (historical Lithuania)', modernCountry:'Poland', iso3:'POL', state:'historical Lithuania',
    historicalContext:'Historical Polish Wilno; large Polish and Jewish population; interwar disputed city.',
    colonizer:'Polish-Lithuanian Commonwealth, Russian Empire', romanizedNative:'Wilno',
    validTo:'1939-09-18'),

  // ── Additional Portugal ───────────────────────────────────────────────────
  Place(continent:'Europe', name:'Coimbra', modernCountry:'Portugal', iso3:'PRT', state:'Coimbra District',
    historicalContext:'Former Portuguese capital; oldest Portuguese university (1290); major ecclesiastical records.',
    colonizer:'Roman Empire', nativeTribes:'Celtic Conii', romanizedNative:'Aeminium'),
  Place(continent:'Europe', name:'Braga', modernCountry:'Portugal', iso3:'PRT', state:'Braga District',
    historicalContext:'Rome of Portugal; ancient Bracara Augusta; archbishopric; major Catholic records hub.',
    colonizer:'Roman Empire', nativeTribes:'Celtic Bracari', romanizedNative:'Bracara Augusta'),
  Place(continent:'Europe', name:'Évora', modernCountry:'Portugal', iso3:'PRT', state:'Évora District',
    historicalContext:'Walled UNESCO city; Roman temple; Inquisition seat; important Alentejo records.',
    colonizer:'Roman Empire, Moorish (Arab)', nativeTribes:'Celtic Celts', romanizedNative:'Liberalitas Julia'),
  Place(continent:'Europe', name:'Faro', modernCountry:'Portugal', iso3:'PRT', state:'Faro District',
    historicalContext:'Algarve capital; Moorish until 1249; significant Jewish community until expulsion.',
    colonizer:'Moorish (Arab)', nativeTribes:'Lusitani', romanizedNative:'Ossónoba'),
  Place(continent:'Europe', name:'Setúbal', modernCountry:'Portugal', iso3:'PRT', state:'Setúbal District',
    historicalContext:'Major port south of Lisbon; Arrábida natural park; salt and fisheries records.',
    colonizer:'Roman Empire', romanizedNative:'Cetóbriga'),

  // ── Additional Romania ────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Timișoara', modernCountry:'Romania', iso3:'ROU', state:'Timiș County',
    historicalContext:'Banat capital; multiethnic (Romanian, Hungarian, German, Serbian); 1989 revolution began here.',
    colonizer:'Ottoman Empire, Habsburg Dynasty', nativeTribes:'Dacians', romanizedNative:'Timișoara'),
  Place(continent:'Europe', name:'Iași', modernCountry:'Romania', iso3:'ROU', state:'Iași County',
    historicalContext:'Former Moldavian capital; major Jewish community; major Orthodox Church records.',
    colonizer:'Ottoman Empire, Russian Empire (briefly)', romanizedNative:'Iași'),
  Place(continent:'Europe', name:'Constanța', modernCountry:'Romania', iso3:'ROU', state:'Constanța County',
    historicalContext:'Black Sea port; ancient Tomis; Ovid exiled here; Dobruja region records.',
    colonizer:'Greek colonists, Roman Empire, Ottoman Empire', nativeTribes:'Getae-Dacians', romanizedNative:'Tomis'),
  Place(continent:'Europe', name:'Brașov', modernCountry:'Romania', iso3:'ROU', state:'Brașov County',
    historicalContext:'Transylvanian Saxon city; German Kronstadt; Black Church; medieval town walls.',
    colonizer:'Teutonic Knights, Saxon settlers, Ottoman Empire, Habsburg Dynasty', romanizedNative:'Kronstadt'),

  // ── Additional Russia ─────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Nizhny Novgorod', modernCountry:'Russia', iso3:'RUS', state:'Nizhny Novgorod Oblast',
    historicalContext:'Major trade fair city; confluence of Volga and Oka; formerly Gorky in Soviet era.',
    colonizer:'Russian Empire', nativeTribes:'Mordvins, Maris', romanizedNative:'Nizhny Novgorod'),
  Place(continent:'Europe', name:'Rostov-on-Don', modernCountry:'Russia', iso3:'RUS', state:'Rostov Oblast',
    historicalContext:'Gateway to the Caucasus; southern Russian port on the Don River.',
    colonizer:'Russian Empire', romanizedNative:'Rostov-na-Donu'),
  Place(continent:'Europe', name:'Samara', modernCountry:'Russia', iso3:'RUS', state:'Samara Oblast',
    historicalContext:'Volga city; wartime Soviet capital during WWII; space industry.',
    colonizer:'Russian Empire', romanizedNative:'Kuybyshev (Soviet era)'),
  Place(continent:'Europe', name:'Volgograd', modernCountry:'Russia', iso3:'RUS', state:'Volgograd Oblast',
    historicalContext:'Battle of Stalingrad turning point of WWII; formerly Tsaritsyn, then Stalingrad.',
    colonizer:'Russian Empire', romanizedNative:'Stalingrad (Soviet era)'),
  Place(continent:'Europe', name:'Perm', modernCountry:'Russia', iso3:'RUS', state:'Perm Krai',
    historicalContext:'Ural industrial city; gateway to Siberia; significant deportee records from Stalin era.',
    colonizer:'Russian Empire'),
  Place(continent:'Europe', name:'Ufa', modernCountry:'Russia', iso3:'RUS', state:'Republic of Bashkortostan',
    historicalContext:'Capital of Bashkortostan; on Belaya River; Bashkir and Russian heritage.',
    colonizer:'Russian Empire', nativeTribes:'Bashkirs'),
  Place(continent:'Europe', name:'Saratov', modernCountry:'Russia', iso3:'RUS', state:'Saratov Oblast',
    historicalContext:'Major Volga port; Volga Germans settled nearby from 18th century.',
    colonizer:'Russian Empire'),
  Place(continent:'Europe', name:'Voronezh', modernCountry:'Russia', iso3:'RUS', state:'Voronezh Oblast',
    historicalContext:'Black soil region; Peter the Great built navy here; heavily destroyed in WWII.',
    colonizer:'Russian Empire'),

  // ── Additional Serbia ─────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Niš', modernCountry:'Serbia', iso3:'SRB', state:'Nišava District',
    historicalContext:'Birthplace of Constantine the Great; on Via Militaris; major Ottoman centre.',
    colonizer:'Roman Empire, Byzantine Empire, Ottoman Empire', nativeTribes:'Thracians', romanizedNative:'Naissus'),

  // ── Additional Slovakia ───────────────────────────────────────────────────
  Place(continent:'Europe', name:'Košice', modernCountry:'Slovakia', iso3:'SVK', state:'Košice Region',
    historicalContext:'Eastern Slovak capital; historically Hungarian Kassa; Transylvanian gateway.',
    colonizer:'Kingdom of Hungary, Habsburg Dynasty', romanizedNative:'Kassa'),
  Place(continent:'Europe', name:'Banská Bystrica', modernCountry:'Slovakia', iso3:'SVK', state:'Banská Bystrica Region',
    historicalContext:'Mining city; Slovak National Uprising 1944 HQ; historically German Neusohl.',
    colonizer:'Kingdom of Hungary, Habsburg Dynasty', romanizedNative:'Neusohl'),
  Place(continent:'Europe', name:'Prešov', modernCountry:'Slovakia', iso3:'SVK', state:'Prešov Region',
    historicalContext:'Eastern Slovak city; historically Hungarian Eperjes; Greek Catholic diocese.',
    colonizer:'Kingdom of Hungary, Habsburg Dynasty', romanizedNative:'Eperjes'),

  // ── Additional Spain ──────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Zaragoza', modernCountry:'Spain', iso3:'ESP', state:'Aragon', county:'Province of Zaragoza',
    historicalContext:'Capital of Aragon; Roman Caesaraugusta; Our Lady of the Pillar Basilica.',
    colonizer:'Roman Empire, Moorish (Arab)', nativeTribes:'Iberian Sedetani', romanizedNative:'Caesaraugusta'),
  Place(continent:'Europe', name:'Málaga', modernCountry:'Spain', iso3:'ESP', state:'Andalusia', county:'Province of Málaga',
    historicalContext:'Picasso\'s birthplace; Phoenician then Roman then Moorish; Costa del Sol.',
    colonizer:'Phoenician, Roman Empire, Moorish (Arab)', nativeTribes:'Iberian Bastetani', romanizedNative:'Malaca'),
  Place(continent:'Europe', name:'Córdoba', modernCountry:'Spain', iso3:'ESP', state:'Andalusia', county:'Province of Córdoba',
    historicalContext:'Capital of Umayyad Caliphate in Europe; greatest medieval city in Western Europe.',
    colonizer:'Roman Empire, Moorish (Arab)', nativeTribes:'Iberian Turdetani', romanizedNative:'Colonia Patricia'),
  Place(continent:'Europe', name:'Alicante', modernCountry:'Spain', iso3:'ESP', state:'Valencia', county:'Province of Alicante',
    historicalContext:'Mediterranean port; Moorish then Aragonese; Costa Blanca; wine and trade records.',
    colonizer:'Roman Empire, Moorish (Arab)', nativeTribes:'Iberian Contestani', romanizedNative:'Lucentum'),
  Place(continent:'Europe', name:'Murcia', modernCountry:'Spain', iso3:'ESP', state:'Region of Murcia',
    historicalContext:'Moorish Mursiya; agricultural region; important Muslim then Christian records.',
    colonizer:'Roman Empire, Moorish (Arab)', nativeTribes:'Iberian Mastienii'),
  Place(continent:'Europe', name:'Valladolid', modernCountry:'Spain', iso3:'ESP', state:'Castile and León', county:'Province of Valladolid',
    historicalContext:'Former capital of Castile and León; Columbus died here; Philip II born here.',
    colonizer:'Moorish (Arab)', nativeTribes:'Vaccaei'),
  Place(continent:'Europe', name:'Pamplona', modernCountry:'Spain', iso3:'ESP', state:'Navarre',
    historicalContext:'Capital of Navarre; running of the bulls; Roman Pompelo; Basque cultural records.',
    colonizer:'Roman Empire, Moorish (Arab)', nativeTribes:'Vascones', romanizedNative:'Pompaelo'),
  Place(continent:'Europe', name:'San Sebastián', modernCountry:'Spain', iso3:'ESP', state:'Basque Country', county:'Province of Gipuzkoa',
    historicalContext:'Basque coastal city; Donostia in Basque; culinary capital; Carlist Wars setting.',
    nativeTribes:'Basques', romanizedNative:'Donostia-San Sebastián'),
  Place(continent:'Europe', name:'Salamanca', modernCountry:'Spain', iso3:'ESP', state:'Castile and León', county:'Province of Salamanca',
    historicalContext:'University of Salamanca founded 1218; gold-stone Plateresque; Castilian records.',
    colonizer:'Roman Empire, Moorish (Arab)', nativeTribes:'Vaccaei', romanizedNative:'Salmantica'),
  Place(continent:'Europe', name:'Toledo', modernCountry:'Spain', iso3:'ESP', state:'Castile-La Mancha', county:'Province of Toledo',
    historicalContext:'Former Visigothic and Islamic capital; City of Three Cultures; sword-making tradition.',
    colonizer:'Roman Empire, Visigothic Kingdom, Moorish (Arab)', nativeTribes:'Carpetani', romanizedNative:'Toletum'),

  // ── Additional Sweden ─────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Uppsala', modernCountry:'Sweden', iso3:'SWE', state:'Uppsala County',
    historicalContext:'Sweden\'s oldest university; archbishopric; former pagan centre Uppsala; royal burial mounds.',
    nativeTribes:'Norse Vikings'),
  Place(continent:'Europe', name:'Linköping', modernCountry:'Sweden', iso3:'SWE', state:'Östergötland County',
    historicalContext:'Cathedral city; battle of Stångebro 1598; major Östergötland records centre.',
    nativeTribes:'Norse Vikings'),
  Place(continent:'Europe', name:'Örebro', modernCountry:'Sweden', iso3:'SWE', state:'Örebro County',
    historicalContext:'Central Swedish city; medieval castle; Swedish parliament met here several times.',
    nativeTribes:'Norse Vikings'),

  // ── Additional Switzerland ────────────────────────────────────────────────
  Place(continent:'Europe', name:'Basel', modernCountry:'Switzerland', iso3:'CHE', state:'Canton of Basel-City',
    historicalContext:'Rhine port city; Erasmus lived here; pharmaceutical industry; major archives.',
    colonizer:'Roman Empire, Holy Roman Empire', nativeTribes:'Celtic Raurici', romanizedNative:'Basilia'),
  Place(continent:'Europe', name:'Lucerne', modernCountry:'Switzerland', iso3:'CHE', state:'Canton of Lucerne',
    historicalContext:'Tourism hub on Lake Lucerne; Confederation founding member; Chapel Bridge.',
    colonizer:'Habsburg Dynasty', nativeTribes:'Celtic Helvetii', romanizedNative:'Luceria'),
  Place(continent:'Europe', name:'Lausanne', modernCountry:'Switzerland', iso3:'CHE', state:'Canton of Vaud',
    historicalContext:'Olympic capital; major Calvinist centre; John Calvin influence; Vaudois records.',
    colonizer:'Roman Empire, Burgundy, Habsburg Dynasty', nativeTribes:'Celtic Helvetii', romanizedNative:'Lausanna'),
  Place(continent:'Europe', name:'St. Gallen', modernCountry:'Switzerland', iso3:'CHE', state:'Canton of St. Gallen',
    historicalContext:'Benedictine abbey library (UNESCO); major Appenzell and Togenburg records hub.',
    colonizer:'Frankish Empire, Holy Roman Empire'),

  // ── Additional Ukraine ────────────────────────────────────────────────────
  Place(continent:'Europe', name:'Dnipro', modernCountry:'Ukraine', iso3:'UKR', state:'Dnipropetrovsk Oblast',
    historicalContext:'Industrial Dnieper city; Cossack Sich nearby; Soviet Dnepropetrovsk; rocket industry.',
    colonizer:'Russian Empire', romanizedNative:'Dnepropetrovsk (Soviet era)'),
  Place(continent:'Europe', name:'Donetsk', modernCountry:'Ukraine', iso3:'UKR', state:'Donetsk Oblast',
    historicalContext:'Coal and steel Donbas; founded as Yuzivka by Welsh industrialist John Hughes.',
    colonizer:'Russian Empire', romanizedNative:'Yuzivka / Stalino'),
  Place(continent:'Europe', name:'Zaporizhzhia', modernCountry:'Ukraine', iso3:'UKR', state:'Zaporizhzhia Oblast',
    historicalContext:'Zaporozhian Sich Cossack heartland; Dnieper dam; industrial city.',
    colonizer:'Russian Empire', nativeTribes:'Zaporozhian Cossacks', romanizedNative:'Alexandrovsk'),
  Place(continent:'Europe', name:'Vinnytsia', modernCountry:'Ukraine', iso3:'UKR', state:'Vinnytsia Oblast',
    historicalContext:'Podolia region; Polish-Lithuanian Commonwealth then Russia; major agricultural records.',
    colonizer:'Polish-Lithuanian Commonwealth, Russian Empire'),
  Place(continent:'Europe', name:'Chernivtsi', modernCountry:'Ukraine', iso3:'UKR', state:'Chernivtsi Oblast',
    historicalContext:'Austrian Czernowitz; multicultural (Ukrainian, Romanian, Jewish, German) Habsburg city.',
    colonizer:'Ottoman Empire, Habsburg Dynasty', romanizedNative:'Czernowitz'),
  Place(continent:'Europe', name:'Poltava', modernCountry:'Ukraine', iso3:'UKR', state:'Poltava Oblast',
    historicalContext:'Battle of Poltava 1709 (Peter the Great vs Charles XII); Cossack hetmanate centre.',
    colonizer:'Polish-Lithuanian Commonwealth, Russian Empire', nativeTribes:'Zaporozhian Cossacks'),

  // ── Additional United Kingdom ─────────────────────────────────────────────
  Place(continent:'Europe', name:'Bristol', modernCountry:'United Kingdom', iso3:'GBR', state:'England', county:'Bristol',
    historicalContext:'Major Atlantic port; transatlantic slave trade; John Cabot sailed here; emigration hub.',
    colonizer:'Norman', nativeTribes:'Celtic Dobunni'),
  Place(continent:'Europe', name:'Leeds', modernCountry:'United Kingdom', iso3:'GBR', state:'England', subState:'West Yorkshire', county:'Leeds',
    historicalContext:'Wool and textile industrial centre; large immigrant communities; Victorian records.',
    nativeTribes:'Celtic Brigantes'),
  Place(continent:'Europe', name:'Sheffield', modernCountry:'United Kingdom', iso3:'GBR', state:'England', subState:'South Yorkshire', county:'Sheffield',
    historicalContext:'Steel city; cutlery tradition since medieval times; heavy industry records.',
    nativeTribes:'Celtic Brigantes'),
  Place(continent:'Europe', name:'Newcastle upon Tyne', modernCountry:'United Kingdom', iso3:'GBR', state:'England', subState:'Tyne and Wear',
    historicalContext:'Roman fort Pons Aelius; coal mining capital; Geordie culture; Hadrian\'s Wall nearby.',
    colonizer:'Roman Empire, Norman', nativeTribes:'Celtic Brigantes', romanizedNative:'Pons Aelius'),
  Place(continent:'Europe', name:'Nottingham', modernCountry:'United Kingdom', iso3:'GBR', state:'England', subState:'Nottinghamshire',
    historicalContext:'Robin Hood legendarily linked; lace industry; Saxon burgh Snottingham.',
    colonizer:'Danish (Danelaw), Norman', nativeTribes:'Celtic Coritani', romanizedNative:'Tigguo Cobauc'),
  Place(continent:'Europe', name:'Leicester', modernCountry:'United Kingdom', iso3:'GBR', state:'England', subState:'Leicestershire',
    historicalContext:'Roman Ratae; Danelaw city; Richard III buried here; large South Asian community.',
    colonizer:'Roman Empire, Danish (Danelaw), Norman', nativeTribes:'Celtic Coritani', romanizedNative:'Ratae Corieltauvorum'),
  Place(continent:'Europe', name:'Southampton', modernCountry:'United Kingdom', iso3:'GBR', state:'England', subState:'Hampshire',
    historicalContext:'Major emigration port; Titanic and Mayflower departed from here.',
    colonizer:'Roman Empire, Saxon', nativeTribes:'Celtic Atrebates', romanizedNative:'Clausentum'),
  Place(continent:'Europe', name:'Exeter', modernCountry:'United Kingdom', iso3:'GBR', state:'England', subState:'Devon',
    historicalContext:'Roman Isca; Devon county town; cathedral; major south-west England records.',
    colonizer:'Roman Empire, Saxon, Norman', nativeTribes:'Celtic Dumnonii', romanizedNative:'Isca Dumnoniorum'),
  Place(continent:'Europe', name:'Oxford', modernCountry:'United Kingdom', iso3:'GBR', state:'England', subState:'Oxfordshire',
    historicalContext:'University of Oxford; Saxon burgh; English Civil War Royalist HQ.',
    colonizer:'Saxon, Norman', nativeTribes:'Celtic tribes'),
  Place(continent:'Europe', name:'Cambridge', modernCountry:'United Kingdom', iso3:'GBR', state:'England', subState:'Cambridgeshire',
    historicalContext:'University of Cambridge; Roman settlement; important Fenland and East Anglian records.',
    colonizer:'Roman Empire, Saxon, Norman', nativeTribes:'Iceni', romanizedNative:'Duroliponte'),
  Place(continent:'Europe', name:'Inverness', modernCountry:'United Kingdom', iso3:'GBR', state:'Scotland', county:'Highland',
    historicalContext:'Gateway to the Scottish Highlands; Culloden Battlefield nearby; Gaelic culture hub.',
    nativeTribes:'Picts'),
  Place(continent:'Europe', name:'Dundee', modernCountry:'United Kingdom', iso3:'GBR', state:'Scotland', county:'Dundee City',
    historicalContext:'Jute, jam and journalism city; Discovery ship; Pictish and Norse heritage.',
    nativeTribes:'Picts'),
  Place(continent:'Europe', name:'Aberdeen', modernCountry:'United Kingdom', iso3:'GBR', state:'Scotland', county:'Aberdeen City',
    historicalContext:'Granite city; two medieval universities; North Sea oil; rich Scottish parish records.',
    nativeTribes:'Picts'),
  Place(continent:'Europe', name:'Swansea', modernCountry:'United Kingdom', iso3:'GBR', state:'Wales', county:'Swansea',
    historicalContext:'Copper and tin industrial city; Dylan Thomas birthplace; Welsh-language records.',
    colonizer:'Norman, English Crown', nativeTribes:'Celtic Silures'),
  Place(continent:'Europe', name:'Derry', modernCountry:'United Kingdom', iso3:'GBR', state:'Northern Ireland', county:'County Londonderry',
    historicalContext:'Plantation city of Londonderry; walls intact; Irish nationalist and unionist history.',
    colonizer:'English/Scottish plantation', nativeTribes:'Gaels'),
  Place(continent:'Europe', name:'Canterbury', modernCountry:'United Kingdom', iso3:'GBR', state:'England', subState:'Kent', county:'Canterbury',
    historicalContext:'Archbishop of Canterbury seat; Chaucer\'s pilgrimage; Roman Durovernum; oldest English records.',
    colonizer:'Roman Empire, Saxon, Norman', nativeTribes:'Celtic Cantii', romanizedNative:'Durovernum Cantiacorum'),
  Place(continent:'Europe', name:'Plymouth', modernCountry:'United Kingdom', iso3:'GBR', state:'England', subState:'Devon',
    historicalContext:'Mayflower sailed from here 1620; Drake\'s port; major Royal Navy base.',
    colonizer:'Norman', nativeTribes:'Celtic Dumnonii'),
  Place(continent:'Europe', name:'Norwich', modernCountry:'United Kingdom', iso3:'GBR', state:'England', subState:'Norfolk',
    historicalContext:'Capital of East Anglia; important Flemish weaver community; major medieval diocese.',
    colonizer:'Danish (Danelaw), Norman', nativeTribes:'Iceni'),

];
