import '../models/place.dart';

/// Asia: ISO 3166-2 level-2 administrative subdivisions (districts, counties,
/// parishes, municipalities, etc.) plus all United States counties (FIPS).
// ignore_for_file: lines_longer_than_80_chars
const List<Place> placesL2Asia = [

  // ── Azerbaijan ──────────────────────────────────────────
  Place(continent:'Asia', name:'Babək', modernCountry:'Azerbaijan', iso3:'AZE', state:'Naxçıvan', historicalContext:'Rayon of Azerbaijan.'),
  Place(continent:'Asia', name:'Culfa', modernCountry:'Azerbaijan', iso3:'AZE', state:'Naxçıvan', historicalContext:'Rayon of Azerbaijan.'),
  Place(continent:'Asia', name:'Kǝngǝrli', modernCountry:'Azerbaijan', iso3:'AZE', state:'Naxçıvan', historicalContext:'Rayon of Azerbaijan.'),
  Place(continent:'Asia', name:'Naxçıvan', modernCountry:'Azerbaijan', iso3:'AZE', state:'Naxçıvan', historicalContext:'Municipality of Azerbaijan.'),
  Place(continent:'Asia', name:'Ordubad', modernCountry:'Azerbaijan', iso3:'AZE', state:'Naxçıvan', historicalContext:'Rayon of Azerbaijan.'),
  Place(continent:'Asia', name:'Sədərək', modernCountry:'Azerbaijan', iso3:'AZE', state:'Naxçıvan', historicalContext:'Rayon of Azerbaijan.'),
  Place(continent:'Asia', name:'Şahbuz', modernCountry:'Azerbaijan', iso3:'AZE', state:'Naxçıvan', historicalContext:'Rayon of Azerbaijan.'),
  Place(continent:'Asia', name:'Şərur', modernCountry:'Azerbaijan', iso3:'AZE', state:'Naxçıvan', historicalContext:'Rayon of Azerbaijan.'),

  // ── Bangladesh ──────────────────────────────────────────
  Place(continent:'Asia', name:'Bagerhat', modernCountry:'Bangladesh', iso3:'BGD', state:'Khulna', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Bandarban', modernCountry:'Bangladesh', iso3:'BGD', state:'Chattogram', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Barguna', modernCountry:'Bangladesh', iso3:'BGD', state:'Barishal', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Barishal', modernCountry:'Bangladesh', iso3:'BGD', state:'Barishal', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Bhola', modernCountry:'Bangladesh', iso3:'BGD', state:'Barishal', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Bogura', modernCountry:'Bangladesh', iso3:'BGD', state:'Rajshahi', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Brahmanbaria', modernCountry:'Bangladesh', iso3:'BGD', state:'Chattogram', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Chandpur', modernCountry:'Bangladesh', iso3:'BGD', state:'Chattogram', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Chapai Nawabganj', modernCountry:'Bangladesh', iso3:'BGD', state:'Rajshahi', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Chattogram', modernCountry:'Bangladesh', iso3:'BGD', state:'Chattogram', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Chuadanga', modernCountry:'Bangladesh', iso3:'BGD', state:'Khulna', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Cox\'s Bazar', modernCountry:'Bangladesh', iso3:'BGD', state:'Chattogram', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Cumilla', modernCountry:'Bangladesh', iso3:'BGD', state:'Chattogram', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Dhaka', modernCountry:'Bangladesh', iso3:'BGD', state:'Dhaka', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Dinajpur', modernCountry:'Bangladesh', iso3:'BGD', state:'Rangpur', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Faridpur', modernCountry:'Bangladesh', iso3:'BGD', state:'Dhaka', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Feni', modernCountry:'Bangladesh', iso3:'BGD', state:'Chattogram', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Gaibandha', modernCountry:'Bangladesh', iso3:'BGD', state:'Rangpur', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Gazipur', modernCountry:'Bangladesh', iso3:'BGD', state:'Dhaka', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Gopalganj', modernCountry:'Bangladesh', iso3:'BGD', state:'Dhaka', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Habiganj', modernCountry:'Bangladesh', iso3:'BGD', state:'Sylhet', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Jamalpur', modernCountry:'Bangladesh', iso3:'BGD', state:'Mymensingh', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Jashore', modernCountry:'Bangladesh', iso3:'BGD', state:'Khulna', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Jhalakathi', modernCountry:'Bangladesh', iso3:'BGD', state:'Barishal', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Jhenaidah', modernCountry:'Bangladesh', iso3:'BGD', state:'Khulna', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Joypurhat', modernCountry:'Bangladesh', iso3:'BGD', state:'Rajshahi', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Khagrachhari', modernCountry:'Bangladesh', iso3:'BGD', state:'Chattogram', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Khulna', modernCountry:'Bangladesh', iso3:'BGD', state:'Khulna', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Kishoreganj', modernCountry:'Bangladesh', iso3:'BGD', state:'Dhaka', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Kurigram', modernCountry:'Bangladesh', iso3:'BGD', state:'Rangpur', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Kushtia', modernCountry:'Bangladesh', iso3:'BGD', state:'Khulna', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Lakshmipur', modernCountry:'Bangladesh', iso3:'BGD', state:'Chattogram', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Lalmonirhat', modernCountry:'Bangladesh', iso3:'BGD', state:'Rangpur', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Madaripur', modernCountry:'Bangladesh', iso3:'BGD', state:'Dhaka', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Magura', modernCountry:'Bangladesh', iso3:'BGD', state:'Khulna', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Manikganj', modernCountry:'Bangladesh', iso3:'BGD', state:'Dhaka', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Meherpur', modernCountry:'Bangladesh', iso3:'BGD', state:'Khulna', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Moulvibazar', modernCountry:'Bangladesh', iso3:'BGD', state:'Sylhet', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Munshiganj', modernCountry:'Bangladesh', iso3:'BGD', state:'Dhaka', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Mymensingh', modernCountry:'Bangladesh', iso3:'BGD', state:'Mymensingh', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Naogaon', modernCountry:'Bangladesh', iso3:'BGD', state:'Rajshahi', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Narail', modernCountry:'Bangladesh', iso3:'BGD', state:'Khulna', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Narayanganj', modernCountry:'Bangladesh', iso3:'BGD', state:'Dhaka', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Narsingdi', modernCountry:'Bangladesh', iso3:'BGD', state:'Dhaka', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Natore', modernCountry:'Bangladesh', iso3:'BGD', state:'Rajshahi', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Netrakona', modernCountry:'Bangladesh', iso3:'BGD', state:'Mymensingh', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Nilphamari', modernCountry:'Bangladesh', iso3:'BGD', state:'Rangpur', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Noakhali', modernCountry:'Bangladesh', iso3:'BGD', state:'Chattogram', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Pabna', modernCountry:'Bangladesh', iso3:'BGD', state:'Rajshahi', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Panchagarh', modernCountry:'Bangladesh', iso3:'BGD', state:'Rangpur', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Patuakhali', modernCountry:'Bangladesh', iso3:'BGD', state:'Barishal', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Pirojpur', modernCountry:'Bangladesh', iso3:'BGD', state:'Barishal', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Rajbari', modernCountry:'Bangladesh', iso3:'BGD', state:'Dhaka', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Rajshahi', modernCountry:'Bangladesh', iso3:'BGD', state:'Rajshahi', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Rangamati', modernCountry:'Bangladesh', iso3:'BGD', state:'Chattogram', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Rangpur', modernCountry:'Bangladesh', iso3:'BGD', state:'Rangpur', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Satkhira', modernCountry:'Bangladesh', iso3:'BGD', state:'Khulna', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Shariatpur', modernCountry:'Bangladesh', iso3:'BGD', state:'Dhaka', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Sherpur', modernCountry:'Bangladesh', iso3:'BGD', state:'Mymensingh', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Sirajganj', modernCountry:'Bangladesh', iso3:'BGD', state:'Rajshahi', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Sunamganj', modernCountry:'Bangladesh', iso3:'BGD', state:'Sylhet', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Sylhet', modernCountry:'Bangladesh', iso3:'BGD', state:'Sylhet', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Tangail', modernCountry:'Bangladesh', iso3:'BGD', state:'Dhaka', historicalContext:'District of Bangladesh.'),
  Place(continent:'Asia', name:'Thakurgaon', modernCountry:'Bangladesh', iso3:'BGD', state:'Rangpur', historicalContext:'District of Bangladesh.'),

  // ── Indonesia ───────────────────────────────────────────
  Place(continent:'Asia', name:'Aceh', modernCountry:'Indonesia', iso3:'IDN', state:'Sumatera', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Bali', modernCountry:'Indonesia', iso3:'IDN', state:'Nusa Tenggara', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Banten', modernCountry:'Indonesia', iso3:'IDN', state:'Jawa', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Bengkulu', modernCountry:'Indonesia', iso3:'IDN', state:'Sumatera', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Gorontalo', modernCountry:'Indonesia', iso3:'IDN', state:'Sulawesi', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Jakarta Raya', modernCountry:'Indonesia', iso3:'IDN', state:'Jawa', historicalContext:'Capital district of Indonesia.'),
  Place(continent:'Asia', name:'Jambi', modernCountry:'Indonesia', iso3:'IDN', state:'Sumatera', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Jawa Barat', modernCountry:'Indonesia', iso3:'IDN', state:'Jawa', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Jawa Tengah', modernCountry:'Indonesia', iso3:'IDN', state:'Jawa', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Jawa Timur', modernCountry:'Indonesia', iso3:'IDN', state:'Jawa', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Kalimantan Barat', modernCountry:'Indonesia', iso3:'IDN', state:'Kalimantan', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Kalimantan Selatan', modernCountry:'Indonesia', iso3:'IDN', state:'Kalimantan', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Kalimantan Tengah', modernCountry:'Indonesia', iso3:'IDN', state:'Kalimantan', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Kalimantan Timur', modernCountry:'Indonesia', iso3:'IDN', state:'Kalimantan', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Kalimantan Utara', modernCountry:'Indonesia', iso3:'IDN', state:'Kalimantan', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Kepulauan Bangka Belitung', modernCountry:'Indonesia', iso3:'IDN', state:'Sumatera', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Kepulauan Riau', modernCountry:'Indonesia', iso3:'IDN', state:'Sumatera', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Lampung', modernCountry:'Indonesia', iso3:'IDN', state:'Sumatera', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Maluku', modernCountry:'Indonesia', iso3:'IDN', state:'Maluku', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Maluku Utara', modernCountry:'Indonesia', iso3:'IDN', state:'Maluku', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Nusa Tenggara Barat', modernCountry:'Indonesia', iso3:'IDN', state:'Nusa Tenggara', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Nusa Tenggara Timur', modernCountry:'Indonesia', iso3:'IDN', state:'Nusa Tenggara', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Papua', modernCountry:'Indonesia', iso3:'IDN', state:'Papua', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Papua Barat', modernCountry:'Indonesia', iso3:'IDN', state:'Papua', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Papua Barat Daya', modernCountry:'Indonesia', iso3:'IDN', state:'Papua', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Papua Pengunungan', modernCountry:'Indonesia', iso3:'IDN', state:'Papua', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Papua Selatan', modernCountry:'Indonesia', iso3:'IDN', state:'Papua', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Papua Tengah', modernCountry:'Indonesia', iso3:'IDN', state:'Papua', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Riau', modernCountry:'Indonesia', iso3:'IDN', state:'Sumatera', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Sulawesi Barat', modernCountry:'Indonesia', iso3:'IDN', state:'Sulawesi', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Sulawesi Selatan', modernCountry:'Indonesia', iso3:'IDN', state:'Sulawesi', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Sulawesi Tengah', modernCountry:'Indonesia', iso3:'IDN', state:'Sulawesi', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Sulawesi Tenggara', modernCountry:'Indonesia', iso3:'IDN', state:'Sulawesi', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Sulawesi Utara', modernCountry:'Indonesia', iso3:'IDN', state:'Sulawesi', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Sumatera Barat', modernCountry:'Indonesia', iso3:'IDN', state:'Sumatera', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Sumatera Selatan', modernCountry:'Indonesia', iso3:'IDN', state:'Sumatera', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Sumatera Utara', modernCountry:'Indonesia', iso3:'IDN', state:'Sumatera', historicalContext:'Province of Indonesia.'),
  Place(continent:'Asia', name:'Yogyakarta', modernCountry:'Indonesia', iso3:'IDN', state:'Jawa', historicalContext:'Special region of Indonesia.'),

  // ── Iraq ────────────────────────────────────────────────
  Place(continent:'Asia', name:'Arbīl', modernCountry:'Iraq', iso3:'IRQ', state:'Iqlīm Kūrdistān', historicalContext:'Governorate of Iraq.'),
  Place(continent:'Asia', name:'As Sulaymānīyah', modernCountry:'Iraq', iso3:'IRQ', state:'Iqlīm Kūrdistān', historicalContext:'Governorate of Iraq.'),
  Place(continent:'Asia', name:'Dahūk', modernCountry:'Iraq', iso3:'IRQ', state:'Iqlīm Kūrdistān', historicalContext:'Governorate of Iraq.'),

  // ── Sri Lanka ───────────────────────────────────────────
  Place(continent:'Asia', name:'Ampara', modernCountry:'Sri Lanka', iso3:'LKA', state:'Eastern Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Anuradhapura', modernCountry:'Sri Lanka', iso3:'LKA', state:'North Central Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Badulla', modernCountry:'Sri Lanka', iso3:'LKA', state:'Uva Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Batticaloa', modernCountry:'Sri Lanka', iso3:'LKA', state:'Eastern Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Colombo', modernCountry:'Sri Lanka', iso3:'LKA', state:'Western Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Galle', modernCountry:'Sri Lanka', iso3:'LKA', state:'Southern Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Gampaha', modernCountry:'Sri Lanka', iso3:'LKA', state:'Western Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Hambantota', modernCountry:'Sri Lanka', iso3:'LKA', state:'Southern Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Jaffna', modernCountry:'Sri Lanka', iso3:'LKA', state:'Northern Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Kalutara', modernCountry:'Sri Lanka', iso3:'LKA', state:'Western Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Kandy', modernCountry:'Sri Lanka', iso3:'LKA', state:'Central Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Kegalla', modernCountry:'Sri Lanka', iso3:'LKA', state:'Sabaragamuwa Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Kilinochchi', modernCountry:'Sri Lanka', iso3:'LKA', state:'Northern Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Kurunegala', modernCountry:'Sri Lanka', iso3:'LKA', state:'North Western Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Mannar', modernCountry:'Sri Lanka', iso3:'LKA', state:'Northern Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Matale', modernCountry:'Sri Lanka', iso3:'LKA', state:'Central Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Matara', modernCountry:'Sri Lanka', iso3:'LKA', state:'Southern Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Monaragala', modernCountry:'Sri Lanka', iso3:'LKA', state:'Uva Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Mullaittivu', modernCountry:'Sri Lanka', iso3:'LKA', state:'Northern Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Nuwara Eliya', modernCountry:'Sri Lanka', iso3:'LKA', state:'Central Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Polonnaruwa', modernCountry:'Sri Lanka', iso3:'LKA', state:'North Central Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Puttalam', modernCountry:'Sri Lanka', iso3:'LKA', state:'North Western Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Ratnapura', modernCountry:'Sri Lanka', iso3:'LKA', state:'Sabaragamuwa Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Trincomalee', modernCountry:'Sri Lanka', iso3:'LKA', state:'Eastern Province', historicalContext:'District of Sri Lanka.'),
  Place(continent:'Asia', name:'Vavuniya', modernCountry:'Sri Lanka', iso3:'LKA', state:'Northern Province', historicalContext:'District of Sri Lanka.'),

  // ── Philippines ─────────────────────────────────────────
  Place(continent:'Asia', name:'Abra', modernCountry:'Philippines', iso3:'PHL', state:'Cordillera Administrative Region (CAR)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Agusan del Norte', modernCountry:'Philippines', iso3:'PHL', state:'Caraga (Region XIII)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Agusan del Sur', modernCountry:'Philippines', iso3:'PHL', state:'Caraga (Region XIII)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Aklan', modernCountry:'Philippines', iso3:'PHL', state:'Western Visayas (Region VI)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Albay', modernCountry:'Philippines', iso3:'PHL', state:'Bicol (Region V)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Antique', modernCountry:'Philippines', iso3:'PHL', state:'Western Visayas (Region VI)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Apayao', modernCountry:'Philippines', iso3:'PHL', state:'Cordillera Administrative Region (CAR)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Aurora', modernCountry:'Philippines', iso3:'PHL', state:'Central Luzon (Region III)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Basilan', modernCountry:'Philippines', iso3:'PHL', state:'Zamboanga Peninsula (Region IX)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Bataan', modernCountry:'Philippines', iso3:'PHL', state:'Central Luzon (Region III)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Batanes', modernCountry:'Philippines', iso3:'PHL', state:'Cagayan Valley (Region II)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Batangas', modernCountry:'Philippines', iso3:'PHL', state:'Calabarzon (Region IV-A)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Benguet', modernCountry:'Philippines', iso3:'PHL', state:'Cordillera Administrative Region (CAR)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Biliran', modernCountry:'Philippines', iso3:'PHL', state:'Eastern Visayas (Region VIII)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Bohol', modernCountry:'Philippines', iso3:'PHL', state:'Central Visayas (Region VII)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Bukidnon', modernCountry:'Philippines', iso3:'PHL', state:'Northern Mindanao (Region X)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Bulacan', modernCountry:'Philippines', iso3:'PHL', state:'Central Luzon (Region III)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Cagayan', modernCountry:'Philippines', iso3:'PHL', state:'Cagayan Valley (Region II)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Camarines Norte', modernCountry:'Philippines', iso3:'PHL', state:'Bicol (Region V)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Camarines Sur', modernCountry:'Philippines', iso3:'PHL', state:'Bicol (Region V)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Camiguin', modernCountry:'Philippines', iso3:'PHL', state:'Northern Mindanao (Region X)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Capiz', modernCountry:'Philippines', iso3:'PHL', state:'Western Visayas (Region VI)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Catanduanes', modernCountry:'Philippines', iso3:'PHL', state:'Bicol (Region V)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Cavite', modernCountry:'Philippines', iso3:'PHL', state:'Calabarzon (Region IV-A)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Cebu', modernCountry:'Philippines', iso3:'PHL', state:'Central Visayas (Region VII)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Cotabato', modernCountry:'Philippines', iso3:'PHL', state:'Soccsksargen (Region XII)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Davao Occidental', modernCountry:'Philippines', iso3:'PHL', state:'Davao (Region XI)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Davao Oriental', modernCountry:'Philippines', iso3:'PHL', state:'Davao (Region XI)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Davao de Oro', modernCountry:'Philippines', iso3:'PHL', state:'Davao (Region XI)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Davao del Norte', modernCountry:'Philippines', iso3:'PHL', state:'Davao (Region XI)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Davao del Sur', modernCountry:'Philippines', iso3:'PHL', state:'Davao (Region XI)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Dinagat Islands', modernCountry:'Philippines', iso3:'PHL', state:'Caraga (Region XIII)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Eastern Samar', modernCountry:'Philippines', iso3:'PHL', state:'Eastern Visayas (Region VIII)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Guimaras', modernCountry:'Philippines', iso3:'PHL', state:'Western Visayas (Region VI)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Ifugao', modernCountry:'Philippines', iso3:'PHL', state:'Cordillera Administrative Region (CAR)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Ilocos Norte', modernCountry:'Philippines', iso3:'PHL', state:'Ilocos (Region I)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Ilocos Sur', modernCountry:'Philippines', iso3:'PHL', state:'Ilocos (Region I)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Iloilo', modernCountry:'Philippines', iso3:'PHL', state:'Western Visayas (Region VI)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Isabela', modernCountry:'Philippines', iso3:'PHL', state:'Cagayan Valley (Region II)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Kalinga', modernCountry:'Philippines', iso3:'PHL', state:'Cordillera Administrative Region (CAR)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'La Union', modernCountry:'Philippines', iso3:'PHL', state:'Ilocos (Region I)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Laguna', modernCountry:'Philippines', iso3:'PHL', state:'Calabarzon (Region IV-A)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Lanao del Norte', modernCountry:'Philippines', iso3:'PHL', state:'Soccsksargen (Region XII)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Lanao del Sur', modernCountry:'Philippines', iso3:'PHL', state:'Autonomous Region in Muslim Mindanao (ARMM)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Leyte', modernCountry:'Philippines', iso3:'PHL', state:'Eastern Visayas (Region VIII)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Maguindanao del Norte', modernCountry:'Philippines', iso3:'PHL', state:'Autonomous Region in Muslim Mindanao (ARMM)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Maguindanao del Sur', modernCountry:'Philippines', iso3:'PHL', state:'Autonomous Region in Muslim Mindanao (ARMM)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Marinduque', modernCountry:'Philippines', iso3:'PHL', state:'Mimaropa (Region IV-B)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Masbate', modernCountry:'Philippines', iso3:'PHL', state:'Bicol (Region V)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Mindoro Occidental', modernCountry:'Philippines', iso3:'PHL', state:'Mimaropa (Region IV-B)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Mindoro Oriental', modernCountry:'Philippines', iso3:'PHL', state:'Mimaropa (Region IV-B)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Misamis Occidental', modernCountry:'Philippines', iso3:'PHL', state:'Northern Mindanao (Region X)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Misamis Oriental', modernCountry:'Philippines', iso3:'PHL', state:'Northern Mindanao (Region X)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Mountain Province', modernCountry:'Philippines', iso3:'PHL', state:'Cordillera Administrative Region (CAR)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Negros Occidental', modernCountry:'Philippines', iso3:'PHL', state:'Western Visayas (Region VI)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Negros Oriental', modernCountry:'Philippines', iso3:'PHL', state:'Central Visayas (Region VII)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Northern Samar', modernCountry:'Philippines', iso3:'PHL', state:'Eastern Visayas (Region VIII)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Nueva Ecija', modernCountry:'Philippines', iso3:'PHL', state:'Central Luzon (Region III)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Nueva Vizcaya', modernCountry:'Philippines', iso3:'PHL', state:'Cagayan Valley (Region II)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Palawan', modernCountry:'Philippines', iso3:'PHL', state:'Mimaropa (Region IV-B)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Pampanga', modernCountry:'Philippines', iso3:'PHL', state:'Central Luzon (Region III)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Pangasinan', modernCountry:'Philippines', iso3:'PHL', state:'Ilocos (Region I)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Quezon', modernCountry:'Philippines', iso3:'PHL', state:'Calabarzon (Region IV-A)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Quirino', modernCountry:'Philippines', iso3:'PHL', state:'Cagayan Valley (Region II)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Rizal', modernCountry:'Philippines', iso3:'PHL', state:'Calabarzon (Region IV-A)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Romblon', modernCountry:'Philippines', iso3:'PHL', state:'Mimaropa (Region IV-B)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Samar', modernCountry:'Philippines', iso3:'PHL', state:'Eastern Visayas (Region VIII)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Sarangani', modernCountry:'Philippines', iso3:'PHL', state:'Davao (Region XI)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Siquijor', modernCountry:'Philippines', iso3:'PHL', state:'Central Visayas (Region VII)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Sorsogon', modernCountry:'Philippines', iso3:'PHL', state:'Bicol (Region V)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'South Cotabato', modernCountry:'Philippines', iso3:'PHL', state:'Davao (Region XI)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Southern Leyte', modernCountry:'Philippines', iso3:'PHL', state:'Eastern Visayas (Region VIII)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Sultan Kudarat', modernCountry:'Philippines', iso3:'PHL', state:'Soccsksargen (Region XII)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Sulu', modernCountry:'Philippines', iso3:'PHL', state:'Autonomous Region in Muslim Mindanao (ARMM)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Surigao del Norte', modernCountry:'Philippines', iso3:'PHL', state:'Caraga (Region XIII)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Surigao del Sur', modernCountry:'Philippines', iso3:'PHL', state:'Caraga (Region XIII)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Tarlac', modernCountry:'Philippines', iso3:'PHL', state:'Central Luzon (Region III)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Tawi-Tawi', modernCountry:'Philippines', iso3:'PHL', state:'Autonomous Region in Muslim Mindanao (ARMM)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Zambales', modernCountry:'Philippines', iso3:'PHL', state:'Central Luzon (Region III)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Zamboanga Sibugay', modernCountry:'Philippines', iso3:'PHL', state:'Zamboanga Peninsula (Region IX)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Zamboanga del Norte', modernCountry:'Philippines', iso3:'PHL', state:'Zamboanga Peninsula (Region IX)', historicalContext:'Province of Philippines.'),
  Place(continent:'Asia', name:'Zamboanga del Sur', modernCountry:'Philippines', iso3:'PHL', state:'Zamboanga Peninsula (Region IX)', historicalContext:'Province of Philippines.'),
];
