import 'dart:io';

import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:provider/provider.dart';

import '../models/person.dart';
import '../models/source.dart';
import '../providers/tree_provider.dart';
import '../screens/relationship_finder_screen.dart'
    show describeRelationship;

/// Generates a formatted, printable relationship-proof document that lists the
/// full ancestry path between two people together with all supporting source
/// citations along that path.
class RelationshipCertificateScreen extends StatefulWidget {
  const RelationshipCertificateScreen({super.key});

  @override
  State<RelationshipCertificateScreen> createState() =>
      _RelationshipCertificateScreenState();
}

class _RelationshipCertificateScreenState
    extends State<RelationshipCertificateScreen> {
  String? _fromId;
  String? _toId;
  List<String>? _path;
  String? _certificateText;
  bool _searched = false;

  void _generate(TreeProvider provider) {
    if (_fromId == null || _toId == null) return;
    final path = provider.findRelationshipPath(_fromId!, _toId!);
    setState(() {
      _path = path;
      _searched = true;
      _certificateText = path.isEmpty
          ? null
          : _buildCertificateText(path, provider);
    });
  }

  String _buildCertificateText(
      List<String> path, TreeProvider provider) {
    final personMap = {for (final p in provider.persons) p.id: p};
    final sourceMap = {for (final s in provider.sources) s.id: s};

    final from = personMap[path.first];
    final to = personMap[path.last];
    if (from == null || to == null) return '';

    final label = describeRelationship(from, to, provider.persons, path);
    final today = DateFormat('d MMMM yyyy').format(DateTime.now());

    final buf = StringBuffer();
    buf.writeln('═' * 60);
    buf.writeln('           RELATIONSHIP CERTIFICATE');
    buf.writeln('═' * 60);
    buf.writeln();
    buf.writeln('Generated by Vetviona  ·  $today');
    buf.writeln();
    buf.writeln('This document certifies that:');
    buf.writeln();
    buf.writeln('  ${from.name}');
    buf.writeln();
    buf.writeln('is the $label of:');
    buf.writeln();
    buf.writeln('  ${to.name}');
    buf.writeln();
    buf.writeln('─' * 60);
    buf.writeln('RELATIONSHIP PATH  (${path.length - 1} step${path.length == 2 ? '' : 's'})');
    buf.writeln('─' * 60);
    buf.writeln();

    for (int i = 0; i < path.length; i++) {
      final id = path[i];
      final person = personMap[id];
      if (person == null) continue;
      buf.writeln('  ${i + 1}. ${person.name}');
      if (person.birthDate != null) {
        final bPlace = person.birthPlace != null &&
                person.birthPlace!.isNotEmpty
            ? ', ${person.birthPlace}'
            : '';
        buf.writeln(
            '     Born: ${DateFormat('d MMMM yyyy').format(person.birthDate!)}$bPlace');
      } else if (person.birthPlace != null && person.birthPlace!.isNotEmpty) {
        buf.writeln('     Born: ${person.birthPlace}');
      }
      if (person.deathDate != null) {
        final dPlace = person.deathPlace != null &&
                person.deathPlace!.isNotEmpty
            ? ', ${person.deathPlace}'
            : '';
        buf.writeln(
            '     Died: ${DateFormat('d MMMM yyyy').format(person.deathDate!)}$dPlace');
      }
      if (i < path.length - 1) {
        buf.writeln('       ↓');
      }
      buf.writeln();
    }

    // Collect all sources cited by persons along the path
    final allSources = <Source>[];
    for (final id in path) {
      final person = personMap[id];
      if (person == null) continue;
      for (final srcId in person.sourceIds) {
        final src = sourceMap[srcId];
        if (src != null && !allSources.any((s) => s.id == srcId)) {
          allSources.add(src);
        }
      }
    }

    if (allSources.isNotEmpty) {
      buf.writeln('─' * 60);
      buf.writeln('SOURCE CITATIONS');
      buf.writeln('─' * 60);
      buf.writeln();
      for (int i = 0; i < allSources.length; i++) {
        final src = allSources[i];
        final citedPerson = personMap[src.personId];
        buf.writeln('  [${i + 1}] ${src.title}');
        buf.writeln('      Type: ${src.type}');
        if (src.url.isNotEmpty && src.url != 'manual') {
          buf.writeln('      Reference: ${src.url}');
        }
        if (src.citedFacts.isNotEmpty) {
          buf.writeln('      Cited facts: ${src.citedFacts.join(', ')}');
        }
        if (src.extractedInfo != null && src.extractedInfo!.isNotEmpty) {
          buf.writeln('      Notes: ${src.extractedInfo}');
        }
        if (citedPerson != null) {
          buf.writeln('      For: ${citedPerson.name}');
        }
        buf.writeln();
      }
    } else {
      buf.writeln('─' * 60);
      buf.writeln('No source citations on record for this path.');
      buf.writeln();
    }

    buf.writeln('═' * 60);
    buf.writeln('END OF CERTIFICATE');
    buf.writeln('═' * 60);

    return buf.toString();
  }

  Future<void> _exportCertificate(BuildContext context) async {
    if (_certificateText == null) return;
    try {
      final dir = await getApplicationDocumentsDirectory();
      final ts = DateTime.now().millisecondsSinceEpoch;
      final file = File('${dir.path}/relationship_certificate_$ts.txt');
      await file.writeAsString(_certificateText!);
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Certificate saved to: ${file.path}')),
        );
      }
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Export failed: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final provider = context.watch<TreeProvider>();
    final persons = provider.persons;
    final colorScheme = Theme.of(context).colorScheme;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Relationship Certificate'),
        actions: [
          if (_certificateText != null)
            IconButton(
              icon: const Icon(Icons.download_outlined),
              tooltip: 'Export as text file',
              onPressed: () => _exportCertificate(context),
            ),
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Card(
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Icon(Icons.verified_outlined,
                            color: colorScheme.primary),
                        const SizedBox(width: 8),
                        Text(
                          'Generate Certificate',
                          style: Theme.of(context)
                              .textTheme
                              .titleSmall
                              ?.copyWith(
                                  fontWeight: FontWeight.bold,
                                  color: colorScheme.primary),
                        ),
                      ],
                    ),
                    const SizedBox(height: 4),
                    Text(
                      'Generates a formal document proving the relationship path between two people, with all source citations. Useful for citizenship, inheritance, and tribal enrollment applications.',
                      style: Theme.of(context).textTheme.bodySmall?.copyWith(
                          color: colorScheme.onSurfaceVariant),
                    ),
                    const SizedBox(height: 16),
                    DropdownButtonFormField<String>(
                      decoration: const InputDecoration(
                          labelText: 'Person A (subject)',
                          border: OutlineInputBorder()),
                      value: _fromId,
                      items: persons
                          .map((p) => DropdownMenuItem(
                              value: p.id, child: Text(p.name)))
                          .toList(),
                      onChanged: (v) => setState(() {
                        _fromId = v;
                        _searched = false;
                        _certificateText = null;
                      }),
                    ),
                    const SizedBox(height: 12),
                    DropdownButtonFormField<String>(
                      decoration: const InputDecoration(
                          labelText: 'Person B (ancestor / relative)',
                          border: OutlineInputBorder()),
                      value: _toId,
                      items: persons
                          .map((p) => DropdownMenuItem(
                              value: p.id, child: Text(p.name)))
                          .toList(),
                      onChanged: (v) => setState(() {
                        _toId = v;
                        _searched = false;
                        _certificateText = null;
                      }),
                    ),
                    const SizedBox(height: 16),
                    SizedBox(
                      width: double.infinity,
                      child: FilledButton.icon(
                        icon: const Icon(Icons.verified),
                        label: const Text('Generate Certificate'),
                        onPressed: (_fromId != null && _toId != null)
                            ? () => _generate(provider)
                            : null,
                      ),
                    ),
                  ],
                ),
              ),
            ),
            if (_searched) ...[
              const SizedBox(height: 12),
              if (_certificateText == null)
                Card(
                  child: Padding(
                    padding: const EdgeInsets.all(16),
                    child: Row(
                      children: [
                        Icon(Icons.link_off, color: colorScheme.error),
                        const SizedBox(width: 8),
                        const Expanded(
                          child: Text(
                              'No relationship path found between these two people.'),
                        ),
                      ],
                    ),
                  ),
                )
              else
                Expanded(
                  child: Card(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Padding(
                          padding: const EdgeInsets.fromLTRB(16, 12, 8, 4),
                          child: Row(
                            children: [
                              Icon(Icons.description_outlined,
                                  color: colorScheme.primary),
                              const SizedBox(width: 8),
                              Text(
                                'Certificate Preview',
                                style: Theme.of(context)
                                    .textTheme
                                    .titleSmall
                                    ?.copyWith(
                                        fontWeight: FontWeight.bold,
                                        color: colorScheme.primary),
                              ),
                              const Spacer(),
                              IconButton(
                                icon: const Icon(Icons.download_outlined),
                                tooltip: 'Export',
                                onPressed: () => _exportCertificate(context),
                              ),
                            ],
                          ),
                        ),
                        Expanded(
                          child: SingleChildScrollView(
                            padding: const EdgeInsets.fromLTRB(16, 4, 16, 16),
                            child: SelectableText(
                              _certificateText!,
                              style: const TextStyle(
                                fontFamily: 'monospace',
                                fontSize: 12,
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
            ],
          ],
        ),
      ),
    );
  }
}
