import 'package:flutter/material.dart';
import 'package:flutter_colorpicker/flutter_colorpicker.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../providers/theme_provider.dart';

class SettingsScreen extends StatefulWidget {
  const SettingsScreen({super.key});

  @override
  State<SettingsScreen> createState() => _SettingsScreenState();
}

class _SettingsScreenState extends State<SettingsScreen> {
  bool _syncTheme = false;
  bool _wifiSync = true;
  bool _bluetoothSync = false;

  @override
  void initState() {
    super.initState();
    _loadSettings();
  }

  Future<void> _loadSettings() async {
    final prefs = await SharedPreferences.getInstance();
    setState(() {
      _syncTheme = prefs.getBool('syncTheme') ?? false;
      _wifiSync = prefs.getBool('wifiSync') ?? true;
      _bluetoothSync = prefs.getBool('bluetoothSync') ?? false;
    });
  }

  Future<void> _saveSetting(String key, bool value) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(key, value);
  }

  @override
  Widget build(BuildContext context) {
    final themeProvider = context.watch<ThemeProvider>();

    return Scaffold(
      appBar: AppBar(
        title: const Text('Settings'),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: ListView(
          children: [
            const Text('Theme', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 10),
            const Text('Primary Color'),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            ColorPicker(
              pickerColor: themeProvider.primaryColor,
              onColorChanged: (color) {
                context.read<ThemeProvider>().setPrimaryColor(color);
              },
              showLabel: true,
              pickerAreaHeightPercent: 0.5,
            ),
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
              title: const Text('Sync Theme Across Devices'),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
              value: _syncTheme,
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
              onChanged: (value) {
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
                setState(() => _syncTheme = value);
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
                _saveSetting('syncTheme', value);
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
              },
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            ),
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Sync Methods', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
              title: const Text('WiFi/Local Network Sync'),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
              value: _wifiSync,
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
              onChanged: (value) {
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
                setState(() => _wifiSync = value);
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
                _saveSetting('wifiSync', value);
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
              },
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            ),
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
              title: const Text('Bluetooth Sync'),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
              value: _bluetoothSync,
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
              onChanged: (value) {
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
                setState(() => _bluetoothSync = value);
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
                _saveSetting('bluetoothSync', value);
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
              },
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            ),
            DropdownButtonFormField<int>(
              decoration: const InputDecoration(labelText: 'Historical Information Level',
              value: context.watch<TreeProvider>().colonizationLevel,
              items: const [
                DropdownMenuItem(value: 0, child: Text('None')),
                DropdownMenuItem(value: 1, child: Text('Native Lands')),
                DropdownMenuItem(value: 2, child: Text('Colonization + Native')),
                DropdownMenuItem(value: 3, child: Text('Native First with Romanization')),
                DropdownMenuItem(value: 4, child: Text('Native Lands Only')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setColonizationLevel(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('Done'),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Date Format',
              value: context.watch<TreeProvider>().dateFormat,
              items: const [
                DropdownMenuItem(value: 'dd MMM yyyy', child: Text('DD MMM YYYY')),
                DropdownMenuItem(value: 'MM/dd/yyyy', child: Text('MM/DD/YYYY')),
                DropdownMenuItem(value: 'yyyy-MM-dd', child: Text('YYYY-MM-DD')),
              ],
              onChanged: (value) => context.read<TreeProvider>().setDateFormat(value!),
            ),
            const SizedBox(height: 20),
            const Text('Paired Devices', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            ),
          ],
        ),
      ),
    );
  }
}
